Repository HGustavs/LenaSYS, pull requests merged in 2018-04, with the labels that each got.

#4257 G2 a16rasja 4104
  DuggaSys/diagram.js
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_mouse.js
Labels: Group2-2018

#4261 Changed the default color and line width
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4266 The enter key can now be pressed to apply changed appearance of objects
  DuggaSys/diagram.php
  DuggaSys/diagram_dialog.js
Labels: Diagram, Group2-2018

#4277 G2 a16rasja 4104 - fixed
  DuggaSys/diagram_mouse.js
Labels: Group2-2018

#4285 G2 b16petma 4265
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_mouse.js
Labels: Group2-2018

#4287 G2 a16juleh 3937
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4301 G2-c16linst-3988
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Group2-2018

#4304 G2 - a16rasja and c16carbe - 4280
  DuggaSys/diagram.php
  DuggaSys/diagram_toolbox.js
  Shared/css/style.css
Labels: Group2-2018

#4310 G2 b16andka 4207
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_mouse.js
Labels: Group2-2018

#4321 G2 a16adala 4283
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Group2-2018

#4324 #4307 - On branch #4181, arrow on collapsed menus are displayed incorrectly
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4359 Removed functionality for figures
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_slask.js
Labels: Group2-2018

#4357 Changed variable names endX and endY to ex and ey
  DuggaSys/diagram.js
Labels: Group2-2018

#4367 The top object is now selected when objects are stacked
  DuggaSys/diagram.js
Labels: Group2-2018

#4365 Removed arity-code
  DuggaSys/diagram.js
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_slask.js
  DuggaSys/diagram_symbol.js
Labels: Group2-2018

#4363 #4208 - Issue with writing headings etc. that include quotes (")
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4372 G2 c16carbe refactorization
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group2-2018

#4331 #4330 - SectionEd: Cannot remove list entry
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4386 G2 b16nicbr and a15setno 4027
  DuggaSys/preview.php
  DuggaSys/showdoc.php
  Shared/css/markdown.css
  Shared/markdown.js
Labels: Group2-2018

#4411 G2 a16adala 4335
  DuggaSys/preview.php
Labels: Group2-2018

#4412 #4381 - SectionEd: Duplicating items when going from hidden to public
  DuggaSys/sectioned.php
  Shared/dugga.js
Labels: Grupp 3 (2018)

#4429 #4426 Re:do. Issue #4188 was fixed, but the fix seems to have been lost during the merge.
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4434 Possible to de-select items with ctrl/cmd-key
  DuggaSys/diagram.js
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#4448 #4435 SectionED: Problems with the dynamic hamburger menu for navigation
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018)

#4451 Spacebar works correctly to toggle movearound
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#4462 #4453 Clean up the old table code related to SortableTable
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#4465 #4407 - SectionEd: CollapsableMenu-Arrow-Icon no longer works
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#4469 Removed points when a relation is targeted
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4494 #4477 DuggaED: Working with implementing the sortable-table. Reinsert all columns
  DuggaSys/duggaed.js
  DuggaSys/duggaedservice.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: SortableTable

#4509 G2-a16timsc-4379
  DuggaSys/diagram_symbol.js
Labels: Group2-2018

#4522 Fix for issue 4430
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
Labels: Group2-2018

#4516 #4515 - SectionEd: Yellow border not removed when pressing escape
  Shared/dugga.js
Labels: Grupp 3 (2018)

#4492 #4480 - SectionEd: Page title always showing Section Editor
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4523 G2 c16linst 4486
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: Group2-2018

#4493 replaced access table with sortable table
  DuggaSys/accessed.js
  DuggaSys/accessed.php
  DuggaSys/accessedservice.php
Labels: SortableTable

#4511 #4505 DuggaEd: Translate data into readable values
  DuggaSys/duggaed.js
  DuggaSys/duggaedservice.php
  Shared/SQL/init_db.sql
Labels: SortableTable

#4473 #4467 - SectionEd: The arrows show a strange behaviour
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#4542 G2 a16rasja 4464
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_symbol.js
  DuggaSys/forms/attribute_appearance.php
  DuggaSys/forms/entity_appearance.php
  DuggaSys/forms/font_appearance.php
  DuggaSys/forms/relation_appearance.php
Labels: Group2-2018

#4559 G2 a16juleh 4524
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
Labels: Group2-2018

#4583 G2 c16linst 4251
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group2-2018

#4594 G2-b16petma-4479 housekeeping strategy
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#4609 Fix for issue #4251
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group2-2018

#4606 #4495 - Implement edit to sortable table in duggaed
  DuggaSys/duggaed.js
  DuggaSys/duggaedservice.php
  Shared/dugga.js
Labels: SortableTable

#4506 #4476 - SectionEd: Check indentation in sectioned.js
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4617 #4482 DuggaED: Working with implementing the sortable-table. Buttons for adding a dugga
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/duggaedservice.php
Labels: Grupp 3 (2018)

#4615 #4565 - SectionEd: Grade overview with Pie Chart, Part 1 (ref #4185)
  DuggaSys/swimlane.js
  DuggaSys/swimlane.php
  DuggaSys/swimlaneservice.php
Labels: Grupp 3 (2018)

#4626 G2 c16linst 4527
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: Group2-2018

#4635 Revert "#4584 merge with new weekly branch."
  DuggaSys/accessed.js
  DuggaSys/accessed.php
  DuggaSys/accessedservice.php
  DuggaSys/diagram.js
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_slask.js
  DuggaSys/diagram_symbol.js
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/duggaedservice.php
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
  DuggaSys/forms/attribute_appearance.php
  DuggaSys/forms/entity_appearance.php
  DuggaSys/forms/font_appearance.php
  DuggaSys/forms/line_appearance.php
  DuggaSys/forms/relation_appearance.php
  DuggaSys/migration.php
  DuggaSys/preview.php
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  DuggaSys/resultedservice.php
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/submissions/2/97732/13/Andersson_Anna_a99annan/Utbildningsplan_WEBUG1.pdf
  DuggaSys/submissions/2/97732/13/Andersson_Anna_a99annan/coursesyspw.php41.zip
  DuggaSys/submissions/2/97732/13/Andersson_Lars_a99laran/Kursplan_IT351G1.pdf
  DuggaSys/submissions/2/97732/13/Andersson_Lars_a99laran/coursesyspw.php41.zip
  DuggaSys/submissions/2/97732/13/Johansson_Maria_a99marjo/Utbildningsplan_WEBUG1.pdf
  DuggaSys/submissions/2/97732/13/Johansson_Maria_a99marjo/coursesyspw.php41.zip
  DuggaSys/submissions/2/97732/13/Olsson_Nils_a99nilol/Utbildningsplan_WEBUG1.pdf
  DuggaSys/submissions/2/97732/13/Olsson_Nils_a99nilol/coursesyspw.php41.zip
  DuggaSys/swimlane.js
  DuggaSys/swimlane.php
  DuggaSys/swimlaneservice.php
  DuggaSys/templates/clipping_masking_dugga.js
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
  Shared/dugga.js
  Shared/icons/code-icon.svg
  Shared/icons/heading-icon.svg
  Shared/icons/markdownPen.svg
  Shared/icons/moment-icon.svg
  Shared/icons/section-icon.svg
  Shared/icons/test-icon.svg
  Shared/loginbox.php
  Shared/loginlogout.php
  Shared/markdown.js
  courses/2/cssdugga-site-1.png
  courses/2/test.png
  install/SQL/testdata.sql
  testfiles/markdown-list-test.md
Labels: Grupp 3 (2018)

#4639 #4388 - DuggaEd: Dialogue-box says "Edit" when creating new
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#4642 #4636 - SectionEd: FAB-button bug
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4647 G2 c16linst a16juleh 4638
  DuggaSys/fileed.js
  DuggaSys/fileed.php
Labels: Group2-2018

#4650 #4644 - SectionEd: Markable FAB
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018)

#4653 G2-b16petma-4479 Clear Diagram clears the point array
  DuggaSys/diagram.js
  DuggaSys/diagram_IOHandler.js
Labels: Diagram, Group2-2018

#4664 G2 a16timsc 4637
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
Labels: Group2-2018

#4676 G2 a16timsc 4668
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, Group2-2018

#4654 #4445 - SectionEd: Change the FAB "+"-buttons position
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4687 G2 a16timsc 4669
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#4685 G2 a16juleh c16linst 4649
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
Labels: Group2-2018

#4666 #4611-SectionEd: Too many spaces around the variable sectionedPageTitle
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4678 #4667 - SectionEd: FAB-button opacity issue
  Shared/css/style.css
Labels: Grupp 3 (2018)

#4684 #4672 - ReFix the Hamburger-button
  DuggaSys/courseedservice.php
  DuggaSys/duggaedservice.php
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4675 #4640 - SectionEd: FAB-button functionality
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4663 #4575 - DuggaEd: New/Edit item-windows on Mobile Browsers
  DuggaSys/duggaed.php
  Shared/css/style.css
Labels: Grupp 3 (2018)

#4688 G2 c16linst 4657
  DuggaSys/fileed.js
Labels: Group2-2018

#4689 Objects have to be connected to each other
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#4693 #4677 - SectionEd: Closing the FAB by pressing elsewhere
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4701 #4507 DuggaED: Working with implementing the sortable-table. Adding "Arrow-functionality"
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/duggaedservice.php
Labels: Grupp 3 (2018)

#4702 #4698 - SectionEd: Closing windows by clicking elsewhere
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4696 #4566 SectionEd: Grade overview with Pie Chart, Part 2 (ref #4185)
  DuggaSys/swimlane.js
Labels: Grupp 3 (2018)

#4700 #4699 - SectionEd: Icons in FAB-bubbles markable
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4705 G2 a16timsc 4697
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#4707 Fixed back button redirection functionality
  DuggaSys/accessed.php
Labels: Group 1 (2018)

#4717 #4661-SectionEd: Incorrect indentations in sectioned.php
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4719 G2-b16petma-4695
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4656 Created new dropdown function
  DuggaSys/accessed.js
Labels: Group 1 (2018)

#4721 G2 b16ponpe 4567
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#4720 G2 c16carbe and a16rasja 4718
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_symbol.js
Labels: Group2-2018

#4722 G2-a15setno_and_b16nicbr-4529
  DuggaSys/preview.php
  Shared/markdown.js
Labels: Group2-2018, Markdown

#4727 #4673-DuggaEd: Less ambiguous confirmation-message
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#4710 G2-a15setno_and_b16nicbr-4648
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
Labels: Group2-2018, Markdown

#4733 #4716 Sub-Issue: Delete-button functionallity from #4706
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#4731 G2-b16ponpe-4725
  DuggaSys/diagram_dialog.js
Labels: Diagram, Group2-2018

#4734 G2 c16carbe and a16rasja 4728
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group2-2018

#4726 G2 c16linst a16juleh 4691
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
Labels: Group2-2018

#4735 #4729-DuggaED: Update confirmation-box
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#4748 G2 b16andka 4403
  DuggaSys/diagram_symbol.js
Labels: Group2-2018

#4740 #4690 - SectionEd: Create new type "Group Activity"
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4757 #4658 SectionEd: Unable to delete certain Headings
  DuggaSys/sectioned.js
  DuggaSys/sectionedservice.php
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#4759 G2 a16juleh c16linst 4738
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group2-2018

#4761 #4703 - SectionEd: Enter-key = Yes/Finalize
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4782 #4713 - Sub-Issue: Edit-button functionallity from
  DuggaSys/duggaed.js
  Shared/dugga.js
Labels: Grupp 3 (2018)

#4781 G2 a16rasja 4752
  DuggaSys/diagram_dialog.js
  DuggaSys/forms/class_appearance.php
Labels: Group2-2018

#4786 #4652
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/duggaedservice.php
Labels: Grupp 3 (2018)

#4789 #4714 Sub-Issue: Save-button functionallity from #4706
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#4780 #4773 - SectionEd: Pop-up closes when draging & releasing the mouse button (Chrome)
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4792 #4737 - SectionEd: New Item state isn't being registered
  DuggaSys/sectioned.js
  DuggaSys/sectionedservice.php
Labels: Grupp 3 (2018)

#4797 #4795 - SectionEd: The type "Group Activity" includes fields that are not hidden
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#4796 G2 a16juleh c16linst 4791
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group2-2018

#4805 #1928 - Added gradesystem field on moment
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4799 G2 a16timsc 4776
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#4812 G2-a16adala-4763
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
  Shared/markdown.js
Labels: Group2-2018, Markdown

#4813 G2-b16petma-4783
  DuggaSys/diagram.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4814 #4712 - Sub-Issue: Submit-button functionallity from
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/duggaedservice.php
Labels: Grupp 3 (2018)

#4815 G2 a16rasja 4766
  DuggaSys/diagram.js
  DuggaSys/diagram_dialog.js
  DuggaSys/forms/class_appearance.php
Labels: Group2-2018

#4808 #4769 - SectionEd: Reduce and refine the code used for the FAB-button
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018)

#4816 G2 c16carbe 4778
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram

#4800 Replaced the table in resulted with sortable table
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  DuggaSys/resultedservice.php
  Shared/css/style.css
Labels: SortableTable

#4845 #4836 Add message functionallity inside FAB
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4837 #4833 - SectionEd: Message option doesn't have "tabs"
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4864 #4828 Change name from message of the day to Message inside sectioned
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4865 G2 c16linst a16juleh 4775
  DuggaSys/fileed.js
  Shared/SortableTableLibrary/coursesyspw.php
  Shared/SortableTableLibrary/sortableTable.js
  Shared/SortableTableLibrary/sortableTableDemo_sortadvanced.html
  Shared/css/style.css
Labels: Group2-2018

#4866 G2 c16carbe 4826
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4867 G2-b16nicbr-4829
  Shared/css/style.css
Labels: Group2-2018, Markdown

#4857 #4827 Creating a group column in Access (Part 1 of #4169)
  DuggaSys/accessed.js
  DuggaSys/accessedservice.php
Labels: Grupp 3 (2018)

#4871 G2-b16petma-4783
  DuggaSys/diagram.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4875 G2 a16rasja 4831
  DuggaSys/diagram.php
  DuggaSys/diagram_toolbox.js
  Shared/css/style.css
Labels: Group2-2018

#4873 #4715 Sub-Issue: Enable/Disable-button functionallity from #4706
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/duggaedservice.php
Labels: Grupp 3 (2018)

#4876 G2 a16timsc 4852
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4877 G2 c16carbe 4868
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4888 #4846 - SectionEd: Creating a new item through the FAB list the entry stays underneath the FAB button
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4859 #4741 DuggaED: Variants window should display dugga name
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  Shared/dugga.js
Labels: Grupp 3 (2018)

#4889 G2 a16rasja 4841
  DuggaSys/diagram.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4891 G1 issue 4794
  DuggaSys/accessed.js
Labels: Group 1 (2018)

#4879 Added logging to the custom 404 page.
  Shared/basic.php
  errorpages/404.php
Labels: Group 1 (2018)

#4894 #4839 - Fix issue when the arrow is included in ellipsis. Also fixed indentet…
  DuggaSys/duggaed.js
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018)

#4881 G2 a16juleh c16linst 4762
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
  Shared/icons/add-icon.svg
  Shared/icons/course_local-icon.svg
  Shared/icons/global-icon.svg
  Shared/icons/link-icon.svg
  Shared/icons/version_local-icon.svg
Labels: Group2-2018

#4893 #4880 - SectionEd: All options when creating an item should be reverted
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4913 G2-b16ponpe-4203
  DuggaSys/diagram.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#4906 G2 a16timsc 4878
  DuggaSys/diagram_symbol.js
  DuggaSys/forms/attribute_appearance.php
Labels: Diagram, Group2-2018

#4911 #4732 - Fix issue when updating variant.
  DuggaSys/duggaed.js
  DuggaSys/duggaedservice.php
Labels: Grupp 3 (2018)

#4917 #4842 - SectionEd: Editing a test while no links available
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4921 G2 a16juleh c16linst 4918
  DuggaSys/fileed.js
  Shared/css/style.css
Labels: Group2-2018

#4922 G2 c16linst a16juleh 4919
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
  Shared/css/style.css
Labels: Group2-2018
