Repository HGustavs/LenaSYS, pull requests merged in 2018-05, with the labels that each got.

#4938 G2 b16andka 4928
  DuggaSys/fileed.js
  DuggaSys/fileed.php
Labels: File Editor, Group2-2018

#4939 #4935_Removed error, and fixed naming.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018)

#4945 Fix for #4746
  DuggaSys/fileed.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: File Editor, Group2-2018

#4953 #4840 - SectionEd: Tests can be created without any links
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4952 #4929 - SectionEd: Items with invalid names can be created
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#4964 G2-b16petma-4754
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#4962 #4612 - DuggaEd: Able to save even though the title has illegal characters
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018)

#4967 #4956 - SectionEd: Update generic code for FAB in sectioned.js
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4970 #4941 - Fix problem when adding dugga.
  DuggaSys/duggaed.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: Grupp 3 (2018)

#4978 G2-b16andka-4961
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
Labels: File Editor, Group2-2018

#4979 G2-b16andka-4974
  DuggaSys/fileed.js
Labels: File Editor, Group2-2018

#4940 G2-a15setno-4874
  DuggaSys/fileed.php
  Shared/markdown.js
Labels: Group2-2018, Markdown

#4977 #4971 - DuggaED: Error when closing windows with escape.
  Shared/dugga.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor, Grupp 3 (2018) Sektion-Editor

#4980 #4861 - SectionEd: Default title values on created items through the FAB list
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#4983 Added sorting to access editor
  DuggaSys/accessed.js
  DuggaSys/accessedservice.php
Labels: Group 1 (2018)

#4987 G2-a16rasja-4905
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#4965 Added cell highlighting on resulted table
  DuggaSys/resulted.js
  Shared/css/style.css
Labels: Group 1 (2018)

#4989 G2-b16andka-4975
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group2-2018

#4988 G2-c16jonha-4936
  DuggaSys/fileed.js
Labels: File Editor, Group2-2018

#4950 #4862 - DuggaEd: Mark the selected variant when editing
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5002 #4892 DuggaED: Fix the styling in the variant editor.
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/duggaedservice.php
  Shared/css/style.css
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#4991 #4597 - DuggaEd: Pressing Escape-button does not clear the error
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5011 #5007 DuggaED: Clicking outside the variant editor should close the window.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018)

#5009 G2 a16timsc 3208
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#5001 Added searching in access editor
  DuggaSys/accessed.js
  DuggaSys/accessed.php
Labels: Group 1 (2018)

#4994 G2 b16andka 4990
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
Labels: Group2-2018

#5013 G2-a15setno-4949
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
  Shared/markdown.js
Labels: Group2-2018

#4946 Added row and cell highligtning for accessed page
  DuggaSys/accessed.js
Labels: Group 1 (2018)

#4947 Fixed bug when grading a newly submitted dugga
  DuggaSys/resulted.js
  DuggaSys/resultedservice.php
Labels: Group 1 (2018)

#5016 #5005 DuggaED: An icon that more clearly links to variants.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5023 G2 b16andka 4986
  DuggaSys/fileed.js
Labels: Group2-2018

#5024 G2-fix-a15setno-4949
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: File Editor, Group2-2018

#5026 G2-b16petma-4957
  DuggaSys/diagram.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5014 G2-b16nicbr-4943 and 4532
  DuggaSys/fileed.php
  Shared/css/style.css
  Shared/icons/insert-photo.svg
  Shared/markdown.js
Labels: Group2-2018, Markdown

#5020 #5018 - SectionEd: Delete group selection option in SectioneEditor
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#5028 G2-b16ponpe-4907
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5022 #5004 - Make it posible to generate variant parameter from the json form.
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5034 G2-b16nicbr-5031
  DuggaSys/fileed.php
  Shared/css/style.css
  Shared/markdown.js
Labels: Group2-2018, Markdown

#5039 G2 c16carbe 4198
  DuggaSys/forms/fillcolor_appearance.php
  DuggaSys/forms/font_appearance.php
  DuggaSys/forms/fontcolor_appearance.php
  DuggaSys/forms/global_appearance.php
  DuggaSys/forms/line-thickness_appearance.php
  DuggaSys/forms/strokecolor_appearance.php
  DuggaSys/forms/textsize_appearance.php
Labels: Diagram, Group2-2018

#5035 G2 a16timsc 4999
  DuggaSys/diagram.php
Labels: Diagram, Group2-2018

#5044 G2 b16andka 5003
  DuggaSys/fileed.js
  DuggaSys/fileed.php
Labels: Group2-2018

#5052 #5038 - DuggaED: Saving dugga changes opens the variant editor.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5048 #5027 - SectionED: With FAB, creating link and code items should not be possible when nothing is stored in files
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#4976 #4623 - DuggaEd: New Dugga, all fields must be filled in order to create new dugga
  DuggaSys/duggaed.js
  DuggaSys/duggaedservice.php
  DuggaSys/migration.php
  Shared/dugga.js
  install/SQL/init_db.sql
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5032 #4194-Moved the deadline icon.
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5050 G2-b16petma-5036
  DuggaSys/diagram.js
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#5058 #5033 DuggaED: Styling for duggas without variants.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5041 Added row filter for teachers and searchterm in resulted
  DuggaSys/resulted.js
Labels: Group 1 (2018)

#5062 #5055 - Font weight is different in Firefox on macOS
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5060 G2-b16ponpe-4997
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5066 #5063 DuggaED: Placement for the "+" button.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5070 #5029 - SectionED: With Add button, creating link and code items should not be possible when nothing is stored in files
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018)

#5069 G2-b16petma-5056
  DuggaSys/diagram.js
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#5072 G2-b16ponpe-5064
  DuggaSys/diagram_mouse.js
Labels: Group2-2018

#5080 G2 b16andka 5015
  DuggaSys/fileed.js
Labels: Group2-2018

#5065 G2 a16timsc 5042
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#5083 G2-b16nicbr-5054
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
  Shared/markdown.js
Labels: Group2-2018, Markdown

#5077 #5068 DuggaED: Add padding around the table.
  DuggaSys/duggaed.php
  DuggaSys/sectioned.php
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#4973 #4963 - SectionEd: Creating option to press Enter when reveiving a error/delete message to close.
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#5098 #5091 DuggaEditor: Add line on left side in table.
  Shared/css/style.css
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5101 G2-b16petma-5037
  DuggaSys/diagram.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5097 G2 b16andka 4431
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
  DuggaSys/filereceive.php
  DuggaSys/filereceive_preview.php
  Shared/css/style.css
  Shared/markdown.js
Labels: Group2-2018, Markdown

#5118 #5105 DuggaED: Sortable table should be sortable
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5126 #5019 DuggaED: Fixes around the icons in the variant table.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#4972 Changed the dropdown menu to a datalist.
  DuggaSys/accessed.js
  DuggaSys/accessed.php
  DuggaSys/accessedservice.php
Labels: Group 1 (2018)

#5129 G2-c16jonha-5000
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: File Editor, Group2-2018

#5104 Fixed column filtering in sortable table
  DuggaSys/resulted.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group 1 (2018)

#5128 #4350 Part 4 - Check of code standard in HGustavs/LenaSYS/DuggaSYS/sectioned.js
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5094 #4760 - Migration to remove old groupstable.
  DuggaSys/migration.php
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Grupp-relaterad

#5127 #5111 - CourseED: Groups for each course
  DuggaSys/courseedservice.php
Labels: Grupp 3 (2018), Grupp 3 (2018) Grupp-relaterad

#5114 #5112 - SectionED: Old group related code
  DuggaSys/sectionedservice.php
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5131 #5093 - SectionED: SQL pop-up message
  DuggaSys/sectionedservice.php
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5122 #5117 DuggaED: Variants table should be sortable
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5137 #5092 - SectionED & DuggaED: Scroll-position
  DuggaSys/duggaed.js
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#5139 G2 b16andka 5116
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/filereceive_preview.php
  Shared/css/style.css
Labels: Group2-2018

#5150 G2-a16rasja-5046
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#5153 #5142 - SectionED: Entry table bottom-margin
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5151 #5136 DuggaED: Fix magic heading in the dugga table and the variant table.
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5158 #5148 DuggaED: Start date is not registered
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5125 #4294 Part 3 - Check of code standard in HGustavs/LenaSYS/DuggaSYS/sectioned.js
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5155 Fixed the selected value by performing a database update to the selec…
  DuggaSys/accessed.js
Labels: Group 1 (2018)

#5175 #4884 - Long press on FAB
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#5138 Removed checkbox for FnameLnameSSN and old code for filtering
  DuggaSys/resulted.js
Labels: Group 1 (2018)

#5156 G2 b16andka 5108
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/filereceive_preview.php
  Shared/css/style.css
  Shared/markdown.js
Labels: Group2-2018

#5176 #5086 - SectionED: Only a FAB button on mobile version
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5172 #5166 - DuggaED: Remove answer column in variants
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5146 #4549 - DuggaEd: Check Mobile browsing
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5047 #5045 - SectionEd: Timestamp is wrong, shown twice
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5184 Added bar diagram to contributions
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  DuggaSys/contributionservice.php
Labels: Group 1 (2018), Group 1 (2018) Contribution

#5144 G2-a15setno-b16nicbr-5081
  DuggaSys/fileed.php
  Shared/css/style.css
  Shared/markdown.js
Labels: File Editor, Group2-2018, Markdown

#5178 G2 a16rasja 5161
  DuggaSys/diagram.php
  DuggaSys/diagram_toolbox.js
Labels: Diagram, Group2-2018

#5185 G2 a16rasja 5173
  Shared/css/style.css
Labels: Diagram, Group2-2018

#5177 Uses correct path to the SVG files
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group 1 (2018)

#5171 Added sorting to the table on the resulted page
  DuggaSys/resulted.js
Labels: Group 1 (2018)

#5187 Added a new background color for duggas that have been submitted after the deadline
  DuggaSys/resulted.js
  Shared/css/style.css
Labels: Group 1 (2018)

#5188 Fix for MOTD covering last course
  DuggaSys/courseed.js
Labels: Group 1 (2018)

#5186 G2-c16jonha-4998
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: File Editor, Group2-2018

#5195 #4352 Part 6 - Check of code standard in HGustavs/LenaSYS/DuggaSYS/sectioned.js
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#5194 G2-b16nicbr-5054
  DuggaSys/fileed.php
Labels: Group2-2018, Markdown

#5199 G2-b16andka-5196
  Shared/SortableTableLibrary/sortableTable.js
Labels: File Editor, Group2-2018

#5204 Fixed access examiner sorting bug
  DuggaSys/accessed.js
Labels: Group 1 (2018)

#5208 G2 a16adala 5087 2
  DuggaSys/diagram.php
Labels: Group2-2018

#5201 Changed hover in contribution
  DuggaSys/contribution.js
Labels: Group 1 (2018)

#5209 G2 a16rasja 5179
  DuggaSys/diagram.php
  Shared/css/style.css
  Shared/icons/redo.svg
  Shared/icons/undo.svg
Labels: Diagram, Group2-2018

#5212 #4380 DuggaEd: Change the button "Add Dugga" to a "+"-button
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#5215 G2 c16carbe 5084
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5213 #4655 - SectionEd: Clarification of the Hamburger-menu
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5218 #4169 - Create mutliple select for access to users.
  DuggaSys/accessed.js
  DuggaSys/accessedservice.php
  Shared/css/style.css
Labels: Grupp 3 (2018), Grupp 3 (2018) Grupp-relaterad

#5221 #5162 - DuggaED: Ellipse long parameters
  DuggaSys/duggaed.js
  Shared/css/style.css
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor

#5217 G2 b16andka 5193
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
Labels: File Editor, Group2-2018

#5223 G2 c16carbe 5222
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5203 A bugg fix that solves incorrect sorting of duggas on the result page
  DuggaSys/resulted.js
Labels: Group 1 (2018)

#5225 G2-b16petma-5145
  DuggaSys/diagram.php
Labels: Diagram, Group2-2018

#5227 G2-b16ponpe-5082
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5230 G2 a16adala 5192
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: Group2-2018

#5229 #5123 DuggaED: Rework variant view (Mock-up)
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5231 G2-a15setno-5149
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: File Editor, Group2-2018, Markdown

#5240 #5233 - SectionED: Icon bug in the statistics tab
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018), Grupp 3 (2018) Sektion-Editor

#5238 G2 c16carbe 3747
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5206 #5119 - SectionED: Change the old datepicker to the browsers default
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5242 G2 c16carbe 5239
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, Group2-2018

#5250 G2-c16jonha-4993
  DuggaSys/fileed.js
  Shared/css/style.css
Labels: File Editor, Group2-2018

#5251 G2-b16petma-5183
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#5254 G2 b16andka 5244
  DuggaSys/fileed.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: File Editor, Group2-2018

#5247 #5232 DuggaED: Implement further the search functionality
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#5261 #5214 DuggaED: Creating tests shouldn't be possible if you don't have access
  DuggaSys/duggaed.js
  DuggaSys/duggaedservice.php
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5268 G2-b16ponpe-5180
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#5270 #5243 - SectionED: Insert the piechart in the new statistics section
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5269 #5248-DuggaED: Add a title
  DuggaSys/duggaed.php
Labels: Grupp 3 (2018)

#5264 G2 b16andka 5256
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
Labels: File Editor, Group2-2018

#5280 #5277 - DuggaED: Change every "let" to "var"
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018)

#5279 #5275 - SectionED: Change every "let" to "var"
  DuggaSys/sectioned.js
Labels: Grupp 3 (2018)

#5276 #5249 SPECIAL CASE
  DuggaSys/duggaed.php
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5255 Line diagram for contribution page
  DuggaSys/contribution.js
  DuggaSys/contribution.php
Labels: Group 1 (2018)

#5278 G2 c16carbe 5181
  DuggaSys/diagram.js
Labels: Diagram, Group2-2018

#5300 #5287 SectionED: Fab button is not visible
  DuggaSys/duggaed.js
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5282 G2 a16rasja 5245
  DuggaSys/diagram_dialog.js
  DuggaSys/forms/global_appearance.php
Labels: Diagram, Group2-2018

#5305 Minimode now renders students in a single line mode
  DuggaSys/resulted.js
  Shared/css/style.css
Labels: Group 1 (2018)

#5303 G2 c16carbe and a16rasja 5284
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_symbol.js
  DuggaSys/forms/line_appearance.php
Labels: Diagram, Group2-2018

#5302 Added a dropdown menu for chosing a uid for the responsible column in…
  DuggaSys/accessed.js
  DuggaSys/accessed.php
  DuggaSys/accessedservice.php
Labels: Group 1 (2018)

#5308 Cells now get colors based on grade in minimode
  DuggaSys/resulted.js
Labels: Group 1 (2018)

#5304 #5286 DuggaED: Hide more content
  DuggaSys/duggaed.js
Labels: Grupp 3 (2018)

#5309 G2-b16petma-5291
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#5311 G2-b16ponpe-5296
  DuggaSys/diagram_mouse.js
Labels: Diagram, Group2-2018

#5313 G2 a16rasja 5295
  DuggaSys/diagram.js
  DuggaSys/diagram_dialog.js
Labels: Diagram, Group2-2018

#5314 G2 a16rasja 5312
  DuggaSys/diagram_toolbox.js
  Shared/css/style.css
Labels: Diagram, Group2-2018

#5285 G2-b16nicbr-a15setno-5210
  DuggaSys/fileed.php
  Shared/css/markdown.css
  Shared/css/style.css
  Shared/markdown.js
Labels: Group2-2018, Markdown

#5325 G2-b16nicbr-5321
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: Group2-2018, Markdown

#5327 #5324 - SectionED: Hide the statistics tab on mobile
  Shared/css/style.css
Labels: Grupp 3 (2018)

#5326 G2-b16ponpe-5310
  DuggaSys/diagram.php
Labels: Diagram, Group2-2018
