Repository HGustavs/LenaSYS, pull requests merged in 2019-04, with the labels that each got.

#5660 Fix for issue #5636
  DuggaSys/diagram_IOHandler.js
Labels: groupA2019, underReviewGruppA2019

#5687 Added teacher column to user_course and groupKind column to listentries
  install/SQL/init_db.sql
Labels: gruppC2019

#5667 Fix for issue #5511
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_dialog.js
Labels: groupA2019, underReviewGruppA2019

#5676 Added additional comments regarding symbols#5674
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: groupA2019, underReviewGruppA2019

#5697 Grupp b2019#5604
  .vs/slnx.sqlite
  DuggaSys/sectioned.js
Labels: GruppB2019

#5645 Changed noup COURSE to SECTION in contribution
  DuggaSys/contribution.php
Labels: gruppC2019

#5682 Fixed issue #5525
  DuggaSys/diagram_forms.php
Labels: groupA2019, underReviewGruppA2019

#5673 Rows in accessed table is now red if user requested password reset
  DuggaSys/accessedservice.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: gruppC2019

#5684 Removed dateSize from the media query for small devices
  Shared/css/style.css
Labels: gruppC2019

#5672 Fix for issue #5647
  install/install.php
Labels: groupA2019, underReviewGruppA2019

#5699 Fix for issue #4244
  DuggaSys/diagram.php
  DuggaSys/diagram_toolbox.js
  Shared/css/style.css
  Shared/icons/rotateButton.svg
Labels: Diagram, groupA2019, underReviewGruppA2019

#5716 Grupp b2019#5606
  DuggaSys/sectioned.js
Labels: GruppB2019, activeGruppB2019

#5719 Fix #5681
  DuggaSys/accessedservice.php
  DuggaSys/courseedservice.php
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
Labels: GruppB2019, activeGruppB2019

#5702 Update accessedservice.php #5625
  DuggaSys/accessedservice.php
Labels: GruppB2019, activeGruppB2019

#5732 GruppB2019#5600
  DuggaSys/sectioned.php
Labels: GruppB2019, activeGruppB2019

#5741 GruppC: Fix for issue #5691
  Shared/navheader.php
Labels: gruppC2019

#5665 Removed templates dir. Fixes #5664
  DuggaSys/accessedservice.php
  templates/test.html
Labels: gruppC2019

#5756 Update resulted.js
  DuggaSys/resulted.js
Labels: GruppB2019, activeGruppB2019

#5706 Fix for #5686
  DuggaSys/diagram.js
Labels: Diagram, activeGruppA2019, groupA2019

#5754 Grupp b2019 #5633
  DuggaSys/resulted.js
  DuggaSys/resulted.php
Labels: GruppB2019, activeGruppB2019

#5734 Grupp a2019#5663
  DuggaSys/diagram_new_function_names.txt
  DuggaSys/diagram_new_variable_names.txt
Labels: Diagram, activeGruppA2019, groupA2019

#5773 Grupp b2019#5633
  DuggaSys/resulted.js
  DuggaSys/resulted.php
Labels: GruppB2019, activeGruppB2019

#5758 Fix for #5695
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, groupA2019

#5809 Added documentation regarding preview lines
  DuggaSys/diagram_mouse.js
Labels: Diagram, groupA2019

#5801 Snap to grid menu option moved to "Align" category - Fix for #5763
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#5813 Fixed typo on documentation in diagram_symbol.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, gruppA2019

#5822 Fix for issue #5712
  DuggaSys/diagram_IOHandler.js
Labels: Diagram, gruppA2019

#5823 Update style.css fixed fab-btn background color
  Shared/css/style.css
Labels: gruppC2019

#5834 Removed back button from Course Editor page
  Shared/navheader.php
Labels: gruppC2019

#5817 Update sectioned.php fixed upper plus(add new item)
  DuggaSys/sectioned.php
Labels: gruppC2019

#5791 Made FAB in courseed uniform with the rest, moved FAB in sectioned slightly to the left.
  DuggaSys/courseed.js
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: gruppC2019

#5838 Grupp b2019 w#5662
  DuggaSys/resulted.js
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#5847 Pull request to branch gruppB2019W16 #5614
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/sectionedservice.php
Labels: GruppB2019, activeGruppB2019

#5855 Added ENGINE=InnoDB to tables that did not have it, fixes #5735
  install/SQL/init_db.sql
Labels: gruppC2019

#5827 Fixed the issue #5782
  DuggaSys/sectioned.js
  Shared/css/style.css
  Shared/dugga.js
Labels: gruppC2019

#5860 Remove and ignore .vs folder
  .gitignore
  .vs/slnx.sqlite
Labels: gruppC2019

#5794 Fix for issue #3752
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#5798 Fix for issue #5736
  DuggaSys/diagram.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, gruppA2019

#5799 Issue #5709 fixed. Variables checked against numbers
  DuggaSys/diagram_toolbox.js
Labels: Diagram, gruppA2019

#5800 Fix for issue #5639
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#5802 Fix issue #5675
  DuggaSys/diagram.js
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_symbol.js
Labels: Diagram, gruppA2019

#5815 Fix#2 for issue #5746
  DuggaSys/diagram.js
  DuggaSys/diagram_mouse.js
Labels: Diagram, gruppA2019

#5819 Fix for #3410
  DuggaSys/diagram.js
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
  DuggaSys/diagram_toolbox.js
Labels: Diagram, gruppA2019

#5824 Add checkboxes to diagram menu - Fix for issue #5694
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#5830 Fix for issue #5711
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_symbol.js
  DuggaSys/diagram_toolbox.js
Labels: Diagram, gruppA2019

#5839 Update sectioned.php
  DuggaSys/sectioned.php
Labels: GruppB2019, activeGruppB2019

#5862 #5705: remove unused swimlane
  DuggaSys/swimlane.js
  DuggaSys/swimlane.php
  DuggaSys/swimlaneservice.php
  Shared/SortableTableLibrary/style.css
  Shared/css/style.css
  Shared/dugga.js
  Shared/navheader.php
Labels: GruppB2019, activeGruppB2019

#5836 Changed textfield constraints for root password - Fix for #5720
  install/install.php
Labels: activeGruppA2019, gruppA2019

#5863 Fixed issue #5804 and #5821 (which was referenced in issue #5804)
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#5869 Fixed the drawing squares bug - Fix for #5534
  DuggaSys/diagram.php
  DuggaSys/diagram_figure.js
Labels: Diagram, activeGruppA2019, gruppA2019

#5871 Added documentation to diagramservice.php - Fix for issue #5818
  DuggaSys/diagramservice.php
Labels: Diagram, activeGruppA2019, gruppA2019

#5831 Fix for issue #5747
  DuggaSys/diagram_symbol.js
Labels: Diagram, gruppA2019

#5805 Made a dugga that loads contribution.php in an iframe
  DuggaSys/sectionedservice.php
  DuggaSys/showDugga.php
Labels: gruppC2019

#5881 Editing variants submission row fixex
  DuggaSys/duggaed.js
Labels: gruppC2019

#5861 Changed cursor and icon for Group Members link
  DuggaSys/sectioned.js
  Shared/icons/group-iconDrk.svg
Labels: gruppC2019

#5892 Fix issues caused by merge problems resulting in missing code
  DuggaSys/resulted.js
Labels: gruppC2019

#5852 Fixed stripping of redundant slashes on new branch
  install/install.php
Labels: gruppC2019

#5867 Gruppc2019w16_1887
  DuggaSys/codeviewer.js
  DuggaSys/codeviewer.php
  Shared/css/style.css
Labels: gruppC2019

#5848 Fixed issue #5846
  Shared/css/style.css
Labels: gruppC2019

#5797 Assign key numbers to variables for increased readability
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#5905 Fixed sorting in access table.
  DuggaSys/accessed.js
Labels: gruppC2019

#5927 Updated the URL to git repo.
  DuggaSys/courseed.js
Labels: gruppC2019

#5909 Fix for issue #5868 Merge files related to diagram
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.php
  DuggaSys/diagram_dialog.js
  DuggaSys/diagram_example.js
  DuggaSys/diagram_figure.js
  DuggaSys/diagram_mouse.js
  DuggaSys/diagram_objects.js
  DuggaSys/diagram_toolbox.js
Labels: Diagram, gruppA2019, highPriority

#5908 Removed duplicate init_db.sql
  Shared/SQL/init_db.sql
  install/SQL/init_db.sql
  install/install.php
Labels: gruppC2019

#5900 Added recursive option for mkdir
  DuggaSys/filereceive.php
Labels: gruppC2019

#5926 Pull request for issue #5619
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#5932 Update style.css #5875
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#5825 Update dugga open pdf new second fix
  Shared/dugga.js
  Shared/icons/external_link_open.svg
Labels: gruppC2019

#5816 New branch version fix for install with coursesys and timeout
  install/install.php
Labels: gruppC2019

#5938 Fix for issue #5928
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#5951 Fix for #5776
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#5952 Fix for issue #5563
  Shared/css/style.css
Labels: File Editor, gruppA2019

#5957 Removed obsolete comment - Fix for #5707
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#5939 Grupp a2019 w16#5897
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_objects.js
Labels: Diagram, activeGruppA2019, gruppA2019, highPriority

#5965 Issue #5533 Pull Request
  DuggaSys/accessed.js
  DuggaSys/resulted.js
  DuggaSys/sectioned.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019, activeGruppB2019

#5978 #5907 - Improvements for responsive design
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  Shared/css/dugga.css
Labels: GruppB2019, activeGruppB2019

#5962 Fix for issue: #5840 "Add whitespace before brackets"
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_IOHandler.php
  DuggaSys/diagram_forms.php
  DuggaSys/diagram_objects.js
Labels: Diagram, activeGruppA2019, gruppA2019, highPriority

#5906 #5903 sortabletable null error
  DuggaSys/resulted.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019, activeGruppB2019

#5954 Fix for issue #5896
  DuggaSys/diagram_forms.php
Labels: Diagram, activeGruppA2019, gruppA2019, highPriority

#5983 Change z-index for FABs to 1 in order to make them appear above trans…
  Shared/css/style.css
Labels: gruppC2019

#5961 GruppC2019W16_5870 Username Shadow changed
  Shared/css/style.css
Labels: gruppC2019

#5950 Change inline-block to block for #Sectionlistc
  Shared/css/style.css
Labels: gruppC2019

#5929 Added coursevers to GET if not already set.
  DuggaSys/showdoc.php
Labels: gruppC2019

#5854 Removed styling on element in sortableTable.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: bug, gruppC2019

#5980 Pull request gruppb2019W16#4960
  DuggaSys/sectioned.js
Labels: GruppB2019

#5986 Solution of issue #5975
  DuggaSys/accessed.js
Labels: gruppC2019

#5984 Deleted non-referenced pages
  Shared/SortableTableLibrary/fixedtest.html
  Shared/SortableTableLibrary/sortableTableDemo.html
  Shared/SortableTableLibrary/sortableTableDemoDB.html
  Shared/SortableTableLibrary/sortableTableDemo_columnfilter.html
  Shared/SortableTableLibrary/sortableTableDemo_edit.html
  Shared/SortableTableLibrary/sortableTableDemo_highlight.html
  Shared/SortableTableLibrary/sortableTableDemo_rowfilter.html
  Shared/SortableTableLibrary/sortableTableDemo_simplest.html
  Shared/SortableTableLibrary/sortableTableDemo_simplest_w_magich.html
  Shared/SortableTableLibrary/sortableTableDemo_sortadvanced.html
  Shared/SortableTableLibrary/sortableTableDemo_sortsimple.html
Labels: GruppB2019, activeGruppB2019

#5971 Fix for issue #5942
  DuggaSys/diagram.js
Labels: Diagram, activeGruppA2019, gruppA2019

#5996 GruppB2019W16#5992 pull request to GruppB2019W16
  DuggaSys/sectioned.js
Labels: GruppB2019, activeGruppB2019

#5995 GruppB2019W16#5858
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#5947 Fix for issue #5837
  DuggaSys/diagram_objects.js
Labels: Diagram, activeGruppA2019, gruppA2019, highPriority

#5991 Add checkboxes - Fix for #5694
  DuggaSys/diagram.js
Labels: Diagram, activeGruppA2019, gruppA2019, highPriority

#5970 Fix for #5708
  DuggaSys/diagram.js
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_IOHandler.php
  DuggaSys/diagram_objects.js
Labels: Diagram, activeGruppA2019, gruppA2019, highPriority

#5979 Fix for "ghost table" and missing heading on tests.
  DuggaSys/duggaed.js
  DuggaSys/fileed.js
  DuggaSys/resulted.js
Labels: gruppC2019

#6000 merge fixing: removes syntax errors, erroneous structure and call before definition
  DuggaSys/resulted.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019, activeGruppB2019

#5880 New time sheet dugga
  DuggaSys/duggaed.js
  DuggaSys/filereceive_dugga.php
  DuggaSys/templates/daily-minutes.html
  DuggaSys/templates/daily-minutes.js
  Shared/SQL/init_db.sql
  Shared/css/dugga.css
  Shared/css/style.css
  Shared/dugga.js
Labels: gruppC2019

#5789 Added a function that initializes the logging db in the install script.
  Shared/basic.php
  install/install.php
Labels: gruppC2019

#5985 Grupp a2019 w16#5890
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019, highPriority

#6007 Fix for issue #6006
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#5989 Grupp a2019 w16#5941
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6009 Make checkboxes more robust, response to #6006 - Fix for #5694
  DuggaSys/diagram.js
Labels: Diagram, activeGruppA2019, gruppA2019

#6014 Grupp a2019 w16#5886
  DuggaSys/diagram.js
Labels: Diagram, activeGruppA2019, gruppA2019

#6057 Fix for issue: #6020 "Diagram.php uses space that isn't used"
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019, highPriority

#6069 Removed duplicate lines
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019

#6071 Fix for issue #6038
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6072 #5887 Pull request for the Mail button in the Result view.
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  DuggaSys/resultedservice.php
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/sectionedservice.php
Labels: GruppB2019, activeGruppB2019

#6088 Gruppc2019w17_5414 Added new icons to accessed.php FAB Longpress
  DuggaSys/accessed.php
  Shared/icons/createUser.svg
  Shared/icons/importUser.svg
Labels: gruppC2019

#6067 spring cleaning: remove uncommented code and console prints
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019, activeGruppB2019

#6107 Grupp c2019 w17 springclean
  Shared/SortableTableLibrary/sortableTable.js
Labels: gruppC2019

#6061 Re-fixed the install constraint on the root pwd textfield
  install/install.php
Labels: activeGruppA2019, gruppA2019

#6079 Fix for issue: #5997 "Menu getting overwritten by the toolbox"
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6097 Update sectioned.js enter to delete section
  DuggaSys/sectioned.js
Labels: gruppC2019

#6093 DuggaEd: Added substr manipulation on the release date
  DuggaSys/duggaed.js
Labels: gruppC2019

#6089 Fixed sorting for password in access table
  Shared/SortableTableLibrary/sortableTable.js
Labels: gruppC2019

#6085 scroll has been emoved #5977
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#6078 New fix for issue #5726
  DuggaSys/courseed.js
  Shared/css/style.css
Labels: gruppC2019

#6115 Added swedish locale to localeCompare
  Shared/SortableTableLibrary/sortableTable.js
Labels: gruppC2019

#6080 DuggaEd: Added verification for Start date and Deadline
  DuggaSys/duggaed.js
Labels: gruppC2019

#6114 styling been fixt#6030
  DuggaSys/resulted.js
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#6070 Removed Dead and commented code
  DuggaSys/accessed.js
Labels: gruppC2019

#6094 Time sheet: Changed day from DATETIME to DATE
  DuggaSys/filereceive_dugga.php
  Shared/SQL/init_db.sql
Labels: gruppC2019

#6125 Removed dead code.
  DuggaSys/duggaed.js
  DuggaSys/fileed.js
  DuggaSys/resulted.js
Labels: gruppC2019

#6130 Adjust FABs to use hover instead of mousedown to display sub-fabs on desktop devices
  DuggaSys/accessed.js
  DuggaSys/duggaed.js
  DuggaSys/fileed.js
  DuggaSys/sectioned.js
  Shared/css/style.css
  Shared/dugga.js
Labels: gruppC2019

#6087 Fixed the toggle on A4 holes - Fix for #6012
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
  Shared/icons/Arrow_down_right.png
Labels: Diagram, activeGruppA2019, gruppA2019

#6111 Fix for #6081
  DuggaSys/codeviewer.js
Labels: CodeViewer, gruppA2019

#6132 Grupp b2019 w17#6101
  DuggaSys/resulted.js
Labels: GruppB2019

#6116 Fixed issue #6083
  Shared/css/style.css
Labels: Diagram, gruppA2019, highPriority

#6117 Fix for #6098 - duplicate code
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019, highPriority

#6133 Masking ssn
  DuggaSys/accessed.js
  DuggaSys/resulted.js
Labels: GruppB2019, activeGruppB2019

#6141 Using utf8mb4 for tables
  Shared/SQL/init_db.sql
Labels: gruppC2019

#6145 Moved comment block in accessed.js
  DuggaSys/accessed.js
Labels: gruppC2019

#6066 Changed 'overflow' to 'overflow-y' for submission view
  DuggaSys/showDugga.php
Labels: gruppC2019

#6077 Modified add button to become lighter on hover.
  Shared/SortableTableLibrary/style.css
  Shared/css/style.css
Labels: gruppC2019

#6157 Removed width of grading buttons
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#6126 Fix for issue #6073
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#6100 Grupp b2019 w17#6022
  DuggaSys/resulted.php
  Shared/css/style.css
Labels: GruppB2019

#6161 Removed filter button
  DuggaSys/resulted.js
Labels: GruppB2019, activeGruppB2019

#6099 Grupp a2019 w17#5143
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6170 Fix issue with FAB button disappearing when pressing esc in some areas
  Shared/dugga.js
Labels: gruppC2019

#6137 Remove unnecessary decimal precision for mouse coordinates - Fix for #5990
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6162 Fix for #5960: Ability to find connected entities
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6153 Set default webkit appearance to none for submit-button-newitem
  Shared/css/style.css
Labels: gruppC2019

#6171 Added table spacing
  Shared/css/dugga.css
Labels: gruppC2019

#6165 Fix for issue #6155 Can't lock after alignment
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6150 Fix for issue #6031
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#6118 Fix for #6113
  DuggaSys/fileed.js
Labels: File Editor, gruppA2019

#6186 Update diagram_objects.js #6179
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019, highPriority

#6183 Grupp a2019 w17#5690
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_objects.js
  Shared/css/style.css
  Shared/icons/diagram_create_umlline.svg
Labels: Diagram, gruppA2019, highPriority

#6109 Grupp a2019 w17#6028
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019, highPriority

#6156 Updated fix for issue#5683 to current master
  DuggaSys/accessedservice.php
  DuggaSys/codeviewerService.php
  DuggaSys/contributionservice.php
  DuggaSys/courseedservice.php
  DuggaSys/resultedservice.php
Labels: gruppC2019
