Repository HGustavs/LenaSYS, pull requests merged in 2019-05, with the labels that each got.

#6482 Grupp b2019 w18#6386
  Shared/css/style.css
Labels: GruppB2019

#6454 Fix for issue #6166: Make variables more readable by adding values ​​to attributes
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6464 Changed text styling for mode - Fix for #6449
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6430 Removed unused database reference
  Shared/loginlogout.php
Labels: gruppC2019

#6426 Fix for issue #6382: Warning when switching modes
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6443 Grupp a2019 w18#6289
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019, highPriority

#6471 Add padding to no access/no items message
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: gruppC2019

#6488 Grupp b2019 w18#6223
  DuggaSys/sectioned.js
Labels: GruppB2019, activeGruppB2019

#6472 Implements and closes #6466 - a sub-issue to #5613
  DuggaSys/resultedconstants.php
  DuggaSys/resultedservice.php
  Shared/SQL/init_db.sql
  install/SQL/2019vt_delta.sql
Labels: GruppB2019, activeGruppB2019

#6486 Fix for #6476
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6316 Fix resizing objects in diagram - #6180
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019, highPriority

#6470 Rouning error solved
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019, highPriority

#6492 Fixed resize issue
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6350 Move TopMenuStatic buttons to main header
  Shared/css/style.css
Labels: gruppC2019

#6483 Moblie friendly form added to Daily-minutes
  DuggaSys/templates/daily-minutes.html
  DuggaSys/templates/daily-minutes.js
  Shared/css/dugga.css
Labels: gruppC2019

#6481 Fixed issue #6407: Zoom-buttons hover effect should not be able to be hovered
  Shared/css/style.css
Labels: Diagram, gruppA2019, highPriority

#6480 Fixed issue #6377: Move cursor was displayed when it should not be
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019, highPriority

#6498 MEGA FIX FOR ZOOM BAR
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6537 Added flex styling
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6528 Change login/logout button colors
  Shared/css/style.css
Labels: gruppC2019

#6539 Fixed issue #6377 and #6507: Move cursor displayed when it should not be
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6571 Fixed developer mode logic and bug, Fix for issue #6490
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6558 Fix for issue #6409: Drawing objects should be centered on the pointer
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6502 Grupp c2019 w18 6456 mobile device dugga sizes.
  Shared/css/style.css
Labels: gruppC2019

#6561 Using CSS Specificity instead !important.
  Shared/css/style.css
Labels: GruppB2019

#6544 Remove duplicate variable
  DuggaSys/courseedservice.php
Labels: GruppB2019, activeGruppB2019

#6444 Self assessment tool group ranking 5627
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
Labels: gruppC2019

#6551 Re added code that went missing to accessed.js
  DuggaSys/accessed.js
Labels: gruppC2019

#6601 FIX: Move align functionality to distribute #6578
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6541 Grupp b2019 w19#6511
  Shared/css/style.css
  Shared/navheader.php
Labels: GruppB2019, activeGruppB2019

#6542 Grupp b2019 w19#6245
  DuggaSys/resulted.js
  DuggaSys/resultedservice.php
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/sectionedservice.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019, activeGruppB2019

#6546 Fix for infinite scroll
  DuggaSys/resulted.js
Labels: GruppB2019, activeGruppB2019

#6582 Pointer cursor missing #6535 Update courseed.php
  DuggaSys/courseed.php
Labels: GruppB2019

#6584 Grupp b2019 w19#6534
  Shared/css/dugga.css
Labels: GruppB2019

#6554 Removed duplicate FAB
  DuggaSys/duggaed.js
Labels: gruppC2019

#6594 Fixed spelling error
  DuggaSys/contribution.js
Labels: gruppC2019

#6597 Faster response on button hover #6575
  Shared/css/style.css
Labels: gruppC2019

#6559 gruppB2019W19#6218
  DuggaSys/sectioned.php
  Shared/SortableTableLibrary/style.css
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#6598 Grupp a2019 w19#6457
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6599 Fixed move to front / move to back, Fix for issue #5750
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6550 Fix #6495 global button styling
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6621 Fixed lock and points resize, Fix for issue #6434
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6549 Contribution: Added sortableTable with integration of time sheet data
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  DuggaSys/contributionservice.php
Labels: gruppC2019

#6610 Changed loading of the contribution iframe to be less naive
  DuggaSys/sectionedservice.php
  DuggaSys/showDugga.php
  DuggaSys/templates/contribution.html
  DuggaSys/templates/contribution.js
Labels: gruppC2019

#6595 Searchbar, sorting has been moved.
  DuggaSys/resulted.js
  Shared/navheader.php
Labels: GruppB2019, activeGruppB2019

#6624 Fixed offsets for weak entities, relations, and multi valued attributes
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6592 Added a view with all hours in the time period to circle graph
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
  Shared/css/style.css
Labels: Contribution, gruppC2019

#6637 fixed styling for zoom bar #6379
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6617 Styling fix for kryss template
  DuggaSys/templates/kryss.html
  Shared/css/dugga.css
Labels: gruppC2019

#6627 Fix for left divdialog fields issue #5883
  DuggaSys/duggaed.js
  DuggaSys/duggaedservice.php
  DuggaSys/resulted.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: gruppC2019

#6628 Remove overflow-y on body
  Shared/css/style.css
Labels: gruppC2019

#6640 Fix for issue #6370: You shouldn't be able to draw lines to text
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6646 Grid is broken but now touchpad zoom is smoother, Fix for issue #6475
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#6636 Increase responsivness burger
  Shared/css/style.css
Labels: gruppC2019

#6641 Notifies user when session is running out
  Shared/dugga.js
  Shared/loginbox.php
Labels: GruppB2019, activeGruppB2019

#6653 fixed 6649
  DuggaSys/accessed.js
Labels: gruppC2019

#6642 Redesign feedback for handin
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  Shared/css/dugga.css
Labels: GruppB2019, activeGruppB2019

#6603 Fix #6017 ER composite behaviour
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6655 Grid working when looking at it, Fix for issue #6648
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6538 Centered request PW button
  Shared/css/style.css
Labels: gruppC2019

#6605 showDugga.php - Alternating rows fix #6564
  Shared/css/style.css
Labels: gruppC2019

#6660 Fix for #6461
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
Labels: Diagram, gruppA2019

#6616 An improved styling to the zoombar
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6663 Fixed breakpoints for hiding menuitems
  Shared/css/style.css
Labels: gruppC2019

#6532 Create the database in its final form directly
  Shared/SQL/deltachange.sql
  Shared/SQL/init_db.sql
Labels: gruppC2019

#6635 Fix for issue #6607: Remove redundant property variables
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6667 Fixed bottom margin of cookie popup msg button
  Shared/css/style.css
Labels: gruppC2019

#6665 Grupp a2019 w19#6664
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#6647 Fixed issue from previous merge
  DuggaSys/contributionservice.php
Labels: gruppC2019, highPriority

#6540 Fix for #6524
  DuggaSys/sectioned.js
Labels: gruppC2019

#6680 Accessed hover and leave functions are but pack #6657
  DuggaSys/accessed.js
  Shared/SortableTableLibrary/sortableTable.js
Labels: gruppC2019

#6681 Removed global variable and added scaling, Fix for issue #6675
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6696 Cleaning code: diagram_IOHandler.php/js #6693
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_IOHandler.php
Labels: Diagram, gruppA2019

#6697 Fix for issue #6622: Re:Stop resizing locked objects
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6689 Removed gradesystem U-3-4-5 from sectioned and in general cause it doesn't exist anymore.
  DuggaSys/duggaed.js
  DuggaSys/resulted.php
  DuggaSys/sectioned.js
Labels: GruppB2019, activeGruppB2019

#6676 Grupp b2019 w19#6154
  DuggaSys/resulted.js
Labels: GruppB2019, activeGruppB2019

#6682 Color when hovering over sectioned list changed
  Shared/SortableTableLibrary/style.css
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#6652 Added clarity to late submission in resulted
  DuggaSys/resulted.js
Labels: GruppB2019, activeGruppB2019

#6658 Open Results, Tests etc. on a new tab
  DuggaSys/sectioned.php
  Shared/dugga.js
Labels: GruppB2019, activeGruppB2019

#6700 Removed import of ssn to resulted
  DuggaSys/resulted.js
  DuggaSys/resultedservice.php
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019, activeGruppB2019

#6645 Fix for issue #6632
  DuggaSys/duggaed.php
Labels: gruppC2019

#6678 Made teacher feedback column stretch to remaining space
  Shared/css/dugga.css
Labels: gruppC2019

#6659 resetToolbar removed
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#6629 Fix for issue #6533: Relation lines missing in UML
  DuggaSys/diagram.js
  DuggaSys/diagram_forms.php
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6630 Contributionservice returns amount in groups and course
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
Labels: gruppC2019

#6701 Fix for #6349. Preventing collapsing when clicking on menu items
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#6713 Fix for #6688 Numbering of different kinds start at 0
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6717 Grupp a2019 w19#6707
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6704 Fix for issue #6239: Ability to lock proportions when resizing entities
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6711 Moved toolbar and changed text
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6674 Should be fixed, Issue #6613
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6673 Removed unnecessary cursor changes, Fix for issue #6432
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6661 Positioning of A4 holes #6414
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, gruppA2019

#6731 Fix for#6271: display multiple A4 sheets
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6705 GruppB2019W19#6650
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  Shared/SortableTableLibrary/sortableTable.js
  Shared/navheader.php
Labels: GruppB2019

#6772 Removed console.trace
  DuggaSys/resulted.js
Labels: GruppB2019

#6762 Update issue 6216 to new master
  DuggaSys/accessed.js
  DuggaSys/accessed.php
  DuggaSys/fileed.php
  Shared/css/style.css
Labels: gruppC2019

#6706 Pull request for #6579
  DuggaSys/templates/daily-minutes.html
  Shared/css/dugga.css
  Shared/css/style.css
Labels: gruppC2019

#6774 Toolbar styling changes
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6771 Mail only visible rows/users W20 #6722
  Shared/SortableTableLibrary/sortableTable.js
Labels: GruppB2019

#6773 Keyboard shortcuts for deleting item
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: GruppB2019

#6778 fixed .zip and .rar to not show additional popup dialog for download.
  Shared/dugga.js
Labels: gruppC2019

#6768 Fix for #6747: mode switching dialog
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6761 Undo and redo working again
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6656 AccessEd: Added keyboard shortcuts to edit boxes
  DuggaSys/accessed.js
Labels: gruppC2019

#6799 Grupp b2019 w20#5620
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/sectionedservice.php
Labels: GruppB2019

#6800 Removed the last slash
  DuggaSys/resulted.js
Labels: GruppB2019

#6776 Aligned items in navbar
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#6801 Upload file filtering added
  DuggaSys/templates/generic_dugga_file_receive.js
Labels: gruppC2019

#6764 Solution for 6321
  Shared/css/style.css
Labels: GruppB2019, activeGruppB2019

#6797 added CSS class to fix the issue #6795
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6802 Fix for issue #6751, position of coordinate-box
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6806 Zoombar fixed #6748
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6805 Remove migration.php
  DuggaSys/migration.php
Labels: Database, gruppC2019

#6815 Fix for #6792 Wrong comments
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6775 Removed test console log from file
  DuggaSys/accessed.js
Labels: gruppC2019

#6718 AccessEd: Edit name box needs to be redesigned
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
  Shared/icons/Cancel_Black.svg
  Shared/icons/Cancel_Red.svg
  Shared/icons/Ok_Black.svg
  Shared/icons/Ok_Green.svg
  Shared/icons/Undo_Button.svg
Labels: gruppC2019

#6822 Fix error message when hovering bar graph in contribution
  DuggaSys/contribution.php
Labels: gruppC2019

#6827 Fixed selection issue to be able to deselect by pressing the cog again.
  DuggaSys/duggaed.js
Labels: gruppC2019

#6810 Fix for issue #6465: Cursor change to indicate objects are movable in 'MoveAround' mode
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6843 Fix for issue #6545: Undoing and redoing Draw Free tool doesn't work
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6804 Hamburger menu fix
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: GruppB2019

#6816 Grupp b2019 w20#6520
  Shared/css/style.css
  Shared/navheader.php
Labels: GruppB2019

#6814 Grupp b2019 w20##6742
  DuggaSys/resulted.php
  Shared/css/style.css
Labels: GruppB2019

#6844 Fix for #6738 Resetting key press when focus is lost
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6833 #6720: Styling on toolbox hover label
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6813 Fix for #6419 Zooming relative to mouse coordinates
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6847 Title attribute fix
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: GruppB2019

#6791 issue #6753 - fix for not being able to change coursevers in dropdown box
  DuggaSys/sectioned.js
  Shared/dugga.js
Labels: GruppB2019

#6825 Added sorting to contribution views Gruppc2019w20_6312
  DuggaSys/contribution.js
  Shared/css/style.css
Labels: gruppC2019

#6834 Made some templates more mobile friendly
  DuggaSys/templates/clipping_masking_dugga.html
  DuggaSys/templates/curve-dugga.html
  DuggaSys/templates/html_css_dugga.html
  DuggaSys/templates/transforms-dugga.html
  DuggaSys/templates/transforms-dugga.js
  Shared/css/dugga.css
Labels: gruppC2019

#6835 Fix Progressbar off grid #6741
  DuggaSys/sectioned.php
Labels: GruppB2019

#6785 Duggaed: Added submission object to submission types
  DuggaSys/duggaed.js
Labels: gruppC2019

#6845 Remove sorting for icons
  DuggaSys/duggaed.js
Labels: gruppC2019

#6852 Accessed: Added Borders to table data issue: #6818
  Shared/css/style.css
Labels: gruppC2019

#6850 Adds toggle all checkboxes on accessed issue: #6769
  DuggaSys/accessed.js
  Shared/css/style.css
Labels: gruppC2019

#6870 Remove login session refresh success alert message
  Shared/dugga.js
Labels: gruppC2019

#6872 Added styling for daily minutes. #6743
  Shared/css/style.css
Labels: gruppC2019

#6884 Pull request for #6703
  DuggaSys/templates/daily-minutes.html
Labels: gruppC2019

#6894 Pull request for #6124
  DuggaSys/codeviewer.js
Labels: gruppC2019

#6865 Fix for issue #6829: Consistency suggestion with zoom buttons
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6871 Fix for #6868
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6860 Fix for #6820 Remove shadows on free draw objects
  DuggaSys/diagram_objects.js
Labels: Diagram, gruppA2019

#6880 FIx: Wrong arrow changes in sectioned.php when expanding headings #6784
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: GruppB2019

#6848 Fixed issue #6684: Unnecessary console.log in groupbranch
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6897 nudging position burger
  Shared/css/style.css
Labels: gruppC2019

#6862 Fix for issue #6826
  DuggaSys/diagram.js
Labels: Diagram, gruppA2019

#6915 Same styling in chrome and firefox
  Shared/css/style.css
Labels: Diagram, gruppA2019

#6855 AccessED: Fixed bug where old version icon didn't show.
  DuggaSys/accessed.js
Labels: gruppC2019

#6902 Added .rar files to allowed file extensions
  DuggaSys/filereceive_dugga.php
Labels: gruppC2019
