Repository HGustavs/LenaSYS, pull requests merged in 2020-05, with the labels that each got.

#8747 Fixed permission text for Windows/Linux/OSX #8000
  install/install.php
Labels: G42020

#8752 Fixed permission text for Windows/Linux/OSX #8000
  install/install.php
Labels: G42020, o18marka

#8746 Changed 777 to 060. Fixes #7900
  install/install.php
Labels: G42020, a18antsv

#8754 Fixes #8512 - Cardinality for UML and ER not working properly
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_objects.js
Labels: G42020, a18frior

#8713 Implemented freedraw for mobile, issue#8674
  DuggaSys/diagram.js
Labels: G42020, a18kaswi

#8755 Fix for issue #8741
  DuggaSys/diagram.js
Labels: G42020, a18antsv, a18jonpe

#8744 Demo-course added. Fixes #8743 #6849 #2974 #6612
  DuggaSys/templates/diagram_dugga.html
  DuggaSys/templates/diagram_dugga.js
  DuggaSys/templates/templates - genväg.lnk
  install/SQL/demoCourseData.sql
  install/install.php
Labels: G42020, b18simla

#8715 Fixes #8508 - Duplicate objects in selected_objects array
  DuggaSys/diagram.js
Labels: G42020, b18mikfr

#8766 Toolbar in fullscreen - solves issue #8435
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: g18marma

#8739 Updated function "closeEditExample" within codeviewer.js - G1-2020-W19-ISSUE#8738
  DuggaSys/codeviewer.js
Labels: CodeViewer, Group-1-2020

#8782 Fixed Analytics osPercentage()
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#8798 iCAL Calendar for mobile and desktop G1 2020 w19 #7892
  DuggaSys/sectioned.php
  Shared/calendar.php
Labels: Group-1-2020

#8780 Maximize function on box 4 now works properly - Template 6
  DuggaSys/codeviewer.js
Labels: CodeViewer, Group-1-2020

#8762 Can now create text in mobile view, issue #8672
  DuggaSys/diagram.js
Labels: G42020, a18petha

#8666 Fixes issue 8600, Fixed broken cardinality
  DuggaSys/diagram.js
Labels: G42020, a18frior

#8796 Solves issue #8765 - Dummy point created when line is drawn from path-object
  DuggaSys/diagram.js
Labels: a18kaswi

#8774 fix issue#8488 localStorage for virtual paper display and virtual paper size
  DuggaSys/diagram.js
Labels: a17robhe

#8813 Fixes #8681- Separation should take the possibility of removing a separator into account
  DuggaSys/diagram.js
Labels: a18andtu, b18simla

#8763 fix issue#8629 Popup only appears in Draw Free mode
  DuggaSys/diagram.js
Labels: b18mikfr

#8828 G1-2020-W19-ISSUE#8593
  DuggaSys/codeviewer.js
Labels: CodeViewer

#8827 fix issue#8787 crosshair in developer mode moved to front
  DuggaSys/diagram.js
Labels: o18marka

#8818 Memory usage in analytics - G1 2020 w19 #8803
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#8825 G1 2020 w19 #8824
  DuggaSys/analytic.php
Labels: Analytic, Group-1-2020

#8843 Solves #8553 - Solution for connecting loose ER-lines to objects
  DuggaSys/diagram.js
Labels: a18frior

#8857 Fixes #8852 - Appearance menu code: Separate long functions into separate functions
  DuggaSys/diagram.js
Labels: a18petha

#8867 Partial solution for #3698
  install/install.php
  install/install_defer.js
  install/install_entry.js
Labels: G42020, a18andtu

#8869 Added RAM Usage on Analytics - G1 2020 w19 issue#8801
  DuggaSys/analytic.js
  DuggaSys/analytic.php
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#8853 Now marks the last made point in freedraw for mobile ,issue #8758
  DuggaSys/diagram.js
Labels: a18jonpe

#8858 User feedback when incorrect line is attempted
  DuggaSys/diagram.js
Labels: b18mikfr

#8880 Added fixed colors to piecharts - G1 2020 w19 issue#8868
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#8878 Fixes #8510 - Object names in line direction select change according to name input
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: a17robhe

#8883 Added cookie to keep track of the current file being viewed
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#8733 Issue #8429 fixed
  DuggaSys/sectioned.js
  Shared/icons/markdownPen.svg
Labels: G42020, g18marma

#8911 Fixed canvas not clearing #8886
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#8914 Added cookie to keep track of the last selected item in service usage #8907
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#8934 Further work on error message handling to user
  DuggaSys/diagram.js
Labels: b18simla

#8927 Added correct updating of longestStr to UML resizing ISSUE#8594
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, g18marma

#8969 Currently online users - G1 2020 w20 issue#8692
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
  Shared/basic.php
Labels: Analytic, Group-1-2020

#8974 Button to visit analytics - issue#8877
  Shared/navheader.php
Labels: Analytic, Group-1-2020

#8976 Removal of unnecessary logging - G1 2020 w20 issue#8940
  Shared/basic.php
  install/install.php
Labels: Group-1-2020, Logging

#8929 Resizing function in submitAppearanceFrom removed ISSUE#8556
  DuggaSys/diagram.js
Labels: G42020, a18kaswi

#8966 Fixes issue 8622, generating examples not working properly
  DuggaSys/diagram.js
  DuggaSys/exampleER.txt
  DuggaSys/exampleUML.txt
Labels: a18petha

#8963 G4 2020 w20 issue#8884
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: a18frior

#8964 G2 2020 w20 #8534
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  Shared/css/style.css
Labels: Group-2-2020, Result Editor

#8986 Fixed buttons in analytics - G1 2020 w20 issue#8915
  DuggaSys/analytic.php
  Shared/css/analytics.css
  Shared/css/style.css
Labels: Analytic, Group-1-2020

#8985 Preparations for #5943 - Reworks the entire layout in diagram.php
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  Shared/css/style.css
Labels: g18marma

#8998 Progress on #3698
  install/install.php
Labels: a18andtu

#8995 G4 2020 w20 issue#8991
  DuggaSys/sectioned.js
Labels: a17robhe

#9003 Icons to replace buttons in analytics - G1 2020 w20 issue#8977
  DuggaSys/analytic.php
  Shared/css/analytics.css
  Shared/navheader.php
Labels: Analytic, Group-1-2020, Navheader

#9017 fix issue#8971 Primary and Partial key lines consistent with text size and zoom
  DuggaSys/diagram_objects.js
Labels: b18phibe

#9011 Max login fails changed from 10 to 3 #9006
  DuggaSys/analyticService.php
  Shared/loginlogout.php
Labels: Analytic, Group-1-2020

#9010 Renamed post-install modal and fixed #8999
  install/install.php
Labels: G42020, b18simla

#9031 Added alert based error reporting
  Shared/basic.php
Labels: Group-1-2020

#9041 Fixed PHP errors in analytics #9035
  DuggaSys/analytic.php
  Shared/basic.php
Labels: Analytic, Group-1-2020

#9037 Page names in analytics #9001
  DuggaSys/analytic.js
  DuggaSys/analytic.php
  Shared/css/analytics.css
Labels: Analytic, Group-1-2020

#8982 Fixes to Diagram layer drop-down menu | G4 2020 w20 issue#8887
  DuggaSys/diagram.js
Labels: b18mikfr

#9042 G4 2020 w20 issue#8475
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: o18marka

#9049 Good start for #5943 - Rulers can be generated
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: g18marma

#9067 Recursive lines can now be hovered
  DuggaSys/diagram_objects.js
Labels: a18antsv

#9064 Fix for issue #8983
  DuggaSys/diagram.js
Labels: a18antsv

#9004 #8683 Fixed
  DuggaSys/diagram.php
Labels: a18kaswi

#9073 G4 2020 w20 issue#3698
  install/install.php
Labels: G42020, o18marka

#9078 Solves issue#9072, error in console when generating example diagrams
  DuggaSys/diagram.js
Labels: a18antsv

#9082 Fixes Diskusage Percentage #9018
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9046 Separate tab for online users in analytics #9002
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
  Shared/navheader.php
Labels: Analytic, Group-1-2020

#9065 Fixes #9060 - Rulers adapt to camera
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: b18simla

#8956 fix issue#8903 fix flash and mutation in FreeDraw
  DuggaSys/diagram.js
Labels: a18andtu

#9097 Cookie to remember last page in analytics #9000
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#9093 G4 W20 Fixes #7419
  install/install.php
Labels: G42020, b18mikfr

#9096 Removed the redundant string-part - FIXES #8972
  install/install_entry.js
Labels: G42020, a18petha

#9080 Fix for #9066
  DuggaSys/diagram.js
Labels: G42020, a18frior

#9102 Cookie to remember last selected user #9098
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#9121 Now possible to add and remove points to/from freedraw objects, issue#6891
  DuggaSys/diagram.js
Labels: G42020, b18simla

#9117 Added delete functionality for diagram layer system | G4 2020 w20 issue#8885
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, a18kaswi

#8961 Scrollbars now hide and show when needed for all templates
  DuggaSys/codeviewer.js
  courses/global/HTML_Ex1.txt
Labels: CodeViewer, Group-1-2020

#9126 MaximizeBoxes updated after code standard
  DuggaSys/codeviewer.js
Labels: CodeViewer, Group-1-2020

#9109 Initialize permissionModal to none FIXED #8987
  install/install.php
Labels: G42020, a17robhe

#9123 fix issue#9103 localStorage for Hide comment
  DuggaSys/diagram.js
Labels: G42020, a18andtu

#9138 Final rework done, fixes issue#3698
  install/install.php
  install/install_defer.js
  install/install_entry.js
Labels: G42020

#9140 LenaSys Installation Size #9112
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9137 Fixes #9061- Rulers adapt to zoom
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: a18frior, g18marma

#9143 User Submission size #9110
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9154 HideShowScrollbars
  DuggaSys/codeviewer.js
Labels: CodeViewer, Group-1-2020

#9160 Total users in general stats #9108
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9171 Updated: solves issue#7446
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: a18antsv

#9163 fix issue#9125 Drag required for flash to appear
  DuggaSys/diagram.js
Labels: a18antsv

#9166 Fixes #9062 - Show mouse positions on rulers
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: a18petha

#9130 Fix bug related to unidentified layer in diagram menu |G4 2020 w20 issue#8890
  DuggaSys/diagram.js
Labels: G42020, o18marka

#9186 Solution for clearing attributes connectorTop
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, g18marma

#9193 Full user list #9116
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9164 Added checkbox for demo-course FIXES #8311
  install/CSS/install_style.css
  install/install.php
Labels: G42020, a18petha

#9199 Changed a value FIXED #8764
  install/install.php
Labels: G42020, a18andtu

#9178 G4 2020 w20 issue#7360
  Shared/resetpw.php
Labels: G42020, SQL, b18mikfr

#9205 fix issue#9196 Text object flash / Savestate issue solved
  DuggaSys/diagram.js
Labels: a18kaswi

#9209 Added an option to run init as transaction. FIXES issue#6922
  install/install.php
Labels: G42020, b18simla

#9180 Fix Generate example writes to active layer - Issue 9170
  DuggaSys/diagram.js
  DuggaSys/diagram_IOHandler.js
Labels: Diagram, G42020

#9167 Solve issue 9159 | Diagram Layers
  DuggaSys/diagram.js
Labels: Diagram, G42020, a18kaswi

#9204 Course specific disk usage #9111
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
  Shared/navheader.php
Labels: Analytic, Group-1-2020

#9225 SQLite database versioning #9220
  Shared/basic.php
Labels: Group-1-2020, Logging

#9157 Fix colors for diagram layers | G4 2020 W20 issue #9144
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: G42020, a17robhe

#9223 Removed connectLogDB #9189
  install/install.php
Labels: G42020, o18marka

#9221 Add current layer to developer toolbar - G4 2020 w20 issue#9201
  DuggaSys/diagram.js
Labels: Diagram, G42020, a18kaswi

#9226 G1 2020 w20 issue#8906-2
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Group-1-2020

#9175 Solves issue#8218, read-only functionality
  Shared/dugga.js
Labels: G42020, b18simla

#9270 Crosses now only shows if developer mode is active after refresh (solves 9207)
  DuggaSys/diagram.js
Labels: a18antsv

#9289 Top OS / Top Browser #9177
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9291 Top Page #9105
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9263 Fixes errors output by codeviwer #9258
  DuggaSys/codeviewer.php
Labels: CodeViewer, Group-1-2020

#9298 Fix to not being able to undo properly
  DuggaSys/diagram.js
Labels: a18frior

#9317 Username and userid
  DuggaSys/filereceive.php
Labels: Group-1-2020

#9314 Fixes #9233 - unwanted line coordinates show on ruler when ER entity selected
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
  Shared/css/style.css
Labels: a18petha

#9302 Reset shortcuts implemented ISSUE#9150
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, a18jonpe

#9328 Fixed last seen to work in Safari and Firefox #9206
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#9329 Extended algorithm for focusTheRightBox() FIXES issue#9248
  install/install_defer.js
Labels: G42020, g18marma

#9339 Added if-checks for functions to avoid errors FIXES #9325
  install/install.php
  install/install_defer.js
Labels: G42020, a17robhe

#9349 G1 2020 w21 issue#9120
  Shared/css/analytics.css
  Shared/navheader.php
Labels: Analytic, Group-1-2020

#9348 Added $completeQuery to broader scope FIXES issue#9324
  install/install.php
Labels: G42020, a18petha

#9322 Defined global error where needed FIXES issue#9247
  install/install.php
Labels: G42020, b18phibe

#9358 Finetuned margins and added a short transition (Issue already merged once)
  Shared/css/analytics.css
Labels: Analytic, Group-1-2020

#9373 It is now possible to move the middle divider of UML-classes
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: b18simla

#9365 Fastest and Slowest service #9341
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9364 Fix so that appearanceform is opened for freedraw objects, issue #9359
  DuggaSys/diagram.js
Labels: a18kaswi

#9344 Drop-down menu in diagram fixed (issue#9267)
  Shared/css/style.css
Labels: G42020, a18antsv

#9378 Fixes #9231 - Property names in local storage is compressed
  DuggaSys/diagram.js
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_objects.js
Labels: b18simla

#9377 G4 2020 w21 issue#9355 Empty points are no longer drawn in origo.
  DuggaSys/diagram.js
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagram_objects.js
Labels: G42020, o18marka

#9395 Top viewed Dugga and Example
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Group-1-2020

#9370 G4 2020 w21 issue#9250 3
  install/install.php
  install/install_defer.js
Labels: G42020, a17robhe

#9354 Improve Layer Code and add comments - Solves Issue 8891
  DuggaSys/diagram.js
Labels: Diagram, G42020, a18andtu

#9340 Solves issue 9208, hidden comments no longer movable or clickable
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: a18antsv

#9399 Service crashes shown
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Group-1-2020

#9405 Fixed a logic issue in barcharts
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#9345 G4 2020 w21 issue#9149 keybinds now stored in localstorage
  DuggaSys/diagram.js
  DuggaSys/diagram_IOHandler.js
Labels: G42020, a18jonpe

#9409 Updated tooltip to OS Percentage #9406
  Shared/navheader.php
Labels: Analytic, Group-1-2020, Navheader

#9411 Template 8 no longer gives a fixed top to box 3 when resizing the width
  DuggaSys/codeviewer.js
Labels: CodeViewer, Group-1-2020

#9426 Filesize added to dropdown #9342
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9408 Fixes so that path objects can be deleted correctly, issue #9360
  DuggaSys/diagram.js
Labels: a18frior

#9414 fix issue#9376 UML text size problem solved
  DuggaSys/diagram_objects.js
Labels: a18petha

#9412 Fix locked functionality - Solves Issue 9379
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: Diagram, G42020, b18mikfr

#9297 Updated from pull request 9235 (G1-2020-W20-ISSUE#8802)
  DuggaSys/analytic.js
  DuggaSys/analyticService.php
Labels: Analytic, Group-1-2020

#9430 G4 2020 w21 issue#9375 fixed shift resize
  DuggaSys/diagram.js
Labels: g18marma

#9256 SaveStated called only when deleting objects (solves 9187)
  DuggaSys/diagram.js
Labels: G42020, o18marka

#9445 Piechart scale
  Shared/css/analytics.css
Labels: Group-1-2020

#9374 Fix so user can't delete all layers anymore - Solves Issue 9312
  DuggaSys/diagram.js
Labels: Diagram, G42020, o18marka

#9455 Updated readme to reflect new installer FIXES issue#8770
  README.md
  Shared/Documentation/Install/Install_3.png
  Shared/Documentation/Install/Install_4.png
  Shared/Documentation/Install/Install_warning.png
Labels: G42020, a17robhe

#9470 Number of times event has been preformed #9407
  DuggaSys/analytic.js
Labels: Analytic, Group-1-2020

#9475 Fix cross dots in developer mode -Solves Issue 9380
  DuggaSys/diagram.js
Labels: Diagram, G42020

#9486 Fixed redirect for non superusers in analytics #9484
  DuggaSys/analytic.php
Labels: Analytic, Group-1-2020

#9487 Fixed logout button in analytics #9485
  DuggaSys/analytic.php
Labels: Analytic, Group-1-2020

#9490 solves issue#9271
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: a18kaswi

#9530 Codeviewer should now take the ordering of code examples into consideration
  DuggaSys/codeviewer.js
  DuggaSys/sectioned.js
Labels: CodeViewer, Group-1-2020
