Repository HGustavs/LenaSYS, pull requests merged in 2020-04, with the labels that each got.

#7798 Issue #7747 - resulted.php modified
  DuggaSys/resulted.php
Labels: Group-2-2020, a17pioja, a18ismca, a18viksa

#7814 G4 2020 w14 issue#7812
  DuggaSys/courseed.js
  DuggaSys/courseed.php
  DuggaSys/courseedservice.php
Labels: Group-4-2020

#7809 Gradebutton moved. Moved partially styling from dugga.css to resulted…
  Shared/css/dugga.css
Labels: Group-2-2020

#7848 Using tab key to navigate the menu bar(in diagram)
  DuggaSys/diagram.php
  Shared/css/style.css
  Shared/navheader.php
Labels: b18phibe

#7854 Added PDO transaction to bundle the queries when using option 'CPYVRS'
  DuggaSys/courseedservice.php
Labels: g18marma

#7870 G4-2020-W15-ISSUE#7868
  Shared/database.php
Labels: G42020, g18marma

#7874 #7250 -updated
  DuggaSys/courseed.js
  DuggaSys/courseed.php
Labels: G42020, a18andtu

#7857 Fixed so that swedish characters are loaded correctly, issue #7839
  DuggaSys/courseed.js
Labels: G42020, o18marka

#7882 G4 2020 w15 issue#7646
  DuggaSys/diagram.js
Labels: G42020, a18conch

#7901 State is now saved when distribute function is used
  DuggaSys/diagram.js
Labels: G42020, a18andtu

#7889 Solved issue#7664, UML-diagram line problem
  DuggaSys/diagram.js
Labels: G42020, a18antsv

#7877 G4 2020 w14 issue#7769
  DuggaSys/accessed.js
  Shared/css/style.css
  Shared/css/template4.css
  Shared/dugga.js
  Shared/icons/desc_black.svg
Labels: G42020, a18frior

#7906 G4 2020 w15 issue#7623 resolved
  DuggaSys/courseed.js
  DuggaSys/courseed.php
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, b18phibe

#7911 G4 2020 w15 issue#7635
  DuggaSys/diagram_objects.js
Labels: a18jonpe

#7909 Removed onclick function from counter elements in sortableTable
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group-2-2020

#7899 An option has been added to download the diagram in A4 size
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
Labels: G42020, a18antsv, a18frior

#7904 G4 2020 w15 issue#7647
  DuggaSys/diagram.js
Labels: G42020, b18mikfr

#7929 G4-2020-W15-ISSUE#7635 Solved
  DuggaSys/diagram_objects.js
Labels: o18marka

#7922 G4 2020 w15 issue#7888 2
  DuggaSys/accessed.js
  DuggaSys/courseed.js
  DuggaSys/courseed.php
  DuggaSys/courseedservice.php
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
  Shared/css/template4.css
  Shared/database.php
  Shared/dugga.js
  Shared/icons/desc_black.svg
  Shared/navheader.php
Labels: b18simla

#7943 Alignment with free draw objects fix
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, a18antsv

#7927 Added the class cursorPointer to the exit button. #7923
  Shared/loginbox.php
Labels: Group-2-2020

#7988 Fixed deleting files
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
Labels: Grupp 3 - 2020

#7954 fixed issue #7680
  DuggaSys/diagram.js
Labels: G42020, a18frior

#7957 Fixes issue#7728, spacing in UML appearance menu
  DuggaSys/diagram_forms.php
Labels: G42020, o18marka

#7976 #7249-fixed
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: G42020, b18simla

#7981 SaveState() is now only triggered when objects are actually moved when using align/distribute
  DuggaSys/diagram.js
Labels: G42020, a18petha

#7964 G4 2020 w15 issue#7908
  DuggaSys/diagram.js
Labels: G42020, b18phibe

#7915 G4 2020 w15 issue#7653
  DuggaSys/diagram_objects.js
Labels: G42020, a18conch

#7932 Fixes issue 7847, closing appearance menu with escape then deleting objects with delete
  DuggaSys/diagram.js
Labels: G42020, a18conch

#7942 G4 2020 w15 issue#5994
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, a18andtu

#7980 Fixed lines between relations and entities issue#6209
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, g18marma

#7979 Implements functionality of issue #5638
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.php
  DuggaSys/diagram_forms.php
  DuggaSys/diagram_objects.js
  Shared/css/style.css
Labels: G42020, a18jonpe

#7946 #7888-fixed
  DuggaSys/courseed.js
  DuggaSys/courseed.php
Labels: G42020, b18mikfr

#8057 Fixed read only checkbox, issue #7812
  DuggaSys/courseed.js
  DuggaSys/courseed.php
  DuggaSys/courseedservice.php
Labels: G42020, a18andtu

#8058 Fixes issue 7847, closing apperance menu with escape locks delete and backspace
  DuggaSys/diagram.js
Labels: G42020, a18antsv

#8049 Fixed navigation through menu with tab
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: G42020, a18jonpe

#8054 Reimplemented old issue that disappeared in weekly merge #7784
  DuggaSys/sectioned.js
  Shared/navheader.php
Labels: G42020, b18mikfr

#8064 G4 2020 w16 issue#8012
  DuggaSys/diagram.js
Labels: G42020, a18andtu

#8053 Fix for message of the day covered once after edit, issue #7789
  Shared/dugga.js
Labels: G42020, a18conch

#8068 Fix for styling in import-dialog issue#7618
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: G42020, a18jonpe

#8059 issue 6005
  DuggaSys/diagram_objects.js
Labels: G42020, b18simla

#8060 Changed it so chrome also zooms in steps of 10% #7614
  DuggaSys/diagram.js
Labels: G42020, g18marma

#8063 Reimplemented solution for new HTML structure
  Shared/css/style.css
Labels: G42020, a18antsv

#8055 Camera position(including zoomValue) is saved and persists when refreshing page
  DuggaSys/diagram.js
Labels: G42020, g18marma

#8074 Implemented refreshing of session cookies when user is active - G1-2020-W16-#7507
  DuggaSys/codeviewer.php
  DuggaSys/courseed.php
  DuggaSys/sectioned.php
Labels: Group-1-2020

#8065 A4 dashed in all zoom modes
  DuggaSys/diagram.js
Labels: G42020, a18antsv

#8048 Added PDO transaction to bundle the queries when using option 'CPYVRS'
  DuggaSys/courseedservice.php
Labels: G42020, a18andtu

#8079 Changed justify-content to center. #7400
  DuggaSys/templates/dugga4.html
Labels: Group-2-2020

#8078 #7888 fixed
  DuggaSys/courseed.js
  DuggaSys/courseed.php
Labels: Group-4-2020

#8051 Change cursor to pointer on alert. #7923
  Shared/css/style.css
  Shared/loginbox.php
Labels: Group-2-2020

#7990 G1 Pull request to Issue#7829
  DuggaSys/codeviewer.php
  Shared/css/codeviewer.css
  Shared/css/style.css
  Shared/css/template1.css
  Shared/css/template2.css
  Shared/css/template3.css
  Shared/css/template4.css
  Shared/css/template5.css
  Shared/css/template6.css
  Shared/css/template7.css
  Shared/css/template8.css
  Shared/css/template9.css
Labels: Group-1-2020

#8113 Fixed issue for branch: G1-2020-W17-ISSUE#4048
  Shared/dugga.js
Labels: Group-1-2020

#8123 G1-2020-W16-ISSUE#5591
  Shared/css/style.css
Labels: Group-1-2020

#8133 G1-2020-W17-ISSUE#8102
  Shared/css/codeviewer.css
Labels: Group-1-2020

#8137 G1-2020-W17-ISSUE#7898
  Shared/css/codeviewer.css
Labels: Group-1-2020

#8125 fix ISSUE#7147 New border when buttons selected
  Shared/css/style.css
Labels: G42020, a18conch

#8117 Fixes issue #7531
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, g18marma

#8120 Fixed positions of Zoom and Coordinate bars - issue#7421
  DuggaSys/diagram.php
Labels: G42020, a18andtu

#8129 G4 2020 w17 issue#6995
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, a18petha

#8135 Fixes issue #7868
  Shared/database.php
Labels: G42020, g18marma

#8119 Issue#7391 Solved
  DuggaSys/diagram_objects.js
Labels: G42020, a18jonpe

#8136 Added CSS-documentation to popupDocumentation
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8152 G4 2020 w17 issue#8127
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, a18frior

#8145 G1-2020-W17-ISSUE#8144
  Shared/css/codeviewer.css
Labels: Group-1-2020

#8155 Reimplemented functionality
  DuggaSys/diagram_objects.js
Labels: Diagram, G42020, b18phibe

#8132 added minimum distance before activating drag and click
  DuggaSys/diagram.js
Labels: G42020, b18simla

#8143 On screen message handling
  DuggaSys/diagram.php
  DuggaSys/diagram_objects.js
  Shared/css/style.css
Labels: G42020, a18andtu

#8168 fix ISSUE#7559 position of button labels
  Shared/css/style.css
Labels: G42020, a18antsv

#8179 Fixes #8138
  Shared/navheader.php
Labels: G42020, a18petha

#8176 G1 2020 w17 issue#7760
  DuggaSys/codeviewer.php
Labels: CodeViewer, Group-1-2020

#8151 G4 2020 W17 issue#7765
  DuggaSys/downloadzip.php
  DuggaSys/filereceive.php
  Shared/navheader.php
Labels: G42020, b18mikfr

#8177 Solves Issue 6878 - snap to grid with arrow keys
  DuggaSys/diagram.js
Labels: G42020, o18marka

#8199 Fixes #8196 - improving code of initialization functions
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  Shared/css/style.css
Labels: a18frior

#8154 Added mouseover text to warning triangle
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2020

#8188 Better explanations in options for UML line
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, a18antsv

#8201 Fixes #8200 - Move button active when not in move mode
  DuggaSys/diagram.js
Labels: b18phibe

#8195 Lines to ER-relation now connect - Issue#6864
  DuggaSys/diagram_objects.js
Labels: a18petha

#8184 Fixes issue #8080
  DuggaSys/diagram.js
Labels: G42020, b18simla

#8190 G1 2020 w17 issue#8128
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8229 G1-2020-W17-ISSUE#8223
  Shared/css/codeviewer.css
  Shared/css/style.css
  Shared/css/template3.css
Labels: Group-1-2020

#8233 Added event-documentation to PopupDocumentation
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8197 Resulted: Fixed issue by limiting the size of the th-element.
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group-2-2020

#8227 The text is no longer cut off.
  Shared/css/style.css
Labels: Group-2-2020, ResultED

#8242 Maximize button now works with every template
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8192 Fixes issue #8011
  DuggaSys/courseed.js
  DuggaSys/courseed.php
  Shared/css/style.css
Labels: G42020, o18marka

#8228 G4 2020 w17 issue#7003
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: G42020, g18marma

#8255 Fixes #8254 - Set loaded value on zoom range on initialization
  DuggaSys/diagram.js
Labels: G42020, a18petha

#8243 No longer opens two dropdowns #8099
  DuggaSys/diagram.js
Labels: G42020, o18marka

#8276 fix issue#6429 prevent a mutation of a free-drawn object
  DuggaSys/diagram.js
Labels: G42020, b18simla

#8241 Added explanatory comments to IOHandler.js
  DuggaSys/diagram_IOHandler.js
Labels: G42020, a18antsv

#8277 Fixes #8091
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/style.css
Labels: G42020, g18marma

#8260 G4 2020 w17 issue#6487
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_objects.js
Labels: G42020, a18antsv

#8280 No longer shows developer coordinates in mobile view, issue #7423
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: G42020, a18petha

#8274 Fixed table styling issues
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
Labels: Group-2-2020

#8292 Properly delete UML-lines
  DuggaSys/diagram.js
Labels: G42020, a18jonpe

#8294 Fixes #8169 - Move coordinates element on small screens
  Shared/css/style.css
Labels: G42020, g18marma

#8270 Issue #8086
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, a18jonpe

#8301 Solution for branch G1-2020-W17-ISSUE#8282
  Shared/css/codeviewer.css
Labels: Group-1-2020

#8293 Solution for branch G1-2020-W17-ISSUE#8279
  Shared/css/template8.css
Labels: Group-1-2020

#8288 G1 2020 w17 issue#8202
  DuggaSys/codeviewer.js
  Shared/css/codeviewer.css
Labels: Group-1-2020

#8246 G4-2020-W17-ISSUE#7583
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, a18antsv

#8310 Fix for problem with draw line in diagram
  DuggaSys/diagram.js
Labels: a18andtu

#8312 Fixes #8067 - Global appearance now affects when no symbols drawn
  DuggaSys/diagram.js
Labels: b18simla

#8325 fix issue#8303 consistency on remaining buttons.
  Shared/css/style.css
Labels: G42020, a18petha

#8315 Fixes #8314 - Proper check to prevent action on wrong objects
  DuggaSys/diagram.js
Labels: G42020, a18petha

#8337 Fixes issue#8248, ability to use enter instead of click in dropdown menu
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
Labels: a18antsv

#8224 Added basic service logging for diagramservice and highscoreservice.php - G1-2020-W17-ISSUE#8213
  DuggaSys/contributionservice.php
  DuggaSys/diagramservice.php
  DuggaSys/highscoreservice.php
Labels: Group-1-2020

#8238 Added logging for dugga page loads - G1-2020-W17-ISSUE#8230
  DuggaSys/showDugga.php
Labels: Group-1-2020

#8275 Fixed solution for G1 2020 w17 issue#8210
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8285 Double scrollbars solved
  Shared/css/style.css
  Shared/css/template6.css
  Shared/css/template7.css
  Shared/css/template9.css
Labels: CodeViewer, Group-1-2020

#8295 Logging for adding a new item in Section
  DuggaSys/sectionedservice.php
  Shared/basic.php
Labels: Group-1-2020

#8308 Added logging when adding new files in fileed - G1-2020-W17-#8264
  DuggaSys/filereceive.php
  Shared/basic.php
Labels: Group-1-2020

#8336 Fixes #8313 - Change derived linecap to prevent covering dashes
  DuggaSys/diagram_objects.js
Labels: G42020, b18phibe

#8331 Touch support for moving around on the canvas, issue #8320
  DuggaSys/diagram.js
Labels: G42020, a18frior, g18marma

#8306 Updated editImpWords to better fit with the code standard.
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8342 G4 2020 w17 issue#6315
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  Shared/css/dugga.css
  Shared/css/style.css
Labels: G42020, b18phibe

#8338 midway merge
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  Shared/css/style.css
Labels: G42020, a18antsv

#8309 Updated function "returned" to better fit with the code standard.
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8332 Logging for create course and edit course - G1-2020-W17-ISSUE#8319
  DuggaSys/courseedservice.php
  Shared/basic.php
Labels: Group-1-2020

#8346 G1 2020 W17 issue#8289
  DuggaSys/codeviewer.js
  Shared/icons/MaxButton.svg
  Shared/icons/MinButton.svg
  Shared/icons/ResetButton.svg
Labels: Group-1-2020

#8349 Issue #8305 - Template 9 rezizing height not working properly - Now fixed
  DuggaSys/codeviewer.js
Labels: CodeViewer, Group-1-2020

#8371 fix issue#8257 Changed arity to length
  DuggaSys/diagram.js
Labels: G42020, a18jonpe

#8403 Fixes #8388 - Appearance menu closes on mousedown inside then mouseup outside
  DuggaSys/diagram.js
Labels: G42020, g18marma

#8385 Solution for branch G1-2020-W18-ISSUE#8360
  DuggaSys/codeviewer.js
  Shared/icons/markdownPen.svg
  Shared/icons/newMarkdown.svg
Labels: Group-1-2020

#8409 Solution for branch G1-2020-W18-ISSUE#8389
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8405 Added logging when creating or editing course version - G1-2020-W18-ISSUE#8364
  DuggaSys/courseedservice.php
  DuggaSys/sectionedservice.php
  Shared/basic.php
Labels: Group-1-2020

#8401 G4 2020 w18 issue#8236 Cardinality.isCorrectside Solved
  DuggaSys/diagram.js
Labels: G42020, o18marka

#8382 Fix so that active labels are also cleared, #8340
  DuggaSys/diagram.js
Labels: G42020, a18petha

#8395 fix issue#8265 Make it easier to see if a text are a comment
  DuggaSys/diagram_objects.js
Labels: G42020, b18mikfr

#8432 Solves issue#8066
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, a18antsv

#8428 FIxes #8427 - Auto focus in appearance menu
  DuggaSys/diagram.js
Labels: G42020, g18marma

#8414 Solution for branch G1-2020-W18-ISSUE#8372
  Shared/css/codeviewer.css
  Shared/css/template1.css
  Shared/css/template2.css
  Shared/css/template3.css
  Shared/css/template4.css
  Shared/css/template5.css
  Shared/css/template6.css
  Shared/css/template7.css
  Shared/css/template8.css
  Shared/css/template9.css
Labels: CodeViewer, Group-1-2020

#8426 G1 2020 w18 issue#8417
  DuggaSys/codeviewer.js
Labels: CodeViewer, Group-1-2020

#8440 G4 2020 w18 issue#7935
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_objects.js
Labels: G42020, b18simla

#8416 G4 2020 w18 issue#6491
  DuggaSys/diagram.js
Labels: G42020, a18andtu

#8390 Exporting as SVG now handles UMl lines
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: G42020, b18phibe

#8421 G1 2020 w18 issue#8408
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8456 Solution for branch G1-2020-W18-ISSUE#8372
  DuggaSys/codeviewer.js
  Shared/css/template9.css
Labels: Group-1-2020

#8457 G1 2020 w18 issue#8361
  DuggaSys/codeviewer.js
  Shared/css/codeviewer.css
Labels: CodeViewer, Group-1-2020

#8454 Back button in codeviewer now works
  Shared/navheader.php
Labels: Group-1-2020

#8466 G4 2020 w18 issue#7361
  DuggaSys/diagram.js
  DuggaSys/diagram_objects.js
Labels: Diagram

#8451 G3 2020#8411
  DuggaSys/downloadzip.php
  Shared/navheader.php
Labels: File Downloading, File Editor

#8380 Logging for save and upload in showDugga
  DuggaSys/filereceive_dugga.php
  DuggaSys/showDuggaservice.php
  Shared/basic.php
Labels: Group-1-2020

#8431 Logging for reset password in accessed
  DuggaSys/accessedservice.php
Labels: Group-1-2020

#8443 Added logging when downloading all contents from course vers - G1-2020-W18-ISSUE#8433
  DuggaSys/downloadzip.php
  Shared/basic.php
Labels: Group-1-2020

#8461 G1 2020 w18 issue#8453
  DuggaSys/codeviewer.js
Labels: Group-1-2020

#8486 Solves issue#8478
  DuggaSys/diagram.js
Labels: G42020, a18antsv

#8479 Solves issue#8436
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G42020, a18antsv, a18petha

#8386 Changed all current logUserEvent to log userid instead of username - G1-2020-W18-ISSUE#8337
  DuggaSys/codeviewer.php
  DuggaSys/courseedservice.php
  DuggaSys/filereceive.php
  DuggaSys/sectionedservice.php
  Shared/loginlogout.php
  Shared/resetpw.php
Labels: Group-1-2020

#8463 Updated codeviewer.js - G1-2020-W18-ISSUE#8455
  DuggaSys/codeviewer.js
Labels: Group-1-2020
