Repository HGustavs/LenaSYS, pull requests merged in 2021-04, with the labels that each got.

#9864 Removed color from bulbs
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Group-2-2021

#9884 G2-2021-W14-ISSUE#9873
  DuggaSys/sectioned.js
Labels: Group-2-2021

#9902 update showdugga.php
  DuggaSys/showDugga.php
Labels: Group-1-2021

#9907 Fix: Correct name on new elements - #9889
  DuggaSys/diagram.js
Labels: Group-3-2021

#9914 Added ruler to the diagram - Issue 9835
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group-3-2021

#9918 Update accessed.js
  DuggaSys/accessed.js
Labels: Group-2-2021

#9923 Added functionality to create lines between entities
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group-3-2021

#9925 Fixed brighter color and darker color when selecting element
  DuggaSys/diagram.js
Labels: Group-3-2021

#9928 Added delete functionality for delete key
  DuggaSys/diagram.js
Labels: Group-3-2021

#9931 update dugga.js
  Shared/dugga.js
Labels: Group-1-2021

#9935 G1 2021 w15 #9911
  DuggaSys/sh/index.php
Labels: Group-1-2021

#9934 Template literals on sectioned.js
  DuggaSys/sectioned.js
Labels: Group-2-2021

#9938 Made the elements selection box dashed
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: Group-3-2021

#9939 G1 2021 w15 #9805
  .htaccess
  DuggaSys/sh/index.php
  Shared/database.php
  log/loglena6.db
Labels: Group-1-2021

#9921 Save Assignment password and hash to db
  DuggaSys/showDuggaservice.php
  Shared/SQL/alterTables.sql
  Shared/SQL/init_db.sql
  Shared/dugga.js
Labels: Group-1-2021

#9933 G1 2021 w15 #9903
  DuggaSys/resulted.php
  DuggaSys/showDugga.php
  DuggaSys/templates/generic_dugga_file_receive.js
Labels: Group-1-2021

#9930 Update dugga.js to only show whitelight
  Shared/dugga.js
Labels: Group-2-2021

#9937 Made the validateSSN function compatible with "samordningsnummer" Issue #9765
  DuggaSys/accessed.js
Labels: Group-2-2021

#9947 Added nodes to selected entity
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#9951 G1 2021 #9916
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-1-2021

#9922 G1 2021 w15 #9865
  Shared/dugga.js
Labels: Group-1-2021

#9959 G2 2021 w15 issue#9874
  DuggaSys/sectioned.js
Labels: Group-2-2021

#9957 Update navheader.php
  Shared/navheader.php
Labels: Group-2-2021

#9940 Replaced string based sytem with template literals
  DuggaSys/accessed.js
Labels: Group-2-2021

#9966 Can now change element names #9872
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#9967 Cmd(Mac) + backspace = delete element
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#9968 Group3 2021 w15 #9945
  DuggaSys/diagram.js
Labels: Group-3-2021

#9965 Update diagram.js
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#9956 Fix - zoom with mousewheel and ctrl-keys, issue #9932
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group-3-2021

#9964 updated dugga.js and showdugga.php
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-1-2021

#9978 Final commit
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-1-2021

#9970 Update dugga.js
  Shared/dugga.js
Labels: Group-1-2021

#9942 Removing access category and group assignment from access editor
  DuggaSys/accessed.js
  DuggaSys/accessed_removedColumn.txt
Labels: Group-2-2021

#9981 Group3 2021 w15 #9963
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#9984 Bugfix when using backspace #9979
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#9987 Validation in 'create user' form issue#9753
  DuggaSys/accessed.js
  DuggaSys/accessed.php
Labels: Group-2-2021

#9982 Fixed safari browser logginbutton problem
  Shared/css/style.css
Labels: Group-2-2021

#9962 Updated export popup window
  DuggaSys/resulted.js
Labels: Group-2-2021

#9983 update dugga.js
  Shared/dugga.js
Labels: Group-1-2021

#9996 Grid function
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10000 Group3 2021 w15 #9953
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10004 Fix - code added for mwheel zoom #10003
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10001 Issue-#9946
  DuggaSys/diagram.js
Labels: Group-3-2021

#9989 G1 2021 #9825
  DuggaSys/accessed.php
  DuggaSys/courseed.js
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/fileed.js
  DuggaSys/resulted.php
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/dugga.js
  Shared/navheader.php
Labels: Group-1-2021

#10009 G1 2021 w15 #9913
  .htaccess
  Shared/SQL/init_db.sql
  sh/course.php
  sh/index.php
  sh/query.php
Labels: Group-1-2021

#10008 Changed cursor icon depending on hotkey selection #9998
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10014 G1 2021 w15 #10012
  .htaccess
  sh/query.php
Labels: Group-1-2021

#10010 G2 2021 w15 issue#9832 - moved swimlanes to the top from the side
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-2-2021

#10006 Allow + sign to be use in name
  Shared/basic.php
Labels: Group-2-2021

#10002 Update fonts in sectioned Issue#9413
  Shared/css/style.css
Labels: Group-2-2021

#10025 G1 2021 10023
  DuggaSys/showDuggaservice.php
Labels: Group-1-2021

#10020 G1 2021 w15 #10011
  install/SQL/testdata.sql
Labels: Group-1-2021

#10019 Issue #9946 created drop down in option menu
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10016 Added icons and change current buttons into the icons
  DuggaSys/diagram.css
  DuggaSys/diagram.php
  Shared/icons/diagram_attribute.svg
  Shared/icons/diagram_box_select.svg
  Shared/icons/diagram_entity.svg
  Shared/icons/diagram_line.svg
  Shared/icons/diagram_pointer.svg
  Shared/icons/diagram_relation.svg
Labels: Diagram, Group-3-2021

#10029 Curly bracket added
  DuggaSys/diagram.css
Labels: Diagram, Group-3-2021

#10034 "Fixed" Enable grid function
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10035 Fixed ruler resize - Issue #10018
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10036 "Fixed" - marker goes over the ruler and yellow button
  DuggaSys/diagram.css
Labels: Diagram, Group-3-2021

#10046 Fixed: Center / Left alignment of text in diagram #9792
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10043 insertParam
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10052 Fixed if-statement
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10059 Added selection for checking if an input is active - ISSUE 10026
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10047 Update testdata.sql
  install/SQL/testdata.sql
Labels: Group-1-2021

#10044 updated html in showdugga.php and css in style.css
  DuggaSys/showDugga.php
  Shared/css/style.css
Labels: Group-1-2021

#10065 Fixed weak entities
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10069 The ruler now live-updating
  DuggaSys/diagram.js
Labels: Group-3-2021

#10074 Fixed Key Attribute Underline
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10081 Changed function variables #10072
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10058 update dugga.js, showdugga.php, index.php
  DuggaSys/showDugga.php
  Shared/dugga.js
  sh/index.php
Labels: Group-1-2021

#10078 Changed magic-numbers to enums
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10056 Simple solution to the issue
  Shared/dugga.js
Labels: Group-1-2021

#10075 Added a default mouse cursor on load
  DuggaSys/diagram.css
Labels: Group-3-2021

#10076 Moved function call from updatepos to updateSections
  DuggaSys/diagram.js
Labels: Group-3-2021

#10077 "Fixed" save the dropdown properties
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10084 Removed the posibility to create an edge between the same kind - ISSUE #10080
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10089 Inconsistent spacing between icons in the Navheader
  Shared/navheader.php
Labels: Group-2-2021

#10097 Now possible to select lines #9975
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10083 G1 2021 #9910
  DuggaSys/showDugga.php
  DuggaSys/showDuggaservice.php
  Shared/dugga.js
Labels: Group-1-2021

#10110 Update showDugga.php and dugga.js
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-1-2021

#10087 Updated announcement icons
  Shared/icons/new_announcement_icon.svg
  Shared/icons/new_announcement_iconShadow.svg
  Shared/navheader.php
Labels: Group-2-2021

#10070 Fixed redirection to latest courseversion from short url. Issue#9806
  sh/index.php
Labels: Group-2-2021

#10105 Removed unused code
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10103 Moving getContext
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021, High priority

#10113 Added maximun number of edges between elements
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10112 G2 2021 w16 issue#9827
  DuggaSys/contribution.js
Labels: Group-2-2021

#10109 G1 2021 #10101
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-1-2021

#10066 Assignments localstorage
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10115 Fixed syntax erros
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10118 G1 2021 #10039
  Shared/dugga.js
Labels: Group-1-2021

#10124 Now possible to select multiple lines #10111
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10120 Added ghost elements when you are adding Entities ISSUE#10082
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group-3-2021

#10126 Solved error in diagram_IOHandler.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10123 Removed unused parameters
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10127 G1 2021 w16 #9858 rebase
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-1-2021

#10143 Issue #10135: Ghost busted from data
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10128 Removed CID from "Add user"-form. Issue#10093
  DuggaSys/accessed.js
  DuggaSys/accessed.php
Labels: Group-2-2021

#10119 Added array to check if id already exists
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10130 "Fixed" Remove specific lines with delete or backspace
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10134 Holding ctrl while clicking background fixed
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10139 Added an message promp and errors-messages to lines.
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10147 Created an new toolbar, moved mousemode and zoom to it.
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10150 update showdugga.php
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10148 Issue #10138 - "Remove teacher feedback part of student submission"
  Shared/dugga.js
Labels: Group-1-2021

#10152 G2 2021 w16 issue#9870
  DuggaSys/sectionedservice.php
Labels: Group-2-2021

#10132 Fixed: #9787, states now save.
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10172 Grid is now enabled by default
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10165 Fixed zoom button placing
  DuggaSys/diagram.css
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10163 Removed SSN and PID from "Create user"-form. Issue#10149
  DuggaSys/accessed.js
  DuggaSys/accessed.php
Labels: Group-2-2021

#10182 MOTD now shows for all users, not only superusers. Issue#8551
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10154 G2 2021 w16 issue#10129
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Group-2-2021

#10108 G2 2021 w16 issue#9783
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: Group-2-2021

#10171 G1 2021 #10142
  DuggaSys/templates/generic_dugga_file_receive.js
Labels: Group-1-2021

#10184 Fixed overlapping div in option-menu
  DuggaSys/diagram.css
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10189 Deleted login-lock and score, issue #10144
  DuggaSys/templates/daily-minutes.js
Labels: Group-1-2021

#10192 Removed login-lock and score #10145
  DuggaSys/templates/group-assignment.js
Labels: Group-1-2021

#10186 Added appropriate svg images
  DuggaSys/diagram.css
  DuggaSys/diagram.php
  Shared/icons/diagram_zoomin.svg
  Shared/icons/diagram_zoomout.svg
Labels: Diagram, Group-3-2021

#10183 Group3 2021 w16 #10061
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10187 Added active class for modes in toolbar
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10170 Fixed: No error message for reaching line limit
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_zoomin.svg
  Shared/icons/diagram_zoomout.svg
Labels: Diagram, Group-3-2021

#10177 Fixed so that the "Properties box" updates when using the box select tool
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10196 Removed unused elements in the diagram and the nav and old-toolbar
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10197 Switched out "enable grid" button
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_grid.svg
Labels: Diagram, Group-3-2021

#10198 Added background color and shadow to the ruler
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10173 Checks if usergroups has the value null instead of "none" Issue#9752
  DuggaSys/resultedservice.php
Labels: Group-2-2021

#10207 Added missing else statement
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10204 Added function to enable and disable ruler
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10203 Update dugga.js and generic_dugga_file_receive.js
  DuggaSys/templates/generic_dugga_file_receive.js
  Shared/dugga.js
Labels: Group-1-2021

#10213 Removed pointer event from toolTipText to fix the hover.
  DuggaSys/diagram.css
Labels: Diagram, Group-3-2021

#10215 Added svg image to ruler button
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_ruler.svg
Labels: Diagram, Group-3-2021

#10176 Group3 2021 w16 10160
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10222 Added highlighted background to grid / ruler buttons
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10211 updated init_db.sql and alterTables.sql
  Shared/SQL/alterTables.sql
  Shared/SQL/init_db.sql
Labels: Group-1-2021

#10217 G1 W16 2021 #10167
  DuggaSys/filereceive_dugga.php
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10209 Fix fab button overflow in mobile landscape issue#10179
  Shared/css/style.css
Labels: Group-2-2021

#10214 "Fixed" Make options side panel extend to the top
  DuggaSys/diagram.css
Labels: Diagram, Group-3-2021

#10219 G2 2021 w16 issue#10079
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: Group-2-2021

#10195 G1 2021 w16 #10091
  DuggaSys/showDugga.php
  DuggaSys/showDuggaservice.php
  Shared/dugga.js
Labels: Group-1-2021

#10235 change name for enableGrid and enableRuler
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10239 G1 2021 w16 #10141
  DuggaSys/showDugga.php
  Shared/dugga.js
  Shared/hashpasswordauth.php
Labels: Group-1-2021

#10232 Update sectioned.js
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10199 Swimlanes now hide after clicking the arrow once. Issue#10185
  Shared/css/style.css
Labels: Group-2-2021

#10247 Make the global timer reset when a new message is pushed
  DuggaSys/diagram.js
Labels: Group-3-2021

#10229 Added functionality when drawing lines between elements #10157
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10242 Changed cursor style to default
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10248 Added previous selected elements to box-select
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10181 Responsive Swimlane
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Group-2-2021

#10250 Diagram code refactored
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10259 2021 w16 merge
  DuggaSys/accessed.js
  DuggaSys/accessed.php
  DuggaSys/contribution.js
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/resultedservice.php
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/sectionedservice.php
  DuggaSys/showDugga.php
  DuggaSys/showDuggaservice.php
  Shared/css/style.css
  Shared/dugga.js
  Shared/hashpasswordauth.php
  Shared/icons/diagram_grid.svg
  Shared/icons/diagram_ruler.svg
  Shared/icons/diagram_zoomin.svg
  Shared/icons/diagram_zoomout.svg
  Shared/icons/new_announcement_icon.svg
  Shared/icons/new_announcement_iconShadow.svg
  Shared/navheader.php
  install/SQL/testdata.sql
  sh/index.php
Labels: Group-1-2021, Group-2-2021, Group-3-2021

#10268 G1 2021 w17 #10053
  DuggaSys/showDuggaservice.php
  DuggaSys/templates/generic_dugga_file_receive.js
  Shared/dugga.js
Labels: Group-1-2021

#10270 Previously selected items cleared when switching to line creation mode
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021
