Repository HGustavs/LenaSYS, pull requests merged in 2021-05, with the labels that each got.

#10527 Group3 2021 w18 10514
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10573 Only clear contextLine if ctrl is not pressed when clicking the container
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10581 Added comments containing parameters and return.
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10587 Update diagram.js
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10590 Created thicker lines for origo on the x and y axes
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10596 "Fixed" Tool-tip for the option-panel
  DuggaSys/diagram.css
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10523 Analytics page and "hamburger"-button now shows properly for both teachers and superusers. Issue#10499
  DuggaSys/analytic.php
  DuggaSys/analyticService.php
  Shared/navheader.php
  Shared/sessions.php
Labels: Group-2-2021

#10528 Swimlane layout change
  Shared/css/style.css
Labels: Group-2-2021

#10608 Moved the bottom buttons
  Shared/css/style.css
Labels: Group-2-2021

#10609 Removed faulty code
  DuggaSys/analytic.php
  DuggaSys/analyticService.php
  Shared/navheader.php
  Shared/sessions.php
Labels: Group-2-2021

#10610 G1 2021 #10572
  Canvas_test_data.md
Labels: Group-1-2021

#10604 Double-click functionality for editing element text
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10603 No longer possible to access student data through the accessed page. Issue#10547
  DuggaSys/accessedservice.php
Labels: Group-2-2021

#10602 G2 2021 w18 issue#10558 -> changed lightbulb icons
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10605 Receiptbox - Remove the receipt numbers when saving a dugga #10592
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-1-2021

#10597 G1 2021 w18 #10474 v2
  Shared/dugga.js
Labels: Group-1-2021

#10591 G1 2021 w18 #10314
  DuggaSys/clickcounter.js
  DuggaSys/showDugga.php
  Shared/css/style.css
  Shared/dugga.js
  Shared/navheader.php
Labels: Group-1-2021

#10613 Score in localstorage - #10435
  Shared/dugga.js
Labels: Group-1-2021

#10614 Hamburger menu in sectioned(courses) now show for both supersusers and teachers Issue#10499v2
  Shared/navheader.php
  Shared/sessions.php
Labels: Group-2-2021

#10617 Implemented the new Demo Diagram from issue #10577
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10620 Fix: Only the diagram is magnified when zooming
  DuggaSys/diagram.js
Labels: Diagram, DiagramAppearance, Group-3-2021

#10631 Made it more clear which lines are selected
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10623 Removed reset button for rapport inlämning
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10634 Fix: backlayer-lineIDs value copy.
  DuggaSys/diagram.js
Labels: Diagram, DiagramLines, Group-3-2021

#10624 Removed Random css dugga pop-up window #10601
  DuggaSys/templates/html_css_dugga.html
  DuggaSys/templates/html_css_dugga_light.html
Labels: Group-1-2021

#10638 Create feedback area for teachers #10568
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10635 Receiptbox - The exclamation point is "undefined" if we enter a hash & password URL and press Save #10606
  Shared/dugga.js
  sh/index.php
Labels: Group-1-2021

#10611 G1 2021 #10574
  Canvas_test_data.md
Labels: Group-1-2021

#10641 The announcement icon in the navbar disappears when the width of the …
  Shared/css/style.css
Labels: Group-2-2021

#10646 Replace popup instructions in linjeduggor #10642
  DuggaSys/templates/dugga3.html
  Shared/css/style.css
Labels: Group-1-2021

#10639 G1 2021 #10628 Create a redirection button for showdugga.php
  DuggaSys/showDugga.php
  Shared/css/dugga.css
  Shared/dugga.js
Labels: Group-1-2021

#10652 Removed bulb and dugga from navbar
  Shared/dugga.js
Labels: Group-2-2021

#10643 Made elements snap to grid as a unit
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10653 Change the title of assignments #10629
  Shared/dugga.js
Labels: Group-1-2021

#10612 Update style.css (Issue #10265)
  Shared/css/style.css
Labels: Group-2-2021

#10664 Create assignment in Canvas for the master branch #10644
  Canvas_test_data.md
Labels: Group-1-2021

#10671 Added trigger
  Shared/SQL/alterTables.sql
  Shared/SQL/init_db.sql
Labels: Group-1-2021

#10667 Added toggleFeedback function and changed feedback area construction
  DuggaSys/showDugga.php
  DuggaSys/templates/generic_dugga_file_receive.js
  Shared/dugga.js
Labels: Group-1-2021

#10670 Teacher gets a variant! #10650
  DuggaSys/showDuggaservice.php
Labels: Group-1-2021

#10654 Double lines are now included in selection box
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10673 G1 2021 w18 #10627
  DuggaSys/showDugga.php
  DuggaSys/templates/clipping_masking_dugga.js
  DuggaSys/templates/dugga1.js
  DuggaSys/templates/dugga2.js
  DuggaSys/templates/dugga3.js
  DuggaSys/templates/dugga4.js
  DuggaSys/templates/generic_dugga_file_receive.js
  DuggaSys/templates/html_css_dugga.js
  DuggaSys/templates/kryss.js
  Shared/dugga.js
Labels: Group-1-2021

#10663 Fix bug where ghostelement got removed when pressing esc
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10666 Elements can now be locked in place
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10674 Update delElement
  Shared/css/style.css
Labels: Group-2-2021

#10668 Made a template of a A4-sheet
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_a4.svg
Labels: Diagram, Group-3-2021

#10680 Weekly merge W18 Group 3
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_a4.svg
Labels: Group-3-2021

#10681 G1 2021 w18
  Canvas_test_data.md
  DuggaSys/clickcounter.js
  DuggaSys/showDugga.php
  DuggaSys/showDuggaservice.php
  DuggaSys/templates/clipping_masking_dugga.js
  DuggaSys/templates/dugga1.js
  DuggaSys/templates/dugga2.js
  DuggaSys/templates/dugga3.html
  DuggaSys/templates/dugga3.js
  DuggaSys/templates/dugga4.js
  DuggaSys/templates/generic_dugga_file_receive.js
  DuggaSys/templates/html_css_dugga.html
  DuggaSys/templates/html_css_dugga.js
  DuggaSys/templates/html_css_dugga_light.html
  DuggaSys/templates/kryss.js
  Shared/SQL/alterTables.sql
  Shared/SQL/init_db.sql
  Shared/css/dugga.css
  Shared/css/style.css
  Shared/dugga.js
  Shared/navheader.php
  dbTables.md
  install/SQL/testdata.sql
  sh/index.php
Labels: Group-1-2021

#10702 Diagram: Reduced history data size
  DuggaSys/diagram.js
Labels: Diagram, Diagram StateMachine, Group-3-2021, High priority

#10696 Added warnings for when clicking on reset buttons #10676
  DuggaSys/templates/3d-dugga.js
  DuggaSys/templates/XMLAPI_report1_file_receive.js
  DuggaSys/templates/bit-dugga.js
  DuggaSys/templates/boxmodell.js
  DuggaSys/templates/clipping_masking_dugga.js
  DuggaSys/templates/color-dugga.js
  DuggaSys/templates/curve-dugga.js
  DuggaSys/templates/dugga1.js
  DuggaSys/templates/dugga2.js
  DuggaSys/templates/dugga3.js
  DuggaSys/templates/dugga4.js
  DuggaSys/templates/dugga5.js
  DuggaSys/templates/feedback_dugga.js
  DuggaSys/templates/generic_dugga_file_receive.js
  DuggaSys/templates/group-assignment.js
  DuggaSys/templates/html_css_dugga.js
  DuggaSys/templates/html_css_dugga_light.js
  DuggaSys/templates/placeholder_dugga.js
  DuggaSys/templates/shapes-dugga.js
  DuggaSys/templates/transforms-dugga.js
Labels: Group-1-2021

#10699 Fixed weakKey attribute
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10700 Added div with background on the ruler
  DuggaSys/diagram.css
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10703 "Fixed" There should be a way to see if a element is locked (visually)
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  Shared/icons/pad_lock.svg
Labels: Diagram, Group-3-2021

#10693 update showdugga.php
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10712 G1 2021 w19 #10665
  DuggaSys/codeviewer.js
  DuggaSys/sectioned.js
  Shared/dugga.js
  Shared/navheader.php
Labels: Group-1-2021

#10691 Added objecs for rulerSettings, zoomSettings and gridSettings
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021, Refactoring

#10715 Fixed CMD zoom in/out on mac
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10716 Diagram: Support for stepForward in the history
  DuggaSys/diagram.js
Labels: Diagram, Diagram StateMachine, Group-3-2021

#10717 8 commits >:(
  DuggaSys/sectioned.js
Labels: Group-1-2021

#10705 Added btn-disable class
  DuggaSys/showDugga.php
  Shared/css/style.css
Labels: Group-1-2021

#10622 Updated cardenality
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10723 Pull request for #10721
  DuggaSys/templates/clipping_masking_dugga.js
Labels: Group-1-2021

#10774 included the function's path in showDugga.php
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10744 G1 2021 w19 #10720
  Shared/dugga.js
Labels: Group-1-2021, LenaSYS

#10783 No more PDOException
  DuggaSys/codeviewer.php
Labels: Group-1-2021

#10751 Fixed error with Ctrl+z
  DuggaSys/diagram.js
Labels: Diagram, Diagram StateMachine, Group-3-2021

#10780 Fix bug where elements could be placed with other mouse buttons than left click
  DuggaSys/diagram.js
Labels: Bug, Elements, Group-3-2021

#10782 Change back name of element at escape pressed
  DuggaSys/diagram.js
Labels: Group-3-2021

#10785 Added line to generate properties when everything is selected
  DuggaSys/diagram.js
Labels: Bug, DiagramAppearance, Group-3-2021

#10792 Display message on properties saved
  DuggaSys/diagram.js
Labels: Bug, Diagram, Group-3-2021

#10796 Check so that only mouse button 0 can trigger double click
  DuggaSys/diagram.js
Labels: Bug, Group-3-2021

#10817 fixed an issue where the lock button in the properties field doesnt change regardless if the element is locked or not
  DuggaSys/diagram.js
Labels: Group-3-2021

#10799 No more error pop-window #10695
  DuggaSys/showDuggaservice.php
Labels: Group-1-2021

#10793 G1 2021 w19 #10726
  DuggaSys/templates/dugga4.js
  DuggaSys/templates/kryss.js
Labels: Group-1-2021, LenaSYS

#10811 sh/index.php now redirects to 404 error page when no match is found #10779
  sh/index.php
Labels: Group-1-2021

#10814 Element nodes is resized depending on zoom
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10826 Right-click trigger disabled
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10827 Fixed A4 tooltip and keybind
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10686 "Delete marked items" button now hides marked items from students instead. Issue#10280
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/sectionedservice.php
  Shared/css/style.css
Labels: Group-2-2021

#10722 Update the Hidden courses
  Shared/css/style.css
Labels: Group-2-2021

#10765 Fab button no longer covers "edit"-button in duggaed. Issue#10761
  DuggaSys/duggaed.php
Labels: Group-2-2021

#10794 Now shows which date a deadline has to be set between Issue#10697
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-2-2021

#10800 Added a margin for the "fab"-button in fileed. Issue#10795
  DuggaSys/fileed.php
Labels: Group-2-2021

#10806 Fixed broken search onclick funtion in fileed. Issue#10805
  Shared/navheader.php
Labels: Group-2-2021

#10809 Added icon and updated navheader.php issue #10807
  Shared/icons/file_download_white.svg
  Shared/navheader.php
Labels: Group-2-2021

#10766 Create AJAXservice_documentation.pdf
  Shared/Documentation/AJAXService/AJAXservice_documentation.pdf
Labels: Group-2-2021

#10810 Autoscroll to relevant swimlane#10756
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10819 Reverted Template Literals
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10829 Added some styling so linjeduggor is centered
  DuggaSys/templates/dugga3.html
  Shared/css/style.css
Labels: Group-1-2021, LenaSYS

#10815 G1 2021 w19 #10500
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  DuggaSys/resultedservice.php
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
Labels: Group-1-2021

#10833 G1 2021 #10825
  DuggaSys/templates/kryss.js
  Shared/dugga.js
Labels: Group-1-2021

#10835 Added if-statement
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10832 Added teacher access/functionality #10781
  DuggaSys/showDugga.php
Labels: Group-1-2021

#10834 You get prompted for password when you update the "Rapport inlämning" dugga #10735
  DuggaSys/showDugga.php
  DuggaSys/showDuggaservice.php
Labels: Group-1-2021, LenaSYS

#10877 Added button descriptions in hamburger menu. Issue#10836
  Shared/css/style.css
  Shared/navheader.php
Labels: Group-2-2021

#10868 Make handle hash great again #10830
  DuggaSys/templates/clipping_masking_dugga.js
  DuggaSys/templates/dugga1.js
  DuggaSys/templates/dugga2.js
  DuggaSys/templates/dugga3.js
  DuggaSys/templates/dugga4.js
  DuggaSys/templates/generic_dugga_file_receive.js
  DuggaSys/templates/html_css_dugga.js
  DuggaSys/templates/kryss.js
  Shared/dugga.js
Labels: Group-1-2021

#10842 G2 2021 w19 issue#10552
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10885 Changed lower to upper case in query
  DuggaSys/showDuggaservice.php
Labels: Group-1-2021

#10803 Solved "cmd"-c and "cmd"-v functionality
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021, Key-bind

#10870 Fixed demo diagram
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10872 Diagram: Replay-mode
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10869 Fix: copy-paste after/before panning or moving elements
  DuggaSys/diagram.js
Labels: Diagram, Diagram StateMachine, Group-3-2021

#10879 Buttons are now enabled in duggas after interacting #10844
  DuggaSys/templates/clipping_masking_dugga.js
  DuggaSys/templates/html_css_dugga.html
  DuggaSys/templates/kryss.js
  Shared/dugga.js
Labels: Group-1-2021

#10896 Remove grade from table #10895
  DuggaSys/resulted.js
  DuggaSys/resultedservice.php
Labels: Group-1-2021

#10909 Uncaught TypeError: Cannot read property 'style' of null #10850
  Shared/dugga.js
Labels: Group-1-2021

#10908 Fix: timelimit append on object
  DuggaSys/diagram.js
Labels: Diagram, Diagram StateMachine, Group-3-2021

#10790 Change position of checking ctrl down
  DuggaSys/diagram.js
Labels: Bug, Group-3-2021

#10866 Fixed correct coordinates on ruler when zooming
  DuggaSys/diagram.js
Labels: Diagram, DiagramRuler, Group-3-2021

#10924 Hash in resulted.php redirect to the corresponding submission #10851
  DuggaSys/resulted.js
Labels: Group-1-2021

#10923 Added timeSubmitted as sortable
  DuggaSys/resulted.js
Labels: Group-1-2021

#10886 Fixed: Bug with panning mode staying active
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-3-2021

#10905 Changed hide multiple button icon
  DuggaSys/sectioned.php
  Shared/icons/ghost_icon.svg
Labels: Group-2-2021

#10894 Removed duplicate announcement button
  Shared/css/style.css
Labels: Group-2-2021

#10904 G2 2021 w19 issue#10831
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10801 Fix so that the ruler bars move independantlly of the x and y position of the mouse positon
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10837 Removed the option to delete elements when in line creation mode
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10925 Fixed the "Ritverktyg" box overlapping
  DuggaSys/templates/dugga3.html
Labels: Group-1-2021

#10927 Dokument how to add LenaSYS assignment into a Canvas course assignment #10920
  Canvas documentation/Pictures/addlena1.png
  Canvas documentation/Pictures/addlena2.png
  Canvas documentation/Pictures/addlena3.png
  Canvas documentation/add_lenasys_assignment_into_canvas.md
Labels: Group-1-2021

#10930 G1 2021 w19 #10865
  sh/index.php
  sh/query.php
Labels: Group-1-2021

#10941 Group 3 Weekly Merge W19
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_stepback.svg
  Shared/icons/diagram_stepforward.svg
  Shared/icons/pad_lock.svg
  Shared/icons/zoom-message-icon.svg
Labels: Group-3-2021

#10922 Created SVG for replay button
  DuggaSys/diagram.php
  Shared/icons/diagram_replay.svg
Labels: Diagram, Group-3-2021

#10933 Updated the demo diagram elements to the right sizes and positions.
  DuggaSys/diagram.js
Labels: Diagram, Elements, Group-3-2021

#10948 RE: Updated the demo diagram elements to the right sizes and positions.
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10937 Blacklisted id on append and changed number check
  DuggaSys/diagram.js
Labels: Diagram, Diagram StateMachine, Group-3-2021

#10940 Cleared the replayTimer in diagram.
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10938 "Fixed" Small bug: Exiting Replay-mode with Esc not always working
  DuggaSys/diagram.js
Labels: Diagram, Diagram StateMachine, Group-3-2021

#10957 Contribution committree#10382
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  DuggaSys/contributionservice.php
Labels: Group-2-2021

#10950 update dugga.js
  Shared/dugga.js
Labels: Group-1-2021

#10953 Remove the error when the "Flytta ner" button is pressed in Linjedugga #10821
  DuggaSys/templates/dugga3.js
Labels: Group-1-2021

#10956 Dropdown menu text is now clickable
  DuggaSys/sectioned.js
  Shared/css/style.css
  Shared/navheader.php
Labels: Group-2-2021

#10954 Added teacher access check
  DuggaSys/resultedservice.php
Labels: Group-1-2021

#10976 Removed email button
  DuggaSys/resulted.php
Labels: Group-1-2021

#10977 Removed the examinator label and dropdown
  DuggaSys/resulted.php
Labels: Group-1-2021

#10962 Click to close burgermenu
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10969 Change the swimlane text color
  DuggaSys/sectioned.js
Labels: Group-2-2021

#10985 Make swimlane centered
  Shared/css/style.css
Labels: Group-2-2021

#10959 Update navheader.php Issue #10915
  Shared/navheader.php
Labels: Group-2-2021

#10993 Added scrollbar and some styiling to commit tree
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  Shared/css/style.css
Labels: Group-2-2021

#10978 Removed the dropdown and label for filter
  DuggaSys/resulted.php
Labels: Group-1-2021

#10903 Changes to snap-to-grid functionality
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10951 Saving both copied elements and lines to localstorage
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10966 Added zoomfact to margin
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10979 Chnaged key length to 2
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10992 Added if statement to check if element you clicked on is in container
  DuggaSys/diagram.js
Labels: Diagram, Elements, Group-3-2021

#10991 Added check if replay-mode is active on "esc"
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#10988 Added missing changes to stateMachine
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#11002 Center camera
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/.svg
  Shared/icons/screenUpdate.svg
Labels: Diagram, Group-3-2021

#10990 Changed max zoom-out to 0.25 instead of 0.125
  DuggaSys/diagram.js
Labels: Diagram, Group-3-2021

#11001 "Minor error is thrown, noticed when reviewed issue #10954" - #10986
  DuggaSys/resulted.php
Labels: Group-1-2021

#11007 new column in database - TimesAccessed #10980
  DuggaSys/showDugga.php
  DuggaSys/showDuggaservice.php
  Shared/SQL/alterTables.sql
  Shared/SQL/init_db.sql
  Shared/dugga.js
Labels: Group-1-2021

#10995 Some of our solutions for URL are hardcoded make them relative in appropriate places #10931
  DuggaSys/resulted.js
  Shared/dugga.js
Labels: Group-1-2021
