Repository HGustavs/LenaSYS, pull requests merged in 2022-05, with the labels that each got.

#11905 Changed how number is sorted in contribution on the web-server
  DuggaSys/contribution.js
Labels: Group-3-2022

#11941 G3 2022 w5 #11928
  DuggaSys/diagram.php
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-3-2022, Waiting for review

#11971 Modified if statement so that only the table rank gets decimals
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group-3-2022

#11982 Proposed implementation
  DuggaSys/contribution.js
  Shared/css/style.css
Labels: Group-3-2022

#11999 Finished issue #11896
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
  Shared/SQL/init_db.sql
Labels: Group-3-2022

#11995 Added a check to only create an alert box if the user has clicked a button
  Shared/dugga.js
Labels: Group-3-2022

#12026 Modified fileed so that html type files uses other function
  DuggaSys/fileed.js
  install/courses/2/helloWorld.html
Labels: Group-3-2022

#12033 Added style margin-top
  DuggaSys/courseed.js
Labels: Group-3-2022

#12031 Resolved that you can not drag around the element
  DuggaSys/sectioned.js
Labels: Group-3-2022, Waiting for merge

#12040 G3 2022 w5 #11956
  DuggaSys/sectioned.js
Labels: Group-3-2022

#12059 removed parent attribute #11916
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#12063 Underline keys attributes #11909
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#12067 added more account request bar click functionality
  DuggaSys/contribution.js
Labels: Group-3-2022

#11910 Variant status are no longer "Undefined"
  DuggaSys/duggaed.js
Labels: Group-1-2022, Test Passed

#11940 Fixed buttons for year and course selection
  DuggaSys/contribution.js
  Shared/css/style.css
Labels: Group-3-2022

#12077 Added some code that goes trough the array and checks the correct boxes
  DuggaSys/sectioned.js
Labels: Group-3-2022

#12078 Added descriptive text to buttons
  DuggaSys/contribution.js
Labels: Group-3-2022

#12071 Made columns sizes remain consistent when searching. Changed code related to the alternating row colors.
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
Labels: Group-3-2022

#12093 Fixed missing changes
  DuggaSys/contribution.js
Labels: Group-3-2022

#12072 Made it possible to search multiple columns
  DuggaSys/duggaed.js
Labels: Group-3-2022

#12085 There is no "Back to top" - button on pages other than main course pages #12051
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/resulted.js
  DuggaSys/resulted.php
Labels: Group-3-2022

#12088 Created a hover function on some parts in the hamburger menu that´s missing the hover function
  Shared/css/style.css
  Shared/navheader.php
Labels: Group-3-2022

#11992 Selected objects get white text. Issue #11986.
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#12087 Including the new testing-page while installing locally only works on windows machines #11875
  install/SQL/testingCourseData.sql
  install/install.php
Labels: Group-2-2022, Waiting for merge

#12083 Fixed black background to match with dark mode
  Shared/css/blackTheme.css
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#12081 Undo button if accidental deletion of an example #11960
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-2-2022, Waiting for merge

#12079 Fixed navheader access #12011
  DuggaSys/codeviewer.js
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#12074 Resizing boxes in template 7 implemented.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#12070 Changed "New Quote" to "New message"
  DuggaSys/sectioned.php
Labels: Group-2-2022, Waiting for merge

#12069 Added dark mode in in 4 different files.
  DuggaSys/accessed.php
  DuggaSys/duggaed.php
  DuggaSys/fileed.php
  DuggaSys/resulted.php
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/blackTheme.css
  Shared/css/style.css
  Shared/css/whiteTheme.css
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#12066 Resizing boxes in template 6.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#12056 Fixed fatal error #12014
  DuggaSys/codeviewerService.php
Labels: Group-2-2022, Waiting for merge

#12034 Added purple color background to the checkboxes.
  DuggaSys/sectioned.js
Labels: Group-2-2022, Waiting for merge

#12028 Cancel Button position
  DuggaSys/sectioned.php
Labels: Group-2-2022, Waiting for merge

#12027 Fixed Absolute deadlines #11224
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-2-2022, Waiting for merge

#12096 11934 dugga instructions editable
  DuggaSys/duggaed.js
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-3-2022

#12024 Added an ID in both whiteTheme.css and blackTheme.css files.
  Shared/css/blackTheme.css
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#12013 Thickness of the theme toggle button
  Shared/css/style.css
  Shared/icons/ThemeToggle.svg
Labels: Group-2-2022, Waiting for merge

#12006 Removed the whitespace in templates
  Shared/css/blackTheme.css
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#11994 Added overflow handler to div2 container.
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11990 Added a new background color
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11923 possible fix for the file fetching problem
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/showDugga.php
Labels: Group-1-2022, Test Passed

#11988 Home icon #11929
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11974 Deleted white background
  DuggaSys/courseed.js
Labels: Group-2-2022, Waiting for merge

#11970 Changed the icon ID
  DuggaSys/sectioned.js
  Shared/css/blackTheme.css
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#11969 Add target _blank to github link
  DuggaSys/courseed.js
Labels: Group-2-2022, Waiting for merge

#12032 Created an icon for the ER-table functionality #11996.
  DuggaSys/diagram.php
  Shared/icons/diagram_ER_table.svg
  Shared/icons/diagram_ER_table2.svg
  Shared/icons/diagram_ER_table_info.svg
  Shared/icons/diagram_ER_table_information.svg
Labels: Diagram, Group-1-2022, Waiting for merge, Test Passed

#11962 Added white text.
  DuggaSys/sectioned.php
  Shared/css/blackTheme.css
Labels: Group-2-2022, Waiting for merge

#11979 Fix for issue #11973 The distance the label gets displaced from the line is incorrect
  DuggaSys/diagram.js
  DuggaSys/templates/diagram_dugga.js
Labels: Diagram, Group-1-2022, Test Passed

#11959 Ghost button disabled when no checkboxes is clicked #11816
  DuggaSys/sectioned.js
Labels: Group-2-2022, Waiting for merge

#11948 Change formatting of dropdown menu on forward- and backwardbutton
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11942 Changed color of editbtn and fontsize of title in codeviewer
  DuggaSys/codeviewer.js
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#11937 Removed duplicate event.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11908 Updated the Burgermeny button for gridview.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11985 fix for issue #11981 The snap is to sensitive for label displacements
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11903 SH URL complete implementation #11512
  sh/index.php
Labels: Group-2-2022, Waiting for merge

#12062 Updated cursor style with responsive behavior in diagram.js #12001
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#12029 Fix for issue #11939 Description file upload and link up
  DuggaSys/showDugga.php
Labels: Group-1-2022, Test Passed

#12094 Removed and fixed double code in mdown #12064
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#11895 G3 2022 w5 #00001 five times faster load speed on the file contributionservice.php
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
Labels: Group-3-2022

#11918 Displays a description of the dropdown menus and of relative when you hover over them
  DuggaSys/sectioned.php
Labels: Group-3-2022

#12098 Log in for git users is now somewhat implemented/the groundwork is laid
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  DuggaSys/contributionservice.php
  Shared/dugga.js
  Shared/sessions.php
Labels: Group-3-2022

#12122 Fixed bug caused by weekly merge
  DuggaSys/sectioned.js
Labels: Group-3-2022

#12138 Solved the problem in the hamburger menu
  Shared/navheader.php
Labels: Group-3-2022

#12167 Fixed the return button interactive area
  Shared/navheader.php
Labels: Group-3-2022

#12171 added navbar to contribution page
  DuggaSys/contribution.php
  Shared/navheader.php
Labels: Group-3-2022

#12169 duggaTitle argument missing or invalid.
  DuggaSys/templates/curve-dugga.js
  DuggaSys/templates/daily-minutes.js
  DuggaSys/templates/dugga1.js
  DuggaSys/templates/dugga2.js
  DuggaSys/templates/dugga3.js
  DuggaSys/templates/duggaTest.js
  DuggaSys/templates/feedback_dugga.js
  DuggaSys/templates/group-assignment.js
  DuggaSys/templates/html_css_dugga.js
  DuggaSys/templates/html_css_dugga_light.js
  DuggaSys/templates/kryss.js
  DuggaSys/templates/placeholder_dugga.js
  Shared/dugga.js
Labels: Group-3-2022

#12188 G3 2022 w6 #12136
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  Shared/icons/githubLink-icon.png
Labels: Group-3-2022

#12190 Fixed the navheader issue
  Shared/navheader.php
Labels: Group-3-2022

#12160 Removed delete button from edge creation. Issue #12104
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#12192 Fixed the overlaping navbar and sidebar
  Shared/css/style.css
Labels: Group-3-2022

#12193 Implemented teacher & user login for contribution.
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
Labels: Group-3-2022

#12204 Variants are no longer Undefined by default on localhost
  DuggaSys/duggaed.js
Labels: Group-1-2022, Test Passed

#12170 Fixed option pane issue #12127
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#12206 Behaviour of selection box in different scenarios #12180
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-1-2022

#12172 Fixed the placement of the FAB button
  DuggaSys/accessed.php
  DuggaSys/courseed.js
  DuggaSys/duggaed.php
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: Group-3-2022

#12225 Added dugga title for superusers
  DuggaSys/showDuggaservice.php
Labels: Group-3-2022

#12234 Issue with scrolling in commit tree and weakly bar chart fixed #12086
  DuggaSys/contribution.js
  DuggaSys/contribution.php
Labels: Group-3-2022

#12240 Solved validation for username and password on contribution.php #12218
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
Labels: Group-3-2022

#12207 Improvement for issue #11744 Table definitions created automatically when creating ER or UML diagram.
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  Shared/css/style.css
Labels: Group-1-2022, Test Passed

#12245 The ability to move elements and moments should be limited #12135
  DuggaSys/sectioned.js
  Shared/icons/nonDragableArea.jpg
  Shared/icons/select.png
Labels: Group-3-2022

#12250 Allowed for duggor and dugga variants to be deleted by pressing enter #12179
  DuggaSys/duggaed.js
Labels: Group-1-2022, Test Passed

#12294 Fixed issue with clicking ENTER in the contribution login menu
  DuggaSys/contribution.js
Labels: Group-3-2022, Waiting for merge

#12222 File with same name and filetype will not be uploaded #11993
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
  DuggaSys/filereceive.php
  DuggaSys/templates/feedback_dugga.js
Labels: Group-1-2022, Test Passed

#12269 Arrow does not disappear
  DuggaSys/diagram.js
Labels: Group-1-2022, Test Passed

#12293 Added database entries to duggor without useranswers
  install/SQL/demoCourseData.sql
  install/SQL/testdata.sql
Labels: Group-3-2022

#12256 Fix for issue #12238 Create a button for turning on off the error checking
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/templates/diagram_dugga.js
Labels: Group-1-2022, Test Passed

#12248 Fixed so "Uploaded diagram"-window doesn't shrink anymore so scrolling isn't as frustrating #12181
  DuggaSys/duggaed.php
Labels: Group-1-2022, Test Passed

#12308 G3 2022 w6 #12299
  DuggaSys/sectioned.js
  Shared/icons/select.png
Labels: Group-3-2022

#12246 Updated the color selector to make it colour blind friendly #12177
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#12223 Empty dropdown option in "Add diagram to dugga". #12201
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  Shared/dugga.js
Labels: Diagram, Group-1-2022, Test Passed

#12212 Pasted elements do not cover messages
  DuggaSys/diagram.css
Labels: Diagram, Group-1-2022, Test Passed

#12209 Double click UMLRelations fixed #12203
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#12197 Move load, save and load dugga button further down on page. #12143
  Shared/css/style.css
Labels: Diagram, Group-1-2022, Test Passed

#12310 Modified the circle diagram to that multiple polygons are shown with the different types
  DuggaSys/contribution.js
  Shared/css/style.css
Labels: Group-3-2022

#12313 Updated commitDiv to not show empty lines
  DuggaSys/contribution.js
Labels: Group-3-2022

#12324 Added dedicated HTML/CSS for contribution.php and implemented
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  DuggaSys/contribution_loginbox.php
Labels: Group-3-2022

#12301 Contribution Logout Button Now Uses git_logout()
  Shared/navheader.php
Labels: Group-3-2022

#12317 Prevented deleted headers from reappearing
  DuggaSys/sectioned.js
Labels: Group-3-2022

#12333 Added functionality to access to a dugga, via hash, for loading of dugga and saving of dugga. [#11365]
  DuggaSys/sectioned.php
  DuggaSys/showDugga.php
  DuggaSys/templates/diagram_dugga.js
  DuggaSys/validateHash.php
  sh/index.php
Labels: Group-1-2022, Test Passed

#12315 Created and added an icon for the new error check functionality and changed the title #12241
  DuggaSys/diagram.php
  Shared/icons/diagram_errorCheck.svg
Labels: Diagram, Group-1-2022, Test Passed

#12351 Checkboxes should now skip invisible headers
  DuggaSys/sectioned.js
Labels: Group-3-2022

#12307 Added ability to choose between candidate and primary keys #12158
  DuggaSys/diagram.js
Labels: Group-1-2022, Test Passed

#12304 Created working keybinds for two functionalities #12277
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagramkeybinds.md
Labels: Diagram, Group-1-2022, Test Passed

#12253 Made all dates dynamic rather than static in the contributionsservice.php file
  DuggaSys/contributionservice.php
Labels: Group-3-2022

#12282 Option panel open and close functionality #12140
  DuggaSys/diagram.css
Labels: Diagram, Group-1-2022, Test Passed

#12362 Buttons nolonger created on headers
  DuggaSys/sectioned.js
Labels: Group-3-2022

#12363 Removed one onclick that was called twice
  Shared/navheader.php
Labels: Group-3-2022

#12368 Moved contribution functions into dedicated file, cleaned up ajaxservice from previous contrib
  DuggaSys/contribution.js
  DuggaSys/contribution_loginbox.js
  DuggaSys/contribution_loginbox.php
  DuggaSys/contribution_loginbox_service.php
  DuggaSys/contributionservice.php
  Shared/dugga.js
Labels: Group-3-2022

#12355 made the icons white on the purple background
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#12350 Delete Canvas_test_data.md
  Canvas_test_data.md
  CheckIssues.txt
Labels: Group-2-2022, Waiting for merge

#12342 changed the colours of rows of the code examples
  Shared/css/blackTheme.css
Labels: Group-2-2022, Waiting for merge

#12328 Dark mode on forgot password page.
  Shared/loginbox.php
Labels: Group-2-2022, Waiting for merge

#12322 Fixed error in "Edit course" version name #12202
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-2-2022, Waiting for merge

#12321 "Edit file" window behaves as a popup window #12292
  DuggaSys/codeviewer.js
  DuggaSys/codeviewer.php
  Shared/css/blackTheme.css
  Shared/css/style.css
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#12295 Removed alert and added text
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-2-2022, Waiting for merge

#12291 Removed the MOTD button and any mentions of it.
  DuggaSys/sectioned.js
  Shared/dugga.js
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#12274 Fixed the color of the icon in dark mode.
  DuggaSys/sectioned.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#12273 Added style for the link icon
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#12366 Added home, return and darkmode to burger menu.
  DuggaSys/sectioned.js
  Shared/css/style.css
  Shared/icons/collapse_icon.svg
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#12255 Made the hamburgermenu icon bigger
  Shared/css/style.css
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#12232 Added support for nested collapsible tags #11428
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#12230 Changed position and style for home icon in navbar
  Shared/css/style.css
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#12224 Adding a new button that changes the visibility of examples to public in the sectioned.php
  .vscode/launch.json
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  DuggaSys/sectionedservice.php
  Shared/icons/eye_icon.svg
Labels: Group-2-2022, Waiting for merge

#12200 Added a drag and drop feature for code windows
  DuggaSys/codeviewer.js
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  Shared/css/codeviewer.css
  Shared/icons/draganddrop.png
Labels: Group-2-2022, Waiting for merge

#12198 The burger menu now behaves like other windows #12173
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#12191 Fixed the background color in dark mode in file "fileed.php".
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#12187 Removed unnecessary console log
  DuggaSys/darkmodeToggle.js
Labels: Group-2-2022, Waiting for merge

#12185 Removed the feedback button
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#12175 Template 8 resizing should now work.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#12156 Create tests on the lenasys website
  install/SQL/testingCourseData.sql
  install/courses/global/PHP-TEST1.php
  install/install.php
Labels: Group-2-2022, Waiting for merge

#12139 Added margin to whiteTheme
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#12130 Added resize functionality to template 4.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#12129 Removed the opacity
  DuggaSys/courseed.js
Labels: Group-2-2022, Waiting for merge

#12319 Fix for issue #12239 Hide the button to turn on of error checking when error checking is not allowed
  DuggaSys/diagram.js
  DuggaSys/duggaed.php
  DuggaSys/templates/diagram_dugga.js
Labels: Group-1-2022, Test Passed

#12349 fixed the dashes to a consistent style issue #12039
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-1-2022, Test Passed

#12367 Created a working keybind for the new error check functionality #12360
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagramkeybinds.md
Labels: Diagram, Group-1-2022, Test Passed

#12357 Fixed the arrow functionality in diagram dugga #12316
  DuggaSys/templates/diagram_dugga.html
Labels: Diagram, Group-1-2022, Test Passed

#12365 Made it easier to navigate using tab and enter
  DuggaSys/courseed.js
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/css/style.css
  Shared/dugga.js
  Shared/navheader.php
Labels: Group-3-2022

#12372 Teacher history not visible in replay for student: #12145.
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-1-2022, Test Passed

#12379 i have modified the baseline of the different polygons
  DuggaSys/contribution.js
Labels: Group-3-2022

#12396 changed regex to match eachother and use same syntax
  DuggaSys/contribution_loginbox.js
  DuggaSys/contribution_loginbox_service.php
Labels: Group-3-2022

#12421 Added a dark mode variant for drag and drop immage
  Shared/css/blackTheme.css
  Shared/icons/draganddropBlack.png
Labels: Group-2-2022, Waiting for merge

#12450 User no longer gets prompted to press OK multiple times when opening dugga
  DuggaSys/showDugga.php
  DuggaSys/templates/diagram_dugga.js
Labels: Group-1-2022, Test Passed

#12449 ERRelations no longer turn black in EDGE_CREATION #12391
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Test Passed

#12410 Fixed replay button & removed launch.json #12399
  .vscode/launch.json
  DuggaSys/diagram.php
Labels: Diagram, Group-1-2022, Test Passed

#12428 Removed forgot password option from login
  DuggaSys/contribution_loginbox.js
  DuggaSys/contribution_loginbox.php
Labels: Group-3-2022

#12465 New Sections and Headers nolonger have extra btns
  DuggaSys/sectioned.js
Labels: Group-3-2022, Waiting for merge

#12452 Fixed consistent darkmode background color #12386
  Shared/css/blackTheme.css
Labels: Group-2-2022, Waiting for merge

#12469 Add padding left value
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge
