Repository HGustavs/LenaSYS, pull requests merged in 2022-04, with the labels that each got.

#11279 G1 2022 w1 #11267
  DuggaSys/accessed.js
Labels: Group-1-2022, Waiting for merge

#11290 Fixed error caused by empty array
  CheckIssues.txt
  DuggaSys/showDugga.php
  diff.txt
  testfiles/Grupp3Test/Testeing branching.txt
  testfiles/Grupp3Test/a17nikjo.txt
  testfiles/Grupp3Test/a19simru.txt
  testfiles/Grupp3Test/a20caros
  testfiles/Grupp3Test/a20johba.txt
  testfiles/Grupp3Test/a20novra.txt
  testfiles/Grupp3Test/a20sacka.txt
  testfiles/Grupp3Test/a20vicad.txt
  testfiles/Grupp3Test/b20eripe.txt
  testfiles/Grupp3Test/b20hanwa
  testfiles/Grupp3Test/b20hanwa.txt
  testfiles/Grupp3Test/b20jonlu.txt
  testfiles/Grupp3Test/c20adael.txt
  testfiles/Grupp3Test/readme.txt
Labels: Group-3-2022

#11354 Removed unnecessary comments.
  DuggaSys/contributionservice.php
Labels: Group-3-2022, Waiting for merge

#11352 Removed unnecessary and faulty references that added nothing to the database
  Shared/SQL/init_db.sql
Labels: Group-3-2022

#11347 Changed some swedish to english
  DuggaSys/sectioned.php
  DuggaSys/showDugga.php
  DuggaSys/testDugga.php
Labels: Group-3-2022, Waiting for merge

#11260 in the #motdArea there was a margin-top with -16px that is now changed to 16px
  Shared/css/style.css
Labels: Group-1-2022, Waiting for merge

#11278 Fixed incorrect double click not counting as a single click and preventing properties from appearing.
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11353 Added code that only highligt/selects text in codviewer.
  Shared/css/blackTheme.css
  Shared/css/codeviewer.css
  Shared/css/style.css
  Shared/css/whiteTheme.css
Labels: Group-2-2022, Waiting for merge

#11344 Change display style
  Shared/css/codeviewer.css
Labels: Group-2-2022, Waiting for merge

#11262 Reset button was missing from diagram
  DuggaSys/diagram.php
Labels: Group-1-2022, Waiting for merge

#11282 Fixed malpositioned background for labels
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11292 Fixed incorrect positioning of cardinality variable in diagram relations.
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11299 No zoom when redirect camera #11236
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group-1-2022, Waiting for merge

#11362 fixed the typo 'UNKz to UNK'
  DuggaSys/sectioned.js
Labels: Group-3-2022

#11280 Copy notification does not overflow under other elements #11217
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11308 added functionality to addLine
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11309 G1 2022 w1 #11305
  DuggaSys/courseedservice.php
Labels: Group-1-2022, Waiting for merge

#11312 Clean up of diagram.css #11311
  DuggaSys/diagram.css
Labels: Group-1-2022, Waiting for merge

#11328 Fixed
  DuggaSys/diagram.php
Labels: Group-1-2022, Waiting for merge

#11336 Clean up of showdoc.php #11335
  DuggaSys/showdoc.php
Labels: Group-1-2022, Waiting for merge

#11334 Clean up of showDuggaservice.php #11332
  DuggaSys/showDuggaservice.php
Labels: Group-1-2022, Waiting for merge

#11289 G2 2022 w1 #11243
  DuggaSys/codeviewer.js
  Shared/css/codeviewer.css
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11351 Removed commented code.
  DuggaSys/codeviewer.php
Labels: Group-2-2022, Waiting for merge

#11350 needed to just delete commented code
  DuggaSys/codeviewerService.php
Labels: Group-2-2022, Waiting for merge

#11360 Commented out statement that is always false
  Shared/dugga.js
Labels: Group-3-2022

#11331 G3 2022 w1 #11320
  Canvas_test_data.md
Labels: Group-3-2022

#11285 G3 2022 w1 #11220
  Shared/css/style.css
  Shared/navheader.php
Labels: Group-3-2022, Waiting for merge

#11287 Added a function on body onload
  DuggaSys/codeviewer.php
Labels: Group-2-2022, Waiting for merge

#11294 Change of default word-list for Preview.
  DuggaSys/codeviewer.js
  Hello World
  README.md
  testfiles/Grupp3Test/Testeing branching.txt
  testfiles/Grupp3Test/a19simru.txt
  testfiles/Grupp3Test/a20caros
  testfiles/Grupp3Test/a20johba.txt
  testfiles/Grupp3Test/a20novra.txt
  testfiles/Grupp3Test/b20eripe.txt
  testfiles/Grupp3Test/b20hanwa
  testfiles/Grupp3Test/b20jonlu.txt
  testfiles/Grupp3Test/c20adael.txt
  testfiles/Grupp3Test/readme.txt
Labels: Group-2-2022, Waiting for merge

#11275 Added showCopyButtons() to maximizeBoxes()
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11370 Origin/g3 2022 w1 #11227
  DuggaSys/showDuggaservice.php
  DuggaSys/templates/generic_dugga_file_receive.js
  Shared/dugga.js
Labels: Group-3-2022

#11422 G2 2022 w2 #1851
  DuggaSys/codeviewer.js
Labels: Group-2-2022

#11434 Copyclipboard should never have a style of 'block'
  DuggaSys/codeviewer.js
Labels: Group-2-2022

#11441 Added a height attribute to the buttonmenu
  Shared/css/codeviewer.css
Labels: Group-2-2022

#11452 Changed padding to margin
  DuggaSys/duggaed.php
Labels: Group-3-2022

#11463 Removed analytic files from file system
  DuggaSys/analytic.js
  DuggaSys/analytic.php
  DuggaSys/analyticService.php
  Shared/css/analytics.css
Labels: Group-3-2022

#11423 G3 2022 w2 #7712
  DuggaSys/contribution.js
Labels: Group-3-2022

#11413 G3 2022 w2 #11400
  DuggaSys/contribution.js
Labels: Group-3-2022

#11420 Fixed animations with CSS in contribution.php in file style.css
  Shared/css/style.css
Labels: Group-3-2022, Waiting for merge

#11394 Added a class DarkmodeBackgorund
  DuggaSys/codeviewer.js
  DuggaSys/codeviewer.php
  Shared/css/blackTheme.css
Labels: Group-2-2022

#11412 Scroll zoom in/out function is now mostly fixed #11058
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed, Important Comment!

#11483 Changed dugga.js to reenabled receipt popup
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-3-2022

#11435 Updated icons in diagram dugga #11395
  Shared/icons/diagram_a4.svg
  Shared/icons/diagram_attribute.svg
  Shared/icons/diagram_box_select.svg
  Shared/icons/diagram_entity.svg
  Shared/icons/diagram_grid.svg
  Shared/icons/diagram_line.svg
  Shared/icons/diagram_relation.svg
  Shared/icons/diagram_replay.svg
  Shared/icons/diagram_stepback.svg
  Shared/icons/diagram_stepforward.svg
  Shared/icons/diagram_zoomin.svg
  Shared/icons/diagram_zoomout.svg
  Shared/icons/fullscreen.svg
  Shared/icons/screenUpdate.svg
Labels: Group-1-2022, Waiting for merge, Test Passed

#11473 Implemented delete button #11387
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11391 Time intervall added #11259
  DuggaSys/diagram.js
Labels: Group-1-2022, Test Passed

#11454 fix for issue #11155 Select & Move labels in diagram
  DuggaSys/diagram.js
Labels: Group-1-2022, Test Passed

#11502 G3 2022 w2 #11379
  DuggaSys/resulted.js
  DuggaSys/resulted.php
  Shared/SortableTableLibrary/sortableTable.js
  Shared/css/style.css
Labels: Group-3-2022

#11481 Select/deselect evolved. issue#11455
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11507 Fixed issue #11506
  DuggaSys/diagram.js
Labels: Diagram, Group-1-2022, Waiting for merge, Test Passed

#11499 G1 2022 w2 #11396
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11501 Error message when creating a line on the same element #11479
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11503 Created functionality for an alert that pops up before closing diagram dugga #11485
  DuggaSys/templates/diagram_dugga.html
  DuggaSys/templates/diagram_dugga.js
Labels: Group-1-2022, Test Passed

#11444 Updated fab in style.css
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11439 move Edit button code
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11426 fixed resize problem template 4
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11425 Removed alert dialog
  DuggaSys/sectioned.js
Labels: Group-2-2022, Waiting for merge

#11392 Fixed headers in dark mode.
  Shared/css/blackTheme.css
Labels: Group-2-2022, Waiting for merge

#11509 Fixed anchor tag download to default to filename+extension instead of only filename
  DuggaSys/fileed.js
Labels: Group-3-2022

#11556 Diagram module - UML entity #11445
  DuggaSys/diagram.js
  Shared/icons/diagram_uml.svg
Labels: Group-1-2022, Waiting for testing

#11526 G2 2022 w2 #11488
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11514 Added function to remove dropdowns when user clicks outside of them.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11505 Removed faulty code #11476
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11459 update codeviewer.js
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11411 Implemented collapsible html tags. Added explanatory comments. #11369
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11564 G3 2022 w2 #11377
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/icons/canvasduggalink.svg
Labels: Group-3-2022

#11515 Dugga deadlines are now displayed the same for all screen widths.
  Shared/css/style.css
Labels: Group-3-2022

#11570 G1 2022 w2 #11395
  Shared/icons/diagram_a4.svg
  Shared/icons/diagram_attribute.svg
  Shared/icons/diagram_box_select.svg
  Shared/icons/diagram_entity.svg
  Shared/icons/diagram_grid.svg
  Shared/icons/diagram_line.svg
  Shared/icons/diagram_relation.svg
  Shared/icons/diagram_replay.svg
  Shared/icons/diagram_stepback.svg
  Shared/icons/diagram_stepforward.svg
  Shared/icons/diagram_zoomin.svg
  Shared/icons/diagram_zoomout.svg
  Shared/icons/fullscreen.svg
  Shared/icons/screenUpdate.svg
Labels: Group-1-2022, DC

#11571 G1 2022 w2 #11396
  DuggaSys/diagram.js
Labels: Group-1-2022, DC

#11573 G1 2022 w2 #11259
  DuggaSys/diagram.js
  Shared/icons/diagram_a4.svg
  Shared/icons/diagram_attribute.svg
  Shared/icons/diagram_box_select.svg
  Shared/icons/diagram_entity.svg
  Shared/icons/diagram_grid.svg
  Shared/icons/diagram_line.svg
  Shared/icons/diagram_relation.svg
  Shared/icons/diagram_replay.svg
  Shared/icons/diagram_stepback.svg
  Shared/icons/diagram_stepforward.svg
  Shared/icons/diagram_zoomin.svg
  Shared/icons/diagram_zoomout.svg
  Shared/icons/fullscreen.svg
  Shared/icons/screenUpdate.svg
Labels: Group-1-2022, DC

#11562 Onclick function on the fab button to upload local files
  DuggaSys/fileed.js
  DuggaSys/fileed.php
Labels: Group-3-2022

#11548 Implemented column filter functionality and improved the "Select all" button
  DuggaSys/resulted.js
Labels: Group-3-2022

#11547 Removed the lines "content = content.replace(/\+/g, '%2B'); for issue #11493
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
Labels: Group-3-2022, Waiting for merge

#11414 G3 2022 w2 #11325
  DuggaSys/clickcounter.js
  DuggaSys/timer.js
  Shared/dugga.js
Labels: Group-3-2022

#11546 Fixed plus signs showing incorrectly in fileed
  DuggaSys/fileed.js
  DuggaSys/showdoc.php
  Shared/markdown.js
Labels: Group-3-2022

#11588 G1 2022 w2 #11259
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for review

#11389 Tooltip functionality added to duggaed.php search bar
  DuggaSys/duggaed.js
  Shared/navheader.php
Labels: Group-3-2022

#11575 G1 2022 w2 #11455
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11576 G1 2022 w2 #11479
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11577 G1 2022 w2 #11485
  DuggaSys/templates/diagram_dugga.html
  DuggaSys/templates/diagram_dugga.js
Labels: Group-1-2022, Waiting for merge

#11578 G1 2022 w2 #11506
  DuggaSys/diagram.js
Labels: Group-1-2022, DC

#11579 G1 2022 w2 #8528
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-1-2022, Waiting for merge

#11580 G1 2022 w2 #11497
  DuggaSys/fileed.js
  DuggaSys/templates/diagram_dugga.js
Labels: Group-1-2022, Waiting for merge

#11581 G1 2022 w2 #11451
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11582 G1 2022 w2 #11442
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/exit.svg
  Shared/icons/replay.svg
Labels: Group-1-2022, Waiting for merge

#11583 G1 2022 w2 #11445
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_uml.svg
Labels: Group-1-2022, Waiting for merge

#11504 Added support for uploading .json files
  DuggaSys/fileed.js
  DuggaSys/filereceive.php
Labels: Group-1-2022, Waiting for merge

#11533 Added a description on diagram_IOHandler.php #11252
  DuggaSys/diagram_IOHandler.php
Labels: Group-1-2022, Waiting for merge

#11543 Made clarifying comments regarding uploading/saving of files (fileed.php, fileed.js, fileedservice.php, filerecieve.php)
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
  DuggaSys/filereceive.php
Labels: Group-1-2022, Waiting for merge

#11559 WIP Creation of file select drop-down menu connected to database #11477
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Group-1-2022

#11608 G3 2022 w3 #11598
  DuggaSys/contributionservice.php
Labels: Group-3-2022

#11611 Prevent "enter" from reloading page
  Shared/navheader.php
Labels: Group-3-2022

#11619 Adding graphical components for changing repositories in Contribution.php
  DuggaSys/contribution.js
  Shared/css/style.css
Labels: Group-3-2022

#11601 Added functionality to the checkboxes in the dugga filter in resulted
  DuggaSys/resulted.js
Labels: Group-3-2022

#11645 Merge this branch (#11617) into toolbox branch issue 11480
  Shared/icons/diagram_UML_entity.svg
  Shared/icons/diagram_inheritance.svg
Labels: Group-1-2022, Waiting for testing

#11644 Hide dropdownmenu when pressing the other button #11633
  DuggaSys/resulted.js
Labels: Group-3-2022

#11631 Searching in the result editor now works #11606
  DuggaSys/resulted.js
Labels: Group-3-2022

#11640 Fixed error on mouseover in weekly bar chart
  DuggaSys/contribution.js
Labels: Group-3-2022

#11648 Alert when leaving a dugga with changes done.
  DuggaSys/showDugga.php
  Shared/dugga.js
Labels: Group-3-2022

#11647 Updated renderCommits in contribution.js
  DuggaSys/contribution.js
Labels: Group-3-2022

#11675 Minor layout changes depending on screen width #11646
  DuggaSys/sectioned.js
Labels: Group-3-2022

#11603 Fixed clicking elements in line creation mode #11183
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11615 fix for issue #11480 Diagram module - Update toolbar to accomodate UML entity
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_UML_entity.svg
  Shared/icons/diagram_inheritance.svg
  Shared/icons/diagram_toolbar_arrow.svg
  Shared/icons/diagram_uml.svg
Labels: Group-1-2022, Waiting for merge, Test Passed

#11621 Moved icons into options panel and changed them into buttons in diagram dugga #11540
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Diagram, Group-1-2022, Waiting for merge, Test Passed

#11622 Removed the square around the delete button #11387
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11625 fix for issue #11155 Select & Move labels in diagram
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11635 Added selected diagram file to be included in generated JSON params
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Group-1-2022, Waiting for merge, Test Passed

#11638 cleaned up test functions and now the dropdown box lists only json files
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
Labels: Group-1-2022, Waiting for merge, Test Passed

#11668 Box around selected element: #11396
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11684 G1 2022 w3 #11342
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11686 Fixed the overlay in areas in dugga exemple
  DuggaSys/codeviewer.php
  DuggaSys/coursefooter.php
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11680 Added an actionevent to the nav buttons and removed dropdown menu name.
  DuggaSys/codeviewer.php
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11674 Make the dropbar do not disappear
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11660 Code to just copy important code
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11636 Added another clause that blocks this behaviour.
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11612 Gave a unique class to edit button #11536
  DuggaSys/codeviewer.js
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11632 Can apply invalid deadlines, fixed validateSectName function #11224
  DuggaSys/sectioned.js
Labels: Group-2-2022, Waiting for merge

#11698 Remove unnecessary code
  DuggaSys/codeviewer.php
  DuggaSys/courseed.php
  DuggaSys/coursefooter.php
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: Group-2-2022

#11699 G1 2022 repair#3
  DuggaSys/diagram.js
Labels: Group-1-2022, Waiting for merge

#11687 dugga link now works on background element
  DuggaSys/sectioned.js
Labels: Group-3-2022

#11700 Adding functionality for creating new users from git login and password popup for contribution.php #11416
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  Shared/dugga.js
  Shared/resetpw.php
Labels: Group-3-2022

#11710 href now found by searching all children
  DuggaSys/sectioned.js
Labels: Group-3-2022

#11723 Fixed fab-btn not staying up when hovering
  Shared/css/style.css
Labels: Group-3-2022

#11712 Removed the commented out code in showDugga.php for issue #11240
  DuggaSys/showDugga.php
Labels: Group-3-2022

#11722 Created a hover function that display a div when hovering over the commit links
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  Shared/css/style.css
Labels: Group-3-2022

#11750 Centered the list on the first page
  DuggaSys/courseed.js
Labels: Group-3-2022

#11747 fix for issue #11643 Teachers should be able to select which type of diagram the student are able to draw in diagram dugga's.
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/duggaed.js
  DuggaSys/duggaed.php
  DuggaSys/templates/diagram_dugga.html
  DuggaSys/templates/diagram_dugga.js
Labels: Group-1-2022, Waiting for merge, Test Passed

#11716 G3 2022 w4 #11222
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/navheader.php
Labels: Group-3-2022

#11765 Removed margin and padding right to center the list
  Shared/css/style.css
Labels: Group-3-2022

#11770 Removed emoji from Diagram Dugga #11762
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Group-3-2022

#11783 G3 2022 w4 #11628
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  DuggaSys/contributionservice.php
Labels: Group-3-2022

#11793 Repaired broken string generation
  DuggaSys/contribution.js
Labels: Group-3-2022

#11805 Created a side menu that contains a table for account requests
  DuggaSys/contribution.js
  DuggaSys/contribution.php
  Shared/css/style.css
Labels: Group-3-2022, Waiting for merge

#11808 Made the commitDiv function better
  DuggaSys/contribution.js
  DuggaSys/contribution.php
Labels: Group-3-2022

#11824 G3 2022 w4 #11630
  DuggaSys/contribution.js
  DuggaSys/contributionservice.php
Labels: Group-3-2022, Waiting for merge

#11829 added alt tags too images
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-3-2022

#11801 The latest version of the red day list in contributions
  DuggaSys/contribution.js
Labels: Group-3-2022

#11781 Added darkmode for dialog boxes
  DuggaSys/courseed.php
  DuggaSys/sectioned.php
  Shared/css/blackTheme.css
  Shared/css/style.css
  Shared/loginbox.php
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#11709 CHanged the position of the textbox to static.
  Shared/css/codeviewer.css
Labels: Group-2-2022, Waiting for merge

#11719 G2 2022 w4 #11701
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11720 Fixed hideMaximizeAndResetButton() #11708
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11735 Padding change
  Shared/css/codeviewer.css
Labels: Group-2-2022, Waiting for merge

#11746 G2-2022-24-#11727
  Shared/css/style.css
Labels: Group-2-2022, Waiting for merge

#11768 G2 2022 w4 #11225
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-2-2022, Waiting for merge

#11774 Cleaned code in codeviewer.js
  DuggaSys/codeviewer.js
Labels: Group-2-2022, Waiting for merge

#11800 G2 2022 w4 #11512 v2
  Shared/SQL/init_db.sql
  sh/index.php
Labels: Group-2-2022, Waiting for merge

#11847 Add a option for tab
  DuggaSys/sectioned.js
Labels: Group-2-2022, Waiting for merge

#11855 Create tests on the lenasys website #11402
  install/SQL/testingCourseData.sql
  install/install.php
Labels: Group-2-2022, Waiting for merge

#11733 Added a toggle icon in main header
  DuggaSys/codeviewer.php
  DuggaSys/courseed.js
  DuggaSys/courseed.php
  DuggaSys/darkmodeToggle.js
  DuggaSys/sectioned.php
  Shared/css/blackTheme.css
  Shared/css/style.css
  Shared/css/whiteTheme.css
  Shared/navheader.php
Labels: Group-2-2022, Waiting for merge

#11853 Hide course dropdown menu until a year is selected
  DuggaSys/contribution.js
Labels: Group-3-2022

#11852 Fixed onclick function in contribution.php
  DuggaSys/contribution.js
Labels: Group-3-2022
