Repository HGustavs/LenaSYS, pull requests merged in 2023-04, with the labels that each got.

#12988 issue#12697
  backend-models/issue#12967.svg
  backend-models/issue#12967.txt
Labels: Group-2-2023

#12990 Added text 'login' so loginbutton is visible
  Shared/navheader.php
Labels: Group-3-2023

#12987 Prevents multiple clicks when toggling instructions.
  Shared/dugga.js
Labels: G1-2023, b21phiro

#12993 added model and text
  backend-models/duggaedservice.svg
  backend-models/duggaedservice.txt
Labels: Group-2-2023

#13009 Store and retrieve diagram from localstorage
  DuggaSys/diagram.js
Labels: G1-2023

#13012 Improve aggression, composition, optionality and cardinality at the end of lines. Issue #12954
  DuggaSys/diagram.js
Labels: G1-2023

#13002 G2 2023 v0 issue#12969
  backend-models/highscoreservice.svg
  backend-models/highscoreservice.txt
Labels: Group-2-2023

#13023 G2 2023 v0 issue #12959
  backend-models/accessedservice.svg
  backend-models/accessedservice.txt
Labels: Group-2-2023

#13031 G1 2023 v0 #12957
  DuggaSys/diagram.js
Labels: G1-2023

#13020 Colors not saved properly #13013
  DuggaSys/diagram.js
Labels: G1-2023

#13028 G1 2023 v0 #12999
  DuggaSys/diagram.php
Labels: G1-2023

#13019 issue#12885
  DuggaSys/diagram.php
Labels: G1-2023

#13022 G2 2023 v0 issue#12966
  backend-models/pushnotification.svg
  backend-models/pushnotification.txt
Labels: Group-2-2023

#13038 G2 2023 v0 #12970
  backend-models/Model filereceive service #12970.svg
  backend-models/Model filereceive service.txt
Labels: Group-2-2023

#13029 Diagram: Last two tooltips goes beyond bottom of the screen.
  DuggaSys/diagram.css
  DuggaSys/diagram.php
Labels: G1-2023

#13034 G2 2023 v0 issue#12960
  backend-models/codeviewerService2.php.svg
  backend-models/codeviewerservice.php
Labels: Group-2-2023

#13054 Darktheme inputs text color and login form background color
  Shared/css/blackTheme.css
  Shared/dugga.js
Labels: Group-3-2023

#13015 G2 2023 v0 issue#12962
  backend-models/sectionedservice.svg
  backend-models/sectionedservice.txt
Labels: Group-2-2023

#13076 G2 2023 v1 issue#13015
  backend-models/sectionedservice.svg
  backend-models/sectionedservice.txt
Labels: Group-2-2023

#13091 #12963 model contribution_loginbox_service
  backend-models/contribution_loginbox_service.svg
  backend-models/contribution_loginbox_service.txt
Labels: Group-2-2023

#13075 Removed inline styling and added padding. Issue #12884
  DuggaSys/templates/diagram_dugga.html
Labels: G1-2023

#13108 G1 2023 v1 #13051
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
Labels: G1-2023

#13107 g3-2023-v1-issue#13106
  DuggaSys/courseed.php
Labels: Group-3-2023

#13114 G1 2023 v1 #13052 Box outline hard to see in darkmode
  DuggaSys/diagram.js
Labels: G1-2023

#13104 try to switch $2 and $1
  Shared/markdown.js
Labels: Group-3-2023

#13119 Icon selection not saving right
  DuggaSys/diagram.js
Labels: G1-2023

#13123 added profileservice_microservices.txt
  backend-models/microservices/profileservice_microservices.txt
Labels: Group-2-2023

#13117 G2 2023 v1 issue#13095
  backend-models/microservices/fileedservice_microservices.txt
Labels: Group-2-2023

#13110 edit course with Github link
  DuggaSys/courseed.js
  DuggaSys/courseed.php
Labels: Group-3-2023

#13103 Triangle is now styled properly for darkmode/lightmode #13061
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: G1-2023

#13127 G2 2023 v1 issue#13094
  backend-models/contributionservice.svg
  backend-models/contributionservice.txt
Labels: Group-2-2023

#13111 Edit dugga now sorts correctly
  Shared/SortableTableLibrary/sortableTable.js
Labels: Group-3-2023

#13120 G2 2023 v1 issue#13100
  backend-models/microservices/showDuggaservice_microservices.txt
Labels: Group-2-2023

#13105 g3-2023-v1-issue#13073
  Shared/css/style.css
Labels: Group-3-2023

#13144 Changing properties on ER-Attribute does not work #13116
  DuggaSys/diagram.js
Labels: G1-2023

#13130 Add darkmode switch to diagram.php in right sidemenu. Issue#13067
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: G1-2023

#13131 #13099
  backend-models/microservices/Investigate potential microservices in sectionedservice.txt
Labels: Group-2-2023

#13145 G2 2023 v1 issue#13093v2
  backend-models/microservices/diagramservice_microservices.txt
Labels: Group-2-2023

#13128 Added contribution_loginbox_service_microservices.php.txt
  backend-models/microservices/contribution_loginbox_service_microservices.php.txt
Labels: Group-2-2023

#13154 You have to zoom in to see the diagram once diagram.php is loaded #13150
  DuggaSys/diagram.php
Labels: G1-2023

#13149 Icons not saved in options.
  DuggaSys/diagram.js
Labels: G1-2023

#13141 added codeviewerService_microservices.php
  backend-models/microservices/codeviewerService_microservices.txt
Labels: Group-2-2023

#13109 added resultedservice_microservices.txt
  backend-models/microservices/resultedservice_microservices.txt
Labels: Group-2-2023

#13153 Fixed so the input fields are correct.
  DuggaSys/sectioned.js
  Shared/css/blackTheme.css
Labels: Group-3-2023

#13159 Create Diagram.txt.txt
  backend-models/microservices/Diagram.txt
Labels: Group-2-2023

#13132 Added duggaed_microservice.txt
  backend-models/microservices/duggaedservice_microservice.txt
Labels: Group-2-2023

#13148 System messages are barely visible in darkmode #13126
  Shared/css/blackTheme.css
Labels: G1-2023

#13155 G1 2023 v1 #13083
  DuggaSys/diagram.js
Labels: G1-2023

#13161 State diagram start and stop #13050
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_UML_final_state.svg
  Shared/icons/diagram_UML_initial_state.svg
Labels: G1-2023

#13167 UML inheritance appears slightly above where it should #13124
  DuggaSys/diagram.js
Labels: G1-2023

#13164 G3 2023 v1 13001 12992 fetch data from a GitHub repository
  recursivetesting/FetchGithubRepo.js
  recursivetesting/FetchGithubRepo.php
Labels: Group-3-2023

#13173 G1 2023 v1 #13080
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/templates/diagram_dugga.js
Labels: G1-2023

#13174 Create highscoreservice.txt
  backend-models/microservices/highscoreservice.txt
Labels: Group-2-2023

#13112 G1 2023 v1 #13074 Add a button in the menu for placing statediagram states.
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2023

#13133 Move database backend from diagram.php #13102
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.js
  DuggaSys/diagramservice.php
Labels: G1-2023

#13178 Make sure localstorage for theme never is null #13177
  DuggaSys/darkmodeToggle.js
Labels: G1-2023

#13168 Refactor checkElementError() #13151
  DuggaSys/diagram.js
Labels: G1-2023

#13160 #13000 Model service distribution in dugga.js
  backend-models/service distribution in duggajs.svg
Labels: Group-2-2023

#13158 added accessedservice_microservices.txt
  backend-models/microservices/accessedservice_microservices.txt
Labels: Group-2-2023

#13169 Changed the color of the delete button for entities in darkmode
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: G1-2023

#13122 Fixed so you can add picture into the markdown file.
  Shared/markdown.js
Labels: Group-3-2023

#13187 G3 2023 v1 issue#13137
  DuggaSys/courseed.js
  DuggaSys/courseed.php
Labels: Group-3-2023

#13170 Fixed red background in add popup
  DuggaSys/sectioned.js
Labels: Group-3-2023

#13186 G3 2023 v1 issue#13163 popup blending in with background
  Shared/css/blackTheme.css
Labels: Group-3-2023

#13230 #12961 Model showDugga service fixed 2.0
  inputandoutput.txt
  modelShowDuggaService.svg
Labels: Group-2-2023

#13260 Overlapping elements when creating #13219
  DuggaSys/diagram.js
Labels: G1-2023

#13251 Change fill color of uml-icon triangle in dark-mode
  Shared/css/blackTheme.css
Labels: G1-2023

#13253 G2 2023 v2 issue #13058 logging to JSON files
  Shared/Documentation/AJAXService Log/Apara.pdf
  Shared/Documentation/AJAXService Log/LenaSYS dugga logging.drawio.png
  Shared/dugga.js
  Shared/logging.php
Labels: Group-2-2023

#13273 Made text white for ER-table when in darkmode, Issue#13257
  Shared/css/blackTheme.css
Labels: G1-2023

#13255 Added accessedservice.php_functionalrequirements.txt
  backend-models/functional-requirements/FRD_accessedservice.php.pdf
  backend-models/functional-requirements/accessedservice.php_functionalrequirements.txt
Labels: Group-2-2023

#13261 Created profileservice.php_functional-requirements
  backend-models/functional-requirements/FRD_profileservice.php.pdf
  backend-models/functional-requirements/profileservice.php_functional-requirement.txt
Labels: Group-2-2023

#13226 Added black arrow.
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: G1-2023

#13267 added documents
  backend-models/functional-requirements/FRD_MALL.pdf
  backend-models/functional-requirements/FRD_showDuggaservice.php.pdf
Labels: Group-2-2023

#13269 G3 2023 v2 13220 change GitHub button on course page
  DuggaSys/sectioned.js
Labels: Group-3-2023

#13296 Create FRD diagramservice.md
  backend-models/functional-requirements/FRD diagramservice.md
Labels: Group-2-2023

#13297 G1 2023 v2 #13203 cardinalities in dark-mode
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: G1-2023

#13298 G1 2023 v2 #13282
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
Labels: G1-2023

#13266 added an error catch
  DuggaSys/diagramservice.php
Labels: G1-2023

#13265 Change entity outline depending on colour and mode. #13211
  DuggaSys/diagram.js
Labels: G1-2023

#13229 Created folder for markdown-testfiles and created one for github-markdown
  markdown-testfiles/github-markdown.txt
  markdown-testfiles/lenasys-markdown.txt
Labels: Group-3-2023

#13228 Create OlderDuggaSYSLogs#13199.txt
  backend-models/OlderDuggaSYSLogs#13199.txt
Labels: Group-2-2023

#13303 G1 2023 v2 #13290
  DuggaSys/diagram.js
Labels: G1-2023

#13305 G1 2023 v2 #13204
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  exampleDiagrams/ErTestDiagram.json
Labels: G1-2023

#13288 Create FRD fileedservice.php.docx
  backend-models/functional-requirements/FRD fileedservice.php.docx
  backend-models/functional-requirements/Fileedservice.md
Labels: Group-2-2023

#13284 Add JSON files to the project #13264
  DuggaSys/JSON/ERDiagramMockup.json
  DuggaSys/JSON/IEDiagramMockup.json
  DuggaSys/JSON/UMLDiagramMockup.json
  DuggaSys/diagram.js
Labels: G1-2023

#13285 added FRD_codeviewerService
  backend-models/functional-requirements/codeviewerService.php.md
Labels: Group-2-2023

#13313 Fixed dropdown issue #13286
  Shared/css/style.css
Labels: Group-3-2023

#13256 G3-2023-v2-#13206-database-implementation-for-fetching-GitHub-repository-meta-data
  Shared/SQL/init_db.sql
  Shared/basic.php
Labels: Group-3-2023

#13272 G3 2023 v2 issue#13222
  DuggaSys/courseed.js
  DuggaSys/courseed.php
  DuggaSys/courseedservice.php
Labels: Group-3-2023

#13310 Create FRD accessedservice.md
  backend-models/functional-requirements/FRD accessedservice.md
Labels: Group-2-2023

#13312 Ruler is always darkmode issue #13280
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: G1-2023

#13307 G1 2023 v2 #13300
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
Labels: G1-2023

#13314 G3 2023 v2 issue#13254 - "Connect the fetchted data to the Database"
  recursivetesting/FetchGithubRepo.php
Labels: Group-3-2023

#13320 G1 2023 v2 #13308
  DuggaSys/diagram.js
Labels: G1-2023

#13246 Reverting while creating edge #13202
  DuggaSys/diagram.js
Labels: G1-2023

#13319 G2 2023 v2 Present the logs in a usable format #13277
  Shared/log.php
Labels: Group-2-2023

#13268 ContributionService Functional requirements #13235
  functionalRequirementsContributionservice[1590].txt
Labels: Group-2-2023

#13334 G1 2023 v2 #13321
  DuggaSys/diagram.css
Labels: G1-2023

#13336 G3 2023 v2 issue#13071
  recursivetesting/FetchGithubRepo.php
Labels: Group-3-2023

#13247 #13201 Study potential microservice documents and document all unique…
  backend-models/microservices/Study potential microservice documents and document all unique occurrences.txt
Labels: Group-2-2023

#13311 Create FRD showDuggaservice.md
  backend-models/functional-requirements/FRD showDuggaservice.md
Labels: Group-2-2023

#13271 G2 2023 v2 issue #13236 courseedservice.php functional requirements
  backend-models/functional-requirements/courseedservice_functionalrequirments.md
  backend-models/functional-requirements/courseedservice_functionalrequirments.txt
Labels: Group-2-2023

#13338 G1 2023 v2 #13215
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2023

#13349 G1 2023 v2 #13057 state diagram state
  DuggaSys/diagram.js
Labels: G1-2023

#13341 Arrow doesnt seem to fully connect #13315
  DuggaSys/diagram.js
Labels: G1-2023

#13302 created FR contribution_loginbox_service
  backend-models/functional-requirements/contribution_loginbox_service.php.md
Labels: Group-2-2023

#13318 Create highscoreservice.php.md
  backend-models/functional-requirements/highscoreservice.php.md
Labels: Group-2-2023

#13362 G2 2023 v2 issue#13331
  Shared/log.php
Labels: Group-2-2023

#13363 Fixed showDuggaservice
  backend-models/functional-requirements/FRD_showDuggaservice.md
  backend-models/functional-requirements/FRD_showDuggaservice.php.pdf
Labels: Group-2-2023

#13352 Lines between states should be possible to label #13081
  DuggaSys/diagram.js
Labels: G1-2023

#13350 FetchGitHubRepo now uses the URL dynamically sent in when creating/editing course
  DuggaSys/courseed.js
  recursivetesting/FetchGithubRepo.php
Labels: Group-3-2023

#13322 Made repo unique in database
  Shared/basic.php
Labels: Group-3-2023

#13360 g1-2023-v2-#13357 Add SD to togglePlacementType()
  DuggaSys/diagram.js
Labels: G1-2023

#13358 Created FRD resultedservice.md
  backend-models/functional-requirements/FRD_resultedservice.md
Labels: Group-2-2023

#13332 Deleted .git from regex
  DuggaSys/courseed.js
Labels: Group-3-2023

#13375 G1 2023 v2 #13283
  DuggaSys/diagram.js
Labels: G1-2023

#13355 G2 2023 v2 issue #13292
  backend-models/functional-requirements/FRD_profileservice.md
  backend-models/functional-requirements/FRD_profileservice.php.pdf
Labels: Group-2-2023

#13275 G3 2023 v2 issue#13196-issue#13326
  DuggaSys/showdoc.php
  Shared/markdown.js
Labels: Group-3-2023

#13354 G1 2023 V2 #13345
  DuggaSys/diagram.js
Labels: G1-2023

#13373 G3 2023 v2 13346 create a refresh button in the headernavbar to refresh all the metadata for all the files
  Shared/css/blackTheme.css
  Shared/css/style.css
  Shared/navheader.php
Labels: Group-3-2023

#13263 G1 2023 v2 #13221
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2023

#13377 G3 2023 v2 issue#13371
  Shared/css/blackTheme.css
Labels: Group-3-2023

#13380 G3 2023 v2 issue#13372 no hover indicator
  Shared/css/style.css
Labels: Group-3-2023

#13378 G3-2023-v2-issue#13223-GitHub-screen
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-3-2023

#13379 G3 2023 v2 issue#13179
  DuggaSys/sectioned.js
  DuggaSys/sectionedservice.php
  recursivetesting/FetchGithubRepo.js
Labels: Group-3-2023

#13384 G1 2023 v2 weekly merge
  DuggaSys/JSON/ERDiagramMockup.json
  DuggaSys/JSON/IEDiagramMockup.json
  DuggaSys/JSON/UMLDiagramMockup.json
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagramservice.php
  Shared/css/blackTheme.css
  Shared/css/style.css
  exampleDiagrams/ErTestDiagram.json
Labels: G1-2023

#13408 G1 2023 v3 #13166 refactor hiding of submenu-buttons
  DuggaSys/diagram.js
Labels: G1-2023

#13402 G1 2023 v3 #13389
  DuggaSys/diagram.css
  DuggaSys/diagram.php
Labels: G1-2023

#13409 Correct line type for state #13406
  DuggaSys/diagram.js
Labels: G1-2023

#13404 Fixed styling/positioning for options menu. Issue#13369
  DuggaSys/diagram.css
  DuggaSys/diagram.php
Labels: G1-2023

#13432 G1 2023 v3 #13390
  DuggaSys/diagram.js
Labels: G1-2023

#13433 Diagrams have now changed positions so they don't load in at different positions
  DuggaSys/JSON/ERDiagramMockup.json
  DuggaSys/JSON/IEDiagramMockup.json
  DuggaSys/JSON/UMLDiagramMockup.json
Labels: G1-2023

#13436 State entity outline should be fixed for lightmode #13366
  DuggaSys/diagram.js
Labels: G1-2023

#13444 G1 2023 v3 #13438 test-case generation button
  DuggaSys/diagram.php
Labels: G1-2023

#13435 Problems when moving multiple entities (with box selection) when some entities are overlapping #13353
  DuggaSys/diagram.js
Labels: G1-2023

#13430 G3 2023 V3 13414 Create column/table in SQLLite for commit/link
  Shared/basic.php
Labels: Group-3-2023

#13445 Added darkmode to profile page
  DuggaSys/profile.php
Labels: Group-3-2023

#13473 Overlapping with SD states is no longer possible. Issue#13381
  DuggaSys/diagram.js
Labels: G1-2023

#13449 G1 2023 v3 #13423
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2023

#13480 G1 2023 v3 #13442
  DuggaSys/diagram.js
Labels: G1-2023

#13469 G1 2023 v3 #13446
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2023

#13472 Fixed line that goes to "final state" goes too far.
  DuggaSys/diagram.js
Labels: G1-2023

#13476 G2 2023 v3 issue#13343 - Write tests for services in duggaedservice
  backend-models/service-tests/duggaedservice-tests.txt
Labels: Group-2-2023

#13474 added sorting to log.php G2 2023 v3 issue#13329
  Shared/log.php
Labels: Group-2-2023

#13479 G3 2023 v3 issue#13411
  DuggaSys/courseed.js
  recursivetesting/FetchGithubRepo.php
Labels: High priority, Group-3-2023

#13489 G1 2023 v3 #13470
  DuggaSys/diagram.js
Labels: G1-2023

#13477 G1 2023 v3 #13437
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2023

#13503 Change arrow to filled white #13461
  DuggaSys/diagram.js
  Shared/css/blackTheme.css
Labels: G1-2023

#13516 data_returned function in diagram.js is never used. #13493
  DuggaSys/diagram.js
Labels: G1-2023

#13514 New include button #13460
  DuggaSys/diagram.js
Labels: G1-2023
