Repository HGustavs/LenaSYS, pull requests merged in 2023-05, with the labels that each got.

#13630 G3 2023 v4 issue#13621
  DuggaSys/courseed.js
  DuggaSys/courseed.php
Labels: Group-3-2023

#13628 G3 2023 v4 issue#13573
  DuggaSys/fileedservice.php
  DuggaSys/filereceive_preview.php
  DuggaSys/showdoc.php
  backend-models/microservices/fileedservice_microservices.txt
Labels: Group-3-2023

#13636 G2 2023 v4 issue#13629
  DuggaSys/codeviewerService.php
Labels: Group-2-2023

#13634 Unable to place other elements within the superstate #13627
  DuggaSys/diagram.js
Labels: G1-2023

#13635 G3-2023-v4-13450-create-a-dropdown-list
  DuggaSys/sectioned.php
Labels: Group-3-2023

#13655 ZOOM buttons borders are visible in both light and darkmode* #13643
  DuggaSys/diagram.css
Labels: G1-2023

#13657 Remove consolelog #13657
  DuggaSys/diagram.js
Labels: G1-2023

#13659 Pop-out has the wrong icon for statediagram #13639
  DuggaSys/diagram.php
Labels: G1-2023

#13602 G2 2023 v4 issue#13330
  Shared/log.php
  Shared/logSearch.js
Labels: Group-2-2023

#13665 G1 2023 v4 #13649
  DuggaSys/diagram.js
Labels: G1-2023

#13664 G3 2023 v4 issue#13453
  DuggaSys/sectioned.js
Labels: Group-3-2023

#13666 Fix visual bug induced in #13643 #13663
  DuggaSys/diagram.css
Labels: G1-2023

#13625 G2 2023 v4 issue#13392
  backend-models/service-tests/codeviewerService-test.txt
Labels: Group-2-2023

#13670 dropdown and textfield incorrect in darkmode #13606
  Shared/css/blackTheme.css
Labels: G1-2023

#13594 G2 2023 v4 issue#13401
  backend-models/service-tests/showDuggaservice-test.txt
Labels: Group-2-2023

#13671 It is not possible to model recursion #13526
  DuggaSys/diagram.js
Labels: G1-2023

#13669 changed diagram.js so that arrow labels are printed
  DuggaSys/diagram.js
Labels: G1-2023

#13674 G3 2023 v4 issue#13549
  DuggaSys/sectioned.js
  DuggaSys/sectionedservice.php
Labels: Group-3-2023

#13631 G2 2023 v4 issue #13532 Created test API
  Shared/sessions.php
  Shared/test.php
Labels: Group-2-2023

#13696 Create sectionedservice-test.txt
  backend-models/service-tests/sectionedservice-test.txt
Labels: Group-2-2023

#13685 G1 2023 v4 #13640
  DuggaSys/diagram.js
Labels: G1-2023

#13706 G3 2023 v5 issue#13677
  Shared/css/blackTheme.css
Labels: Group-3-2023

#13712 Toggle load button as well as dropdown #13680
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13699 Added missing content to codeviewerService.md
  backend-models/functional-requirements/FRD_codeviewerService.md
Labels: Group-2-2023

#13715 Documentation for mdown(event) #13705
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13686 Tooltip partially hidden #13641
  DuggaSys/diagram.css
Labels: Testing, G1-2023

#13716 G1 2023 v5 #13711
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13718 G1 2023 v5 #13682
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13726 G2 2023 v5 issue#13434 - Transition log.php to a microservice architecture
  Shared/log.js
  backend-models/service documentation/Communication used in the old style service files.pdf
Labels: Group-2-2023

#13719 Fix keybinding functionality for UML Initial State #13701
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13739 G1 2023 v5 #13722
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13738 G2 2023 v5 issue#13653 - Add missing content to FRD_highscoreservice.md
  backend-models/functional-requirements/FRD_highscoreservice.md
Labels: Group-2-2023

#13720 Fix keybinding functionality for UML-final state #13702
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13762 Continue work with recursive state-arrows #13691
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13721 G1 2023 v5 #13687
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13760 G1 2023 v5 #13736
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13761 Added a file and made it an option in the dropdown #13714
  DuggaSys/JSON/EMPTYDiagramMockup.json
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13766 Clean function "setCursorStyles"
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13745 Added missing content and smaller changes to FRD_resultedservice.md
  backend-models/functional-requirements/FRD_resultedservice.md
Labels: Group-2-2023

#13752 Create profileservice-tests.txt.txt
  backend-models/service-tests/profileservice-tests.txt.txt
Labels: Group-2-2023

#13725 G2 2023 v5 issue#13494
  Shared/log.js
  Shared/log.php
Labels: Group-2-2023

#13763 fixed the output of diagram.js for state line labels.
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13740 G2 2023 v5 issue#13400
  backend-models/service-tests/sectionedservice-test.txt
Labels: Group-2-2023

#13775 Added blue color to option bar and changed initial state and final state to black color. #13688
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13784 Added passed/failed text
  Shared/test.php
Labels: Group-2-2023

#13787 Remove unused code in diagram.php #13782
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13792 Removed unused code #13742
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13773 Create the functionality for sequence lifeline #13684
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13794 Replace variable names a and b for function sortElementAssociations #13786
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13795 Variables should use local scope #13783
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13776 G1 2023 v5 #13734
  DuggaSys/diagram.php
  DuggaSys/modules/search.module.js
Labels: Testing, G1-2023

#13780 Fixed so that lines save properly
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13772 G1 2023 v5 #13737
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13799 G1 2023 v5 #13769
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13812 G3 2023 v5 issue#13732
  DuggaSys/fileed.js
  DuggaSys/fileed.php
  DuggaSys/fileedservice.php
  Shared/css/style.css
Labels: Group-3-2023

#13813 G1 2023 v5 #13798
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13807 G2 2023 v5 issue#13789 - Change duggaedservice-tests.txt to MD and add expected output
  backend-models/service-tests/duggaedservice-test.md
Labels: Group-2-2023

#13815 Updated class diagram ProfileService.svg #13747
  backend-models/class-diagrams/profileservice.svg
Labels: Group-2-2023

#13717 added test proposals to courseedservice
  backend-models/functional-requirements/FRD_courseedservice_functionalrequirments.md
Labels: Group-2-2023

#13622 fileedservice-test.txt file for Issue#13398
  backend-models/service-tests/fileedservice-tests.txt
Labels: Group-2-2023

#13778 G2 2023 v5 issue#13396 Design test for courseedservice.php
  backend-models/service-tests/courseedservice-tests.txt
Labels: Group-2-2023

#13809 G1 2023 v5 #13735
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13823 Added the option "name" for a test
  Shared/test.php
Labels: Group-2-2023

#13827 Test API can now run multple tests at the same time
  Shared/test.php
Labels: Group-2-2023

#13844 G1 2023 v5 #12889
  DuggaSys/templates/diagram_dugga.html
Labels: Testing, G1-2023

#13843 G1 2023 v5 #12883
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13830 G2 2023 v5 issue#13749 Update class diagram codeviewerService
  backend-models/class-diagrams/codeviewerService.svg
  backend-models/codeviewerService2.php.svg
Labels: Group-2-2023

#13828 Fix magic-number TODO #13724
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13842 G2 2023 v5 issue#13820 - Change fileedservice-tests.txt to MD and add expected output
  backend-models/service-tests/fileedservice-test.md
  backend-models/service-tests/fileedservice-tests.txt
Labels: Group-2-2023

#13876 created a new file called fetchDiagramInfo.js and added an assets fo…
  DuggaSys/assets/js/fetchDiagramInfo.js
Labels: Testing, G1-2023

#13824 Activation element for sequence diagrams #13728
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13882 Superstate should be scalable height-wise
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13797 G3 2023 v5 issue#13668
  DuggaSys/courseed.js
  DuggaSys/sectioned.js
  Shared/navheader.php
  recursivetesting/FetchGithubRepo.php
  recursivetesting/getLatestCommit.php
Labels: Group-3-2023

#13888 improved recursive sd lines
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13805 Sqlite metadatadb is now deleted and recreated when running install script
  install/install.php
Labels: Group-3-2023

#13841 G2 2023 v5 issue#13393
  backend-models/service-tests/accessedservice-test.md
  backend-models/service-tests/accessedservice-test.txt
Labels: Group-2-2023

#13892 G1 2023 v5 #13810
  DuggaSys/diagram.js
Labels: G1-2023

#13864 ER to UML, UML to ER options panel dropdown issue #12694
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13887 Diagramservice throws a 500 HTTP error #13861
  DuggaSys/diagramservice.php
Labels: Testing, G1-2023

#13866 added a button for sequance option loop
  DuggaSys/diagram.php
  Shared/icons/diagram_optionLoop.svg
Labels: Testing, G1-2023

#13867 G1 2023 v5 #13796
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13829 Prevent label and cardinalities on IE lines #12860
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13895 Text without whitebackground remains black in darkmode #13869
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13894 New version of class-diagram accessedservice.svg
  backend-models/accessedservice.svg
  backend-models/class-diagrams/accessedservice.svg
Labels: Group-2-2023

#13886 G2 2023 v5 issue#13744 Update class diagram Fileed.svg to include input data in methods
  backend-models/Fileed.svg
  backend-models/class-diagrams/fileedservice.svg
  backend-models/service-tests/fileedservice-test.md
Labels: Group-2-2023

#13898 G3 2023 v5 issue#13821
  DuggaSys/fileed.js
  DuggaSys/fileedservice.php
Labels: Group-3-2023

#13885 Identify and edit service files to support test API issue#13679
  DuggaSys/courseedservice.php
  DuggaSys/resultedservice.php
  DuggaSys/sectionedservice.php
  DuggaSys/showDuggaservice.php
Labels: Group-2-2023

#13903 Updated the class diagram sectionedservice
  backend-models/class-diagrams/sectionedservice.svg
  backend-models/sectionedservice.svg
Labels: Group-2-2023

#13915 #13791
  backend-models/service-tests/showDuggaservice-test.md
Labels: Group-2-2023

#13918 G2 2023 v6 issue#13910 Change sectionedservice-test.txt to MD and add expected output
  backend-models/service-tests/sectionedservice-test.md
  backend-models/service-tests/sectionedservice-test.txt
Labels: Group-2-2023

#13912 g1 2023 v6 #13906
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13924 G2 2023 v6 issue#13908
  backend-models/service-tests/courseedservice-test.md
Labels: Group-2-2023

#13930 G2 2023 v6 issue#13920 Updated Test API to be able to execute db querys
  Shared/Documentation/Test API/Guide on how to use Test API.md
  Shared/Documentation/Test API/Guide on how to use Test API.pdf
  Shared/test.php
Labels: Group-2-2023

#13940 Centered the cursor for ghost elements
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13929 Added pop-out for sequence and added all the buttons
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13926 Created tests for resultedservice.php in md
  backend-models/service-tests/resultedservice-test.md
Labels: Group-2-2023

#13921 UML Super State darkmode issue #13905
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13941 G1 2023 v6 #13689
  DuggaSys/diagram.js
Labels: G1-2023

#13957 G3 2023 v6 issue#13943
  DuggaSys/gitcommitService.php
Labels: Group-3-2023

#13942 G3 2023 v6 issue#13890
  DuggaSys/courseed.js
  DuggaSys/gitcommitService.php
Labels: Group-3-2023

#13949 Add functionality for sequence loop or alternative #13914
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2023

#13954 created a save button
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_save_icon.svg
Labels: Testing, G1-2023

#13983 Fixed major merge-conflict, retracted some changes.
  DuggaSys/diagram.php
Labels: Potentially Fixed, G1-2023, !Assignable

#13969 Ctrl+z when placing elements #13965
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13982 0-1, 1, 1! and 1-M breaking lines #13471
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13981 G2 2023 v6 issue#13638
  DuggaSys/codeviewer.js
Labels: Group-2-2023

#13971 Not possible to rename actors and objects #13958
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13992 Fix function linetest() #13785 fix 3
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13993 G1 2023 v6 #13991
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13994 Linked the save function to the save button
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13996 [NOTE: This is the PR for "v6-fix-3"] State without attributes displays incorrectly
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13970 Update class diagram with input data in methods#13757
  backend-models/class-diagrams/resultedservice.svg
  backend-models/resultedservice resulted and resulted_dugga.svg
Labels: Group-2-2023

#14001 Label position recursive edge #13966
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14005 Create a "load-save" button. #13986
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/icons/diagram_load_icon.svg
Labels: Testing, G1-2023

#14000 [NOTE: g1-2023-v6-fix-3 version] added the tooltip-class for pop-outs
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#13948 Add functionality for all entities to elementHasLines #13865
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14011 Remove button for sequence object #13978
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#14017 renamed function in diagram.js to loadDiagramFromLocalStorage. made …
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13973 G1 2023 v6 #13945
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14006 Changing icons for IE-entities throws TypeError #13988
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14016 G2 2023 v6 issue#13617
  backend-models/service-tests/motherTest.php
  backend-models/service-tests/motherTestJSON.json
Labels: Group-2-2023

#14041 g1-2023-v6-fix-3-#14022 changed x and y postion of label
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14034 getElementLines now works for UML, ER, IE and SD
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14015 G1 2023 v6 fix 3 #14007
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14029 G1-2023-v6-fix-3-#14019 Typo fix
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13998 Add functionality for sequence loop or alternative #13914 new
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#13990 G2 2023 v6 issue#13790
  backend-models/service-tests/codeviewerService-test.md
Labels: Group-2-2023

#14046 Allow display of saved diagram when loaded #14045
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#14023 G3 2023 v6 issue#13549
  DuggaSys/sectioned.js
  DuggaSys/sectionedservice.php
Labels: Group-3-2023

#14043 Clipping outlines for superstate and sequence activation #14038
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14031 G3 2023 v6 issue#13897
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/SQL/init_db.sql
Labels: Group-3-2023

#14053 G3 2023 v6 issue#13939
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Group-3-2023

#14060 G2 2023 v6
  DuggaSys/codeviewer.js
  Shared/Documentation/Test API/Guide on how to use Test API.md
  Shared/Documentation/Test API/Guide on how to use Test API.pdf
  Shared/test.php
  backend-models/README.md
  backend-models/class-diagrams/courseedservice.svg
  backend-models/class-diagrams/resultedservice.svg
  backend-models/class-diagrams/sectionedservice.svg
  backend-models/courseedService2.php.svg
  backend-models/microservices/README.md
  backend-models/microservices/duggaSys services/Database_related_micro_services.md
  backend-models/microservices/duggaSys services/Potetial_micro_services.md
  backend-models/resultedservice resulted and resulted_dugga.svg
  backend-models/sectionedservice.svg
  backend-models/service-tests/README.md
  backend-models/service-tests/accessedservice-test.txt
  backend-models/service-tests/codeviewerService-test.md
  backend-models/service-tests/courseedservice-test.md
  backend-models/service-tests/courseedservice-tests.txt
  backend-models/service-tests/motherTest.php
  backend-models/service-tests/motherTestJSON.json
  backend-models/service-tests/resultedservice-test.md
  backend-models/service-tests/sectionedservice-test.md
  backend-models/service-tests/sectionedservice-test.txt
  backend-models/service-tests/showDuggaservice-test.md
Labels: Group-2-2023

#13972 G3 2023 v5 issue#13771
  DuggaSys/fileed.js
  Shared/css/blackTheme.css
  Shared/css/style.css
Labels: Group-3-2023

#14056 G3 2023 v5 #13456
  DuggaSys/sectioned.js
  Shared/basic.php
Labels: Group-3-2023

#14073 Not all toggable-buttons have indication that they are active #14027
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#14064 G1 2023 v7 #14042
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: Testing, G1-2023

#14076 G3 2023 v7 issue#13549
  DuggaSys/sectioned.js
  DuggaSys/sectionedservice.php
Labels: Question To Customer, Group-3-2023

#14074 commented out function setPreviewValue in diagram.js
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14085 Name of lifeline elements #14059
  DuggaSys/diagram.js
Labels: Testing, G1-2023

#14105 Added functionality for "Load"-button
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  Shared/css/blackTheme.css
Labels: Testing, G1-2023

#14096 G3 2023 v7 issue#14065
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Group-3-2023

#14083 New expected outputs from tests profileservice.php#13909
  backend-models/service-tests/profileservice-tests.md
Labels: Group-2-2023

#14124 G3 2023 v7 issue#13959
  Shared/css/blackTheme.css
  Shared/css/style.css
  Shared/icons/gitrefresh.svg
  Shared/navheader.php
Labels: Group-3-2023

#14098 G3 2023 v7 issue#13987
  DuggaSys/sectioned.js
Labels: Group-3-2023

#14127 Added column for separate filename in lenasys for gitFiles
  DuggaSys/sectioned.js
  Shared/SQL/init_db.sql
  Shared/basic.php
  recursivetesting/FetchGithubRepo.php
Labels: Group-3-2023

#14130 G3 2023 v7 issue#14126
  DuggaSys/sectionedservice.php
Labels: Group-3-2023

#14107 G3 2023 v6 issue#13999
  DuggaSys/gitcommitService.php
  DuggaSys/sectioned.js
Labels: Group-3-2023

#14138 G2 2023 v7 issue#14035
  backend-models/functional-requirements/FRD_profileservice.md
Labels: Group-2-2023

#14125 G3 2023 v7 issue#14021
  DuggaSys/codeviewer.js
  DuggaSys/codeviewer.php
  Shared/navheader.php
Labels: Group-3-2023
