Repository HGustavs/LenaSYS, pull requests merged in 2024-05, with the labels that each got.

#15240 G1 2024 v4 #14787
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram/camera.js
  DuggaSys/diagram/classes/point.js
  DuggaSys/diagram/classes/stateChange.js
  DuggaSys/diagram/classes/stateChangeFactory.js
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/draw/boxSelect.js
  DuggaSys/diagram/draw/element.js
  DuggaSys/diagram/draw/line.js
  DuggaSys/diagram/draw/node.js
  DuggaSys/diagram/draw/options.js
  DuggaSys/diagram/draw/ruler.js
  DuggaSys/diagram/draw/selection.js
  DuggaSys/diagram/draw/update.js
  DuggaSys/diagram/errorHandling.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/globals.js
  DuggaSys/diagram/helper.js
  DuggaSys/diagram/helpers/boxSelect.js
  DuggaSys/diagram/helpers/context.js
  DuggaSys/diagram/helpers/element.js
  DuggaSys/diagram/helpers/line.js
  DuggaSys/diagram/helpers/mouse.js
  DuggaSys/diagram/helpers/mouseMode.js
  DuggaSys/diagram/helpers/rect.js
  DuggaSys/diagram/message.js
  DuggaSys/diagram/theme.js
  DuggaSys/diagram/toggle.js
  DuggaSys/diagram/zoom.js
Labels: G1-2024

#15300 G1 2024 v5 #15269
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram/classes/point.js
  DuggaSys/diagram/classes/rect.js
  DuggaSys/diagram/draw/boxSelect.js
  DuggaSys/diagram/draw/ruler.js
  DuggaSys/diagram/draw/update.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/helpers/boxSelect.js
  DuggaSys/diagram/helpers/mouse.js
  DuggaSys/diagram/helpers/rect.js
Labels: G1-2024

#15326 Change how the text/value of 'attribute' and 'function' properties of elements are drawn out on diagram #15322
  DuggaSys/diagram.js
Labels: G1-2024

#15333 Broke out error handling in addLine #15311
  DuggaSys/diagram.js
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/helpers/line.js
Labels: G1-2024

#15295 preventDefault() added to MOVING_OBJECT
  DuggaSys/diagram.js
Labels: G1-2024

#15401 Remove object with ID BA4BCD #15263
  DuggaSys/JSON/ERDiagramMockup.json
Labels: G1-2024

#15248 Added icons, label and dashed line to SE #14819
  DuggaSys/diagram/draw/line.js
  DuggaSys/diagram/draw/options.js
  DuggaSys/diagram/events/mouse.js
Labels: G1-2024

#15384 Removed break for non attributes #15383
  DuggaSys/diagram/draw/options.js
Labels: G1-2024

#15447 Created the test - issue#15350
  DuggaSys/tests/microservices/resultedService/getUserAnswer_ms_test.php
Labels: Group-2-2024

#15429 Fixed move and resize jump. (#14623)
  DuggaSys/diagram.js
Labels: G1-2024

#15460 icon change on cycling #14375
  DuggaSys/diagram.js
  DuggaSys/diagram/helpers/mouseMode.js
  DuggaSys/diagram/toggle.js
Labels: G1-2024

#15449 G2 2024 v5 issue#15304
  DuggaSys/microservices/courseedService/changeActiveCourseVersion_courseed_ms.php
  DuggaSys/microservices/courseedService/createCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createMOTD_ms.php
  DuggaSys/microservices/courseedService/createNewCourse_ms.php
  DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
  DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
  DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
  DuggaSys/microservices/courseedService/updateCourse_ms.php
  Shared/dugga.js
Labels: Group-2-2024

#15456 Created test for createDugga_ms.php issue#15199
  DuggaSys/tests/microservices/duggaedService/createDugga_ms_test.php
Labels: Group-2-2024

#15445 Continued fixing the undo function #15243
  DuggaSys/diagram.js
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/globals.js
Labels: G1-2024

#15477 Moved defaults #15441
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/defaults.js
Labels: G1-2024

#15506 G1 2204 v5 #15478
  DuggaSys/diagram.js
  DuggaSys/diagram/camera.js
  DuggaSys/diagram/classes/rect.js
  DuggaSys/diagram/classes/stateChange.js
  DuggaSys/diagram/classes/stateChangeFactory.js
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/defaults.js
  DuggaSys/diagram/draw/element.js
  DuggaSys/diagram/draw/line.js
  DuggaSys/diagram/draw/node.js
  DuggaSys/diagram/draw/options.js
  DuggaSys/diagram/draw/ruler.js
  DuggaSys/diagram/draw/selection.js
  DuggaSys/diagram/draw/update.js
  DuggaSys/diagram/errorHandling.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/globals.js
  DuggaSys/diagram/helper.js
  DuggaSys/diagram/helpers/boxSelect.js
  DuggaSys/diagram/helpers/element.js
  DuggaSys/diagram/helpers/line.js
  DuggaSys/diagram/helpers/mouse.js
  DuggaSys/diagram/helpers/mouseMode.js
  DuggaSys/diagram/message.js
  DuggaSys/diagram/toggle.js
  DuggaSys/diagram/zoom.js
Labels: G1-2024

#15505 G2 204 v6 issue#15499
  DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php
  DuggaSys/microservices/sectionedService/createListEntry_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Labels: Group-2-2024

#15516 Created test for deleteDugga_ms.php issue#15201
  DuggaSys/tests/microservices/duggaedService/deleteDugga_ms_test.php
Labels: Group-2-2024

#15517 G2 2024 v6 issue#14198
  DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
  Shared/dugga.js
Labels: Group-2-2024

#15528 Created test for createDuggaVariant_ms.php issue#15197
  DuggaSys/tests/microservices/duggaedService/createDuggaVariant_ms_test.php
Labels: Group-2-2024

#15533 Fixed overlapping check #15508
  DuggaSys/diagram.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/helpers/element.js
  DuggaSys/diagram/helpers/mouse.js
Labels: G1-2024

#15541 G2 Merge #15433
  DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
Labels: Group-2-2024

#15549 G2 2024 v6 issue#15200
  DuggaSys/tests/microservices/duggaedService/deleteDuggaVariant_ms_test.php
Labels: Group-2-2024

#15556 background overlap fix #15555
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/helper.js
Labels: G1-2024

#15548 Corrected IE height #15539
  DuggaSys/diagram/draw/element.js
Labels: G1-2024

#15482 #15081 fix, when changing an UML/SD/IE element to an ER entity the height doesnt default to zero anymore.
  DuggaSys/diagram/draw/element.js
  DuggaSys/diagram/globals.js
Labels: G1-2024

#15551 #14986 actor and object alignment
  DuggaSys/diagram/draw/element.js
Labels: G1-2024

#15579 G2 2024 v6 issue#15194
  DuggaSys/tests/microservices/courseedService/updateCourseVersion_ms_test.php
Labels: Group-2-2024

#15575 finished undo #15498
  DuggaSys/diagram.js
  DuggaSys/diagram/draw/options.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/helper.js
Labels: G1-2024

#15592 G2 Merge issue#15378
  DuggaSys/tests/microservices/courseedService/copyCourseVersion_ms_test.php
Labels: Group-2-2024

#15583 migrate showDuggaService to microservices by changing the service redirections in dugga.js
  Shared/dugga.js
Labels: Group-2-2024

#15469 G2 2024 v5 issue#15387
  DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php
  DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php
  DuggaSys/microservices/codeviewerService/editCodeExample_ms.php
  DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php
  DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php
  Shared/dugga.js
Labels: Group-2-2024

#15599 G2 2024 v6 issue#15190
  DuggaSys/microservices/courseedService/createMOTD_ms.php
  DuggaSys/tests/microservices/courseedService/createMOTD_ms_test.php
Labels: Group-2-2024

#15615 G2 2024 v6 issue#15611
  DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
  DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
Labels: Group-2-2024

#15610 G2 Merge issue#15189
  DuggaSys/microservices/courseedService/createCourseVersion_ms.php
  DuggaSys/tests/microservices/courseedService/createCourseVersion_ms_test.php
Labels: Group-2-2024

#15598 G2 2024 v6 issue#15191
  DuggaSys/tests/microservices/courseedService/createNewCourse_ms_test.php
Labels: Group-2-2024

#15630 G2 2024 v6 issue#15613
  DuggaSys/microservices/courseedService/createMOTD_ms.php
  DuggaSys/microservices/courseedService/createNewCourse_ms.php
  DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
  Shared/dugga.js
Labels: Group-2-2024

#15624 Changed the identation and removed blank spaces for issue#15593
  DuggaSys/assets/js/fetchDiagramInfo.js
Labels: G1-2024

#15577 fixed padlocks #15267
  DuggaSys/diagram.css
  DuggaSys/diagram/zoom.js
  Shared/css/blackTheme.css
  Shared/icons/pad_lock.svg
Labels: G1-2024

#15631 Created test for updateFileLink_ms.php issue#15207
  DuggaSys/tests/microservices/fileedService/updateFileLink_ms_test.php
Labels: Group-2-2024

#15641 G2 2024 v6 issue#15638
  DuggaSys/microservices/courseedService/getCourseed_ms.php
Labels: Group-2-2024

#15643 G2 2024 v6 #15193
  DuggaSys/tests/microservices/courseedService/retrieveCourseedService_ms_test.php
Labels: Group-2-2024

#15596 G1 2024 v6 #15553
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagram/constants.js
Labels: G1-2024

#15655 G2 2024 v6 issue#15184
  DuggaSys/microservices/sharedMicroservices/getUid_ms.php
  DuggaSys/tests/microservices/codeviewerService/editBoxTitle_ms_test.php
Labels: Group-2-2024

#15597 Create new test for the microservice deleteFileLink_ms.php #15206
  DuggaSys/microservices/fileedService/deleteFileLink_ms.php
  DuggaSys/tests/microservices/duggaedService/deleteDugga_ms_test.php
  DuggaSys/tests/microservices/fileedService/deleteFileLink_ms_test.php
Labels: G2 Waiting for Test

#15709 create service getAccessedService_ms.php
  DuggaSys/microservices/accessedService/getAccessedService_ms.php
Labels: Group-2-2024

#15723 Created ms retrieveAllCourseVersions_ms.php issue#15652
  DuggaSys/microservices/sectionedService/retrieveAllCourseVersions_ms.php
Labels: Group-2-2024

#15673 G2 2024 v6 issue#15188
  DuggaSys/tests/microservices/courseedService/changeActiveCourseVersion_courseed_ms_test.php
Labels: Group-2-2024

#15535 Migrated the microservices that are done for the sectioned page.
  DuggaSys/microservices/sectionedService/changeActiveCourseVersion_sectioned_ms.php
  DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php
  DuggaSys/microservices/sectionedService/getCourseVersions_ms.php
  DuggaSys/microservices/sectionedService/getDeletedListEntries_ms.php
  DuggaSys/microservices/sectionedService/getGroupValues_ms.php
  DuggaSys/microservices/sectionedService/getUserDuggaFeedback_ms.php
  DuggaSys/microservices/sectionedService/removeListEntries_ms.php
  DuggaSys/microservices/sectionedService/reorderListEntries_ms.php
  DuggaSys/microservices/sectionedService/setVisibleListentries_ms.php
  DuggaSys/microservices/sectionedService/updateCourseVersion_sectioned_ms.php
  DuggaSys/microservices/sectionedService/updateListEntriesTabs_ms.php
  DuggaSys/microservices/sectionedService/updateListEntries_ms.php
  DuggaSys/microservices/sectionedService/updateQuizDeadline_ms.php
  DuggaSys/sectioned.js
  Shared/dugga.js
Labels: Group-2-2024

#15536 Student Feedback Question illigal symbols.
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: g3-2024

#15742 G2 2024 v6 issue#15696
  DuggaSys/microservices/sectionedService/setVisibleListentries_ms.php
  DuggaSys/tests/microservices/sectionedService/setVisibleListentries_ms_test.php
Labels: Group-2-2024

#15735 G2 2024 v6 issue#15684
  DuggaSys/tests/microservices/sectionedService/createListEntry_ms_test.php
Labels: Group-2-2024

#15754 G2 2024 v6 issue#15753 fix getCourseVersions_ms.php
  DuggaSys/microservices/sectionedService/getCourseVersions_ms.php
Labels: Group-2-2024

#15732 inital/final state resizing #14828
  DuggaSys/diagram.js
  DuggaSys/diagram/draw/node.js
Labels: G1-2024

#15672 G1 2024 v6 #14922 2
  DuggaSys/diagram/theme.js
Labels: G1-2024

#15858 G2 merge issue#15857
  DuggaSys/microservices/sectionedService/getDeletedListEntries_ms.php
Labels: Group-2-2024

#15519 G1 2024 v6 #14235
  DuggaSys/diagram.js
  DuggaSys/diagram/camera.js
Labels: G1-2024

#15855 Wrote jsdocs for rect
  DuggaSys/diagram/classes/rect.js
Labels: G1-2024

#15841 JSDoc update #15736
  DuggaSys/diagram.js
  DuggaSys/diagram/classes/stateChange.js
  DuggaSys/diagram/classes/stateChangeFactory.js
Labels: G1-2024

#15836 cleaned up history functionality #15770
  DuggaSys/diagram.js
  DuggaSys/diagram/classes/stateChange.js
  DuggaSys/diagram/classes/stateChangeFactory.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/helper.js
Labels: G1-2024

#15898 G2 2024 v7 issue#15891
  DuggaSys/microservices/sectionedService/retrieveAllCourseVersions_ms.php
  DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Labels: Group-2-2024

#15888 Balanced the size for the different elements for issue #15084, new branch/PR
  DuggaSys/diagram/classes/element.js
  DuggaSys/diagram/defaults.js
Labels: G1-2024

#15854 fixed "You don't have anything to save." appearing when reloading/leaving the site when you havent added anything to the diagram #15527
  DuggaSys/diagram.js
Labels: G1-2024

#15905 G2 2024 v7 issue#15856
  DuggaSys/duggaedservice.php
  DuggaSys/microservices/duggaedService/retrieveDuggaedService_ms.php
  DuggaSys/tests/duggaedService_test.php
  DuggaSys/tests/microservices/duggaedService/createDuggaVariant_ms_test.php
  DuggaSys/tests/microservices/duggaedService/deleteDuggaVariant_ms_test.php
  DuggaSys/tests/microservices/duggaedService/deleteDugga_ms_test.php
  DuggaSys/tests/microservices/duggaedService/updateDuggaVariant_ms_test.php
Labels: Group-2-2024

#15906 G2 2024 v7 issue#15690
  DuggaSys/tests/microservices/sectionedService/getGroupValues_ms_test.php
Labels: Group-2-2024

#15866 G2 2024 v6 issue#15694
  DuggaSys/tests/microservices/sectionedService/reorderListEntries_ms_test.php
Labels: Group-2-2024

#15918 G2 2024 v7 issue#15834
  DuggaSys/tests/microservices/sectionedService/Microservices_test_documentation.md
Labels: Group-2-2024

#15945 Updated documentation #15779
  DuggaSys/diagram.js
  DuggaSys/diagram/classes/stateChangeFactory.js
Labels: G1-2024

#15926 Created test for updateActiveUsers_ms.php issue#15363
  DuggaSys/tests/microservices/showDuggaService/updateActiveUsers_ms_test.php
Labels: Group-2-2024

#15954 g2 2024 v7 issue#15952
  DuggaSys/tests/microservices/courseedService/updateActiveCourseVersion_courseed_ms_test.php
Labels: Group-2-2024

#15932 correct parameters are sent in the ajax request for the kind SECTION
  Shared/dugga.js
Labels: Group-2-2024

#15963 G2 2024 v7 issue#15828
  DuggaSys/tests/microservices/courseedService/courseedService_documentation.md
Labels: Group-2-2024

#15981 G2 2024 v7 issue #15961
  Shared/dugga.js
Labels: Group-2-2024

#15985 fix for #15617
  DuggaSys/diagram/theme.js
Labels: G1-2024

#15940 G1 2024 v7 #15797
  DuggaSys/diagram.js
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/draw/options.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/globals.js
  DuggaSys/diagram/helper.js
  DuggaSys/diagram/helpers/element.js
  DuggaSys/diagram/helpers/mouse.js
Labels: G1-2024

#15946 G2 Merge issue#15941
  DuggaSys/tests/microservices/sectionedService/readCourseVersions_ms_test.php
Labels: Group-2-2024

#15949 Made elements smaller for issue #15907
  DuggaSys/diagram/classes/element.js
  DuggaSys/diagram/defaults.js
Labels: G1-2024

#15939 Create Microservices_docuementation.md
  DuggaSys/tests/microservices/resultedService/Microservices_docuementation.md
Labels: Group-2-2024

#15912 G2 2024 v7 #15829
  DuggaSys/tests/microservices/duggaedService/duggaedService_documentation.md
Labels: Group-2-2024

#15897 G2 2024 v7 #15832
  DuggaSys/tests/microservices/profileService/profileService_documentation.md
Labels: Group-2-2024

#15892 G2 2024 v7 #15825
  DuggaSys/tests/microservices/Microservices_tests_documentation.md
  DuggaSys/tests/microservices/accessedService/accessedService_documentation.md
Labels: Group-2-2024

#16009 G2 2024 v7 issue#15987
  DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createMOTD_ms.php
  DuggaSys/microservices/courseedService/createNewCourse_ms.php
  DuggaSys/microservices/courseedService/getCourseed_ms.php
  DuggaSys/microservices/courseedService/specialUpdate_ms.php
  DuggaSys/microservices/courseedService/updateActiveCourseVersion_courseed_ms.php
  DuggaSys/microservices/courseedService/updateCourse_ms.php
Labels: Group-2-2024

#15935 documentation for element.js
  DuggaSys/diagram/classes/element.js
Labels: G1-2024

#16064 g2-2024-v7-issue#16060
  DuggaSys/microservices/duggaedService/updateDugga_ms.php
Labels: Group-2-2024

#16078 G2 2024 v7 issue#15695
  DuggaSys/tests/microservices/sectionedService/retrieveSectionedService_ms_test.php
Labels: Group-2-2024

#16089 G2 2024 v7 issue#15195
  DuggaSys/tests/microservices/courseedService/updateCourse_ms_test.php
Labels: Group-2-2024

#16040 G1 2024 v7 #15993
  DuggaSys/diagram/classes/rect.js
  DuggaSys/diagram/draw/boxSelect.js
  DuggaSys/diagram/draw/selection.js
  DuggaSys/diagram/helpers/boxSelect.js
Labels: G1-2024

#16042 fixed the id on the lock button
  DuggaSys/diagram/draw/options.js
Labels: G1-2024

#15991 Reverted ghost pos to correct resize bug #15944
  DuggaSys/diagram/defaults.js
  DuggaSys/diagram/draw/element.js
  DuggaSys/diagram/theme.js
Labels: G1-2024

#15925 fix for issue #15877 "It's possible to select existing lines while dragging a new one"
  DuggaSys/diagram/events/mouse.js
Labels: G1-2024

#16090 G1 2024 #15781
  DuggaSys/diagram/draw/boxSelect.js
Labels: G1-2024

#16043 G2 2024 v7 issue#15959
  DuggaSys/microservices/courseedService/specialUpdate_ms.php
  DuggaSys/tests/microservices/courseedService/specialUpdate_ms_test.php
Labels: Group-2-2024

#16081 G1 2024 v7 #15786
  DuggaSys/diagram/draw/options.js
Labels: G1-2024

#16015 G2 2024 v7 issue#15980
  DuggaSys/microservices/fileedService/updateFileLink_ms.php
Labels: Group-2-2024

#16109 G2 2024 v7 issue#16093
  DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php
Labels: Group-2-2024

#16106 G2 2024 v7 issue#16092
  DuggaSys/accessed.php
  DuggaSys/codeviewer.php
  DuggaSys/codeviewerService.php
  DuggaSys/contribution.php
  DuggaSys/courseed.php
  DuggaSys/diagram.php
  DuggaSys/diagram_IOHandler.php
  DuggaSys/fileed.php
  DuggaSys/microservices/sectionedService/readCourseGroupsAndMembers_ms.php
  DuggaSys/profile.php
  DuggaSys/pushnotifications.php
  DuggaSys/resulted.php
  DuggaSys/sectioned.php
  DuggaSys/tests/duggaedService_test.php
  DuggaSys/tests/fileedService_test.php
  Shared/loginlogout.php
  Shared/resetpw.php
  errorpages/404.php
  testingdb/testingdb_setup.php
Labels: Group-2-2024

#16114 G2 2024 v7 issue#16097
  DuggaSys/microservices/sectionedService/createListEntry_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Labels: Group-2-2024

#16119 G2 2024 v7 issue#16116
  DuggaSys/microservices/Microservices.md
  DuggaSys/microservices/courseedService/retrieveAllCourseedServiceData_ms.php
  DuggaSys/tests/microservices/courseedService/deleteCourseMaterial_ms_test.php
  DuggaSys/tests/microservices/courseedService/retrieveCourseedService_ms_test.php
Labels: Group-2-2024

#16057 updated documentation for ruler.js
  DuggaSys/diagram/draw/ruler.js
Labels: G1-2024

#16002 documentation for event/mouse.js as specified in #15790
  DuggaSys/diagram/events/mouse.js
Labels: G1-2024

#16131 made md file and wrote instructions
  includeInstructions.md
Labels: Group-2-2024

#16052 G1 2024 #16048
  DuggaSys/JSON/ERDiagramMockup.json
  DuggaSys/JSON/IEDiagramMockup.json
  DuggaSys/diagram/classes/element.js
  DuggaSys/diagram/defaults.js
  DuggaSys/diagram/helpers/element.js
Labels: G1-2024

#16004 documentation for helpers/mouse.js as specified in #15998
  DuggaSys/diagram/helpers/mouse.js
Labels: G1-2024

#16136 Documentation of fileedService microservices written
  DuggaSys/tests/microservices/Microservices_tests_documentation.md
Labels: Group-2-2024

#16130 G2 2024 v7 issue#16125
  DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
Labels: Group-2-2024

#16156 Added 'feedbackquestion' into the microservice and the test for the ms
  DuggaSys/microservices/sectionedService/readUserDuggaFeedback_ms.php
  DuggaSys/tests/microservices/sectionedService/readUserDuggaFeedback_ms_test.php
  Shared/dugga.js
Labels: Group-2-2024

#16163 Reimplemented recursive relation on ER diagram
  DuggaSys/diagram/draw/line.js
Labels: G1-2024
