Repository HGustavs/LenaSYS, pull requests merged in 2024-04, with the labels that each got.

#14307 Added option to enable "Using Docker" in installer.
  install/install.php
Labels: Testing

#14300 Fixed savebutton in diagrams.php (#13984)
  DuggaSys/diagram.php
Labels: G1-2024

#14318 Fixed issue where two notifications would pop up when centering in diagram.php. (#14293)
  DuggaSys/diagram.php
  Hello World
  markdown-testfiles/lenasys-markdown.txt
  testfiles/Text.txt
Labels: Testing, G1-2024

#14365 Now not possible to bring up context menu when on diagram page.
  DuggaSys/diagram.js
Labels: G1-2024

#14355 G2 2024 v13 issue#14156
  DuggaSys/microservices/courseedService/createCourseVersion_ms.php
  Shared/dugga.js
Labels: Group-2-2024

#14373 Updated keybinds, added cycling #14314
  DuggaSys/diagram.js
  DuggaSys/diagramkeybinds.md
Labels: G1-2024

#14417 Fixed savebutton in diagrams.php (#13984)
  DuggaSys/diagram.php
Labels: G1-2024

#14396 G2 2024 v13 issue#14336
  DuggaSys/tests/duggaedservice-tests.php
  DuggaSys/tests/fileedservice_test.php
  DuggaSys/tests/sectionedservice_Test.php
  DuggaSys/tests/showDuggaservice_test.php
  Shared/database.php
  Shared/test.php
Labels: Group-2-2024

#14418 Enlarge section that opens the option
  DuggaSys/diagram.css
  backend-models/functional-requirements/FRD_courseedservice.md
Labels: G1-2024

#14377 Solved issue where box-select wouldn't properly select items. (#14325)
  DuggaSys/diagram.js
Labels: G1-2024

#14436 Updated formatting #14380
  DuggaSys/diagram.js
Labels: G1-2024

#14439 G1 2024 v1
  DuggaSys/JSON/StateChartDiagramMockup.json
  DuggaSys/diagram.css
  DuggaSys/diagram.js
  DuggaSys/diagram.php
  DuggaSys/diagramkeybinds.md
  markdown-testfiles/lenasys-markdown.txt
Labels: G1-2024

#14468 Solved the 'keybind for note' bug
  DuggaSys/diagram.js
Labels: G1-2024

#14477 arrow is not broken anymore #14292
  DuggaSys/diagram.js
Labels: G1-2024

#14479 fixd #14454
  Shared/navheader.php
Labels: g3-2024

#14444 Fixed #14358
  DuggaSys/sectioned.js
Labels: g3-2024

#14488 G2 2024 v2 progress on #13860 and fixes to test.php.
  DuggaSys/showDugga.php
  DuggaSys/templates/block.md
  DuggaSys/tests/showDuggaservice_test.php
  Shared/test.php
Labels: G2 Waiting for Test

#14462 fixed #14460
  DuggaSys/microservices/courseedService/createNewCourse_ms.php
  Shared/dugga.js
Labels: G2 Waiting for Test

#14453 g2-2024-v2-#14206
  DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
Labels: Testing

#14484 Fixed accedental context clear #14483
  DuggaSys/diagram.js
Labels: G1-2024

#14519 Added functionality to close loaddiagram using escape key #14403
  DuggaSys/diagram.js
Labels: G1-2024

#14490 Updated centering #14446
  DuggaSys/diagram.js
Labels: G1-2024

#14461 Fixed #14398
  DuggaSys/gitcommitService.php
  Shared/navheader.php
Labels: g3-2024

#14481 G2 2024 v2 issue#14435
  DuggaSys/microservices/sectionedService/getDeletedListentries_ms.php
  DuggaSys/sectioned.js
Labels: Testing, G2 Waiting for Test

#14482 replaced break; with isOverlapping = false;
  DuggaSys/diagram.js
Labels: G1-2024

#14515 g2-2024-v2 #14419
  DuggaSys/microservices/sectionedService/reorderListentries_ms.php
Labels: Testing

#14469 Fixed the collide issue
  DuggaSys/diagram.js
Labels: G1-2024

#14392 G2 2024 v13 #14199
  DuggaSys/microservices/courseedService/updateCourseVersion_courseed_ms.php
  DuggaSys/microservices/updateCours_ms.php
  DuggaSys/microservices/updateCourse
Labels: G2 Waiting for Test, Group-2-2024

#14540 remove all references to the unused variable $appuser and remove unnecessary debug call from test.php.
  DuggaSys/codeviewerService.php
  DuggaSys/microservices/monolithic-to-microservices.md
  DuggaSys/microservices/shared_microservices/getUid_ms.php
  Shared/test.php
Labels: G2 Waiting for Test

#14564 G2 2024 v2 issue#14449
  DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
  DuggaSys/microservices/sectionedService/getCourseGroupsAndMembers_ms.php
  Shared/dugga.js
Labels: G2 Waiting for Test

#14582 Selecting with ghost entity disable
  DuggaSys/diagram.js
Labels: G1-2024

#14547 Fixed issue where resizing elements caused the position to change. #14383
  DuggaSys/diagram.js
Labels: G1-2024

#14528 fixed element delete function
  DuggaSys/diagram.js
Labels: G1-2024

#14585 Fixed issues with nodes for resizing not showing. (#14523)
  DuggaSys/diagram.js
Labels: G1-2024

#14571 G2 2024 v2 issue#14209 Create microservice deleteListentries
  DuggaSys/microservices/sectionedService/deleteListentries_ms.php
  DuggaSys/sectioned.js
  Shared/dugga.js
Labels: G2 Waiting for Test, Group-2-2024

#14579 Created changeActiveCourseVersion_sectioned_ms.php issue#14424
  DuggaSys/microservices/sectionedService/changeActiveCourseVersion_sectioned_ms.php
Labels: G2 Waiting for Test

#14604 updated remove course
  DuggaSys/courseedservice.php
Labels: G2 Waiting for Test

#14575 G2 2024 v2 issue#14319 Implement retrieveSectionedService_ms
  DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Labels: G2 Waiting for Test

#14601 G2 2024 v2 issue#14552 create updateActiveUsers_ms.php
  DuggaSys/microservices/showDuggaservice/updateActiveUsers_ms.php
  Shared/dugga.js
Labels: G2 Waiting for Test

#14560 G2 2024 v2 issue#14420
  DuggaSys/microservices/sectionedService/updateListentrie_ms.php
Labels: G2 Waiting for Test

#14598 G2 2024 v2 issue#14196
  DuggaSys/microservices/courseedService/changeActiveCourseVersion_courseed_ms.php
Labels: Testing

#14475 Reimplemented setup() function from issue#14426
  DuggaSys/diagram.js
  DuggaSys/templates/diagram_dugga.js
Labels: G1-2024

#14513 aligned instructions and canvas #12886
  DuggaSys/templates/diagram_dugga.html
Labels: G1-2024

#14611 line draw refactor#14494
  DuggaSys/diagram.js
Labels: G1-2024

#14574 G2 2024 v2 issue#14504
  DuggaSys/duggaedservice.php
  DuggaSys/tests/duggaedservice-tests.php
Labels: G2 Waiting for Test

#14592 G2 2024 v2 issue#14555
  DuggaSys/microservices/showDuggaService/loadDugga_ms.php
Labels: G2 Waiting for Test

#14606 remove echo from validateHash.php
  DuggaSys/validateHash.php
Labels: G2 Waiting for Test

#14616 Fixed delete button on select #14615
  DuggaSys/diagram.js
Labels: G1-2024

#14655 Merge issue#14650 add correct paths for logging
  Shared/logging.php
Labels: G2 Waiting for Test

#14652 G2 2024 v3 issue#14625
  DuggaSys/duggaed.php
  Shared/navheader.php
Labels: G2 Waiting for Test

#14660 New Pull request for issue#14485
  DuggaSys/diagram.js
Labels: G1-2024

#14683 G1 2024 v3 #14291
  DuggaSys/diagram.js
Labels: G1-2024

#14680 G1 2024 v3 #14548
  DuggaSys/diagram.js
Labels: G1-2024

#14667 G1 2024 v3 #14651
  DuggaSys/diagram.css
Labels: G1-2024

#14692 issue #14572 is now fixed
  DuggaSys/diagram.js
Labels: G1-2024

#14676 Placing a element now de-selects everything.
  DuggaSys/diagram.js
Labels: G1-2024

#14672 changed all variables in elementTypesNames
  DuggaSys/diagram.js
Labels: G1-2024

#14687 replaced color strings #14485
  DuggaSys/diagram.js
Labels: G1-2024

#14674 replaced strings with direction const #14491
  DuggaSys/diagram.js
Labels: G1-2024

#14678 Remove gradesystem input on the kind type 3
  DuggaSys/sectioned.js
Labels: G2 Waiting for Test, Group-2-2024

#14710 ctrl + a sets mouse to pointer
  DuggaSys/diagram.js
Labels: G1-2024

#14727 G1 2024 v3 #14632
  DuggaSys/diagram.js
Labels: G1-2024

#14770 G2 2024 v3 issue #14718 #14764
  DuggaSys/tests/sectionedservice_Test.php
  install/SQL/testdata.sql
Labels: G2 Waiting for Test

#14762 fixed the pointer when dragging down
  DuggaSys/diagram.js
Labels: G1-2024

#14792 Increased the height for ER-tables: issue#14778
  Shared/css/style.css
Labels: G1-2024

#14785 G1 2024 v3 #14701
  DuggaSys/diagram.js
Labels: G1-2024

#14773 Removed onchange="checkDropdownOption()" from the example diagram fi…
  DuggaSys/diagram.php
Labels: G1-2024

#14695 G2 merge issue#14590
  DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Labels: G2 Waiting for Test

#14724 G2 2024 v3 #14642
  DuggaSys/microservices/duggaedService/updateDugga_ms.php
Labels: G2 Waiting for Test

#14808 updateUser #14754
  DuggaSys/microservices/accessedService/updateUser_ms.php
Labels: G2 Waiting for Test

#14802 G1 2024 v3 #14769
  DuggaSys/diagram.js
Labels: G1-2024

#14810 G1 2024 V3 #14776
  DuggaSys/diagram.js
Labels: G1-2024

#14821 Changed IEEntity to behave like UMLEntity
  DuggaSys/diagram.js
Labels: G1-2024

#14805 Program now detects overlapping while resizing objects
  DuggaSys/diagram.js
Labels: G1-2024

#14768 G2 2024 v3 #14755
  DuggaSys/accessedservice.php
  DuggaSys/microservices/accessedService/updateUserCourse_ms.php
Labels: G2 Waiting for Test

#14829 UML states broken out #14823
  DuggaSys/diagram.js
Labels: G1-2024

#14818 removed unused variable
  DuggaSys/diagram.js
Labels: G1-2024

#14859 Separated the lifeline actor/object into two different elements. (#14654)
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2024

#14860 G1 2024 v3 #14740
  DuggaSys/diagram.css
  Shared/css/style.css
Labels: G1-2024

#14809 deleted some conditions
  DuggaSys/diagram.js
Labels: G1-2024

#14820 Fixed #14816
  DuggaSys/diagram.js
Labels: G1-2024

#14726 fix for #12756
  DuggaSys/diagram.js
Labels: G1-2024

#14576 I searched in diagram.js for Conditions and i added entityTypes. issue #14486
  DuggaSys/diagram.js
Labels: G1-2024

#14973 Broke out note into function #14941
  DuggaSys/diagram.js
Labels: G1-2024

#14920 G1 2024 V4 #14880
  DuggaSys/diagram.js
Labels: G1-2024

#14909 G1 2024 v4 #14872
  DuggaSys/diagram.js
Labels: G1-2024

#14998 G2 2024 v4 issue#14965 Create microservicec refreshGithubRepo_ms.php
  DuggaSys/microservices/gitCommitService/refreshGithubRepo_ms.php
Labels: Group-2-2024

#14972 G1 2024 V4 #14944
  DuggaSys/diagram.js
Labels: G1-2024

#14974 Fixed the minimum height and width for superstates
  DuggaSys/diagram.js
Labels: G1-2024

#14995 Broke out ER into function #14979
  DuggaSys/diagram.js
Labels: G1-2024

#14858 G1 2024 v3 #14832
  DuggaSys/diagram.js
Labels: G1-2024

#15022 Changed position for cardinalities on ER-lines. (#14882)
  DuggaSys/diagram.js
Labels: G1-2024

#15061 G2 2024 v4 #15059
  DuggaSys/microservices/showDuggaService/processDuggaFile_ms.php
Labels: Group-2-2024

#15048 Moved common code to drawElement #15046
  DuggaSys/diagram.js
Labels: G1-2024

#15049 Replaced functions #15044
  DuggaSys/diagram.js
Labels: G1-2024

#15074 Moved ER-relation to be the second item in the relation sublist for issue#14376
  DuggaSys/diagram.php
Labels: G1-2024

#15072 G1 2024 v4 #15050
  DuggaSys/diagram.js
Labels: G1-2024

#15122 fixed note resizing #15031
  DuggaSys/diagram.js
Labels: G1-2024

#15043 Replaced getPoint #15042
  DuggaSys/diagram.js
  DuggaSys/diagram/helper.js
Labels: G1-2024

#15108 Removed repetition and nesting #15100
  DuggaSys/diagram.js
Labels: G1-2024

#15123 Corner nodes for entities #14947
  DuggaSys/diagram.css
  DuggaSys/diagram.js
Labels: G1-2024

#15175 element z-index #15170
  DuggaSys/diagram.js
Labels: G1-2024

#15134 updated submenu icons and cycling #15133
  DuggaSys/diagram.js
  DuggaSys/diagram.php
Labels: G1-2024

#15010 G1 2024 V4 #14878
  DuggaSys/diagram.js
Labels: G1-2024

#15018 G1 2024 V4 #15000
  DuggaSys/diagram.js
Labels: G1-2024

#15141 ctrl + z #14364
  DuggaSys/diagram.js
Labels: G1-2024

#15094 Broke out attribute change #15085
  DuggaSys/diagram.js
Labels: G1-2024
