Repository HGustavs/LenaSYS, pull requests merged in 2025-05, with the labels that each got.

#17056 Ignore the file "microservice_connection.md" in the Microservice directory database script #16994
  DuggaSys/microservices/endpointDirectory/fillEndpointDb.php
Labels: Grupp 2 - 2025

#17085 Resolved conflicts in sharedMicroservices documentation
  DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
Labels: Grupp 2 - 2025

#17095 Fix underfined array key warnings for output fields in microserviceUI.php. #17065
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17104 Create table documentation for Microservice Directory #16620
  DuggaSys/microservices/endpointDirectory/microserviceDirectoryDocumentation.md
Labels: Grupp 2 - 2025

#17087 Update createTables.sql
  Shared/SQL/createTables.sql
  Shared/SQL/init_db.sql
Labels: Grupp 2 - 2025

#17090 DeleteCourseMaterial reengineered - Issue #16858
  DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
  DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
Labels: Grupp 2 - 2025

#17136 17014 there are problems with the lines loaded from the example diagrams
  DuggaSys/diagram/draw/line.js
Labels: G1-2025

#17083 Added specific error handling for events modal in new installer. Use Docker and Windows to test it.
  newinstaller/installer_ui.js
  newinstaller/installer_ui.php
  newinstaller/style.css
  newinstaller/tools/modal.js
  newinstaller/tools/modal.php
  newinstaller/tools/sse_receiver.js
Labels: Grupp 2 - 2025

#17147 [#17086] Fixed issue with quicksave keybind triggering constantly when held down
  DuggaSys/diagram.js
Labels: G1-2025

#17139 Documented getAccessedService_ms and retrieveAccessedService_ms
  DuggaSys/microservices/Microservices Documentation/accessedService.md
Labels: Grupp 2 - 2025

#17121 Added a button to create database in microservicesUI.php
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17132 Added styling for microserviceUI
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
  DuggaSys/microservices/endpointDirectory/style.css
Labels: Grupp 2 - 2025

#17099 Re-engineer microservice retrieveShowDuggaService #16979
  DuggaSys/microservices/showDuggaService/getShowDugga_ms.php
  DuggaSys/microservices/showDuggaService/loadDugga_ms.php
  DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
  DuggaSys/microservices/showDuggaService/saveDugga_ms.php
  DuggaSys/microservices/showDuggaService/updateActiveUsers_ms.php
Labels: Grupp 2 - 2025

#17137 Added macOS command to instructions
  README.md
Labels: Grupp 2 - 2025

#17215 updated readCourseVersions to use cURL
  DuggaSys/microservices/sectionedService/readCourseVersions_ms.php
  DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Labels: Grupp 2 - 2025

#17195 Changed callMicroserviceGET function parameter in curlService.php #17186
  DuggaSys/microservices/curlService.php
Labels: Grupp 2 - 2025

#17211 Add database download button to microserviceUI #17188
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17145 Documented updateUser_ms and updateUserCourse_ms
  DuggaSys/microservices/Microservices Documentation/accessedService.md
Labels: Grupp 2 - 2025

#17217 Added a command text "docker compose up --build" for macOS
  dockerenv/document/docker_install_instructions.md
Labels: Grupp 2 - 2025

#17228 Add foreign key from microservice table to dependencies table in endpoint database #17212
  DuggaSys/microservices/endpointDirectory/dependenciesList.php
  DuggaSys/microservices/endpointDirectory/fillDependenciesDb.php
  DuggaSys/microservices/endpointDirectory/installEndpointDb.php
Labels: Grupp 2 - 2025

#17149 mini re-factor for duggaService
  DuggaSys/microservices/showDuggaService/processDuggaFile_ms.php
  DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
Labels: Grupp 2 - 2025

#17164 Added edit functionality
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17204 Fix return options on curlService Get function - Issue #17114
  DuggaSys/microservices/curlService.php
Labels: Grupp 2 - 2025

#17157 Re-Engineer of loadDugga_ms.php
  DuggaSys/microservices/showDuggaService/loadDugga_ms.php
  DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
Labels: Grupp 2 - 2025

#17242 Fixed desktop toolbar height
  DuggaSys/diagram.css
Labels: G1-2025

#17263 Re-engineer of insertIntoSQLite_ms.php
  DuggaSys/microservices/gitCommitService/getCourseID_ms.php
  DuggaSys/microservices/gitCommitService/insertIntoSQLite_ms.php
Labels: Grupp 2 - 2025

#17286 Changed microservice retrieveUsername to use curlService #17273
  DuggaSys/microservices/accessedService/retrieveAccessedService_ms.php
  DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createNewCourse_ms.php
  DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
  DuggaSys/microservices/courseedService/updateCourse_ms.php
  DuggaSys/microservices/fileedService/updateFileLink_ms.php
  DuggaSys/microservices/sectionedService/createListEntry_ms.php
  DuggaSys/microservices/sectionedService/updateCourseVersion_sectioned_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Labels: Grupp 2 - 2025

#17301 Added filter functionality
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17276 Add dependencies to microservices in microserviceUI.php #17269
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17324 Fixed issue #17319. Use only Windows with XAMPP
  newinstaller/tools/configuration_manager.php
Labels: Grupp 2 - 2025

#17344 Added microservice form functionality
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17274 G3 2025 v6 #17025 jquery to js in profile.js
  DuggaSys/profile.js
Labels: Grupp 3 - 2025

#17355 Change the styling of a-tags in MicroserviceUI #17340
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
  DuggaSys/microservices/endpointDirectory/style.css
Labels: Grupp 2 - 2025

#17397 Deleted a document and all images
  dockerenv/document/apacheLink.png
  dockerenv/document/choosePlan.png
  dockerenv/document/containersdeactive.png
  dockerenv/document/createAccount.png
  dockerenv/document/dockerContainers.png
  dockerenv/document/dockerContainers2.png
  dockerenv/document/dockerDesktop.png
  dockerenv/document/docker_home.png
  dockerenv/document/docker_install_instructions.md
  dockerenv/document/dockerimages.png
  dockerenv/document/github.png
  dockerenv/document/homepage.png
  dockerenv/document/lenasys.png
  dockerenv/document/newlenasysinstaller.png
  dockerenv/document/os.png
  dockerenv/document/stopdocker.png
  dockerenv/document/terminal.png
  dockerenv/document/terminal2.png
  dockerenv/document/terminal3.png
  dockerenv/document/terminal4.png
  dockerenv/document/terminal5.png
  dockerenv/document/terminal6.png
  dockerenv/document/terminal7.png
  dockerenv/document/terminal8.png
Labels: Grupp 2 - 2025

#17376 Update curlService.php
  DuggaSys/microservices/curlService.php
Labels: Grupp 2 - 2025

#17401 Updated Microservices Documentation template.md
  DuggaSys/microservices/Microservices Documentation/template.md
Labels: Grupp 2 - 2025

#17404 Update curlService.php
  DuggaSys/microservices/curlService.php
Labels: Grupp 2 - 2025

#17347 G3 2025 V6 changed default visibility of objects
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2025

#17336 Fixed acccess denied user, when go to a course page using new LenaSYS installer with docker
  newinstaller/installer_ui.php
  newinstaller/new_components.php
  newinstaller/test.html
  newinstaller/tools/modal.js
Labels: Grupp 2 - 2025

#17378 Documented changeActiveCourseVersion_sectioned_ms and createGithubCodeExample_ms
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
Labels: Grupp 2 - 2025

#17443 added documentation for microservices in microservices/resultedService
  DuggaSys/microservices/Microservices Documentation/resultedService.md
Labels: Grupp 2 - 2025

#17399 Documentation for fileedService folder
  DuggaSys/microservices/Microservices Documentation/fileedService.md
Labels: Grupp 2 - 2025

#17415 Changed to curlService in retrieveHighscoreService_ms and highscoreservice_ms #17117
  DuggaSys/microservices/highscoreService/highscoreservice_ms.php
  DuggaSys/microservices/highscoreService/retrieveHighscoreService_ms.php
Labels: Grupp 2 - 2025

#17468 documented microservices in /codeviewerService #17356
  DuggaSys/microservices/Microservices Documentation/codeviewerService.md
Labels: Grupp 2 - 2025

#17482 documented microservices in microservices/duggaedService #17360
  DuggaSys/microservices/Microservices Documentation/duggaedService.md
Labels: Grupp 2 - 2025

#17505 Documented updateListEntriesTabs_ms.php and updateListEntries_ms.php #17487
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
Labels: Grupp 2 - 2025

#17332 Remove test files used when creating endpoint database #17328
  .gitignore
  DuggaSys/microservices/endpointDirectory/newMDStructureTest.md
Labels: Grupp 2 - 2025

#17300 G3 2025 V6 fixed hide dugga list arrows
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2025

#17287 Document getDeletedListEntries_ms.php and getGroupValues_ms.php #17174
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
Labels: Grupp 2 - 2025

#17510 Fixed-sequence-table-recursive-relation-labels
  DuggaSys/diagram/draw/line.js
  DuggaSys/diagram/draw/options.js
Labels: G1-2025

#17449 G2 2025 v6 a20artje 17364
  DuggaSys/microservices/Microservices Documentation/gitFetchService.md
Labels: Grupp 2 - 2025

#17459 Documented updateCourseVersion_sectioned_ms and updateListEntriesGrad…
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
Labels: Grupp 2 - 2025

#17490 G2 2025 v6 #17359 Document microservices in microservices/courseedService
  DuggaSys/microservices/Microservices Documentation/courseedService.md
Labels: Grupp 2 - 2025

#17466 Admin panel for endpointDirectory_db.sqlite #17414
  DuggaSys/microservices/endpointDirectory/admin-endpointDirectory_db.php
  DuggaSys/microservices/endpointDirectory/deleteEndpointDb.php
Labels: Grupp 2 - 2025

#17614 Documented editCodeExample_ms.php and editContentOfExample_ms.php #17447
  DuggaSys/microservices/Microservices Documentation/codeviewerService.md
Labels: Grupp 2 - 2025

#17595 Added file/documentation for deprecated services
  DuggaSys/microservices/deprecated_microservices.md
Labels: Grupp 2 - 2025

#17625 Documented all files in showDuggaService-map
  DuggaSys/microservices/Microservices Documentation/showDuggaService.md
Labels: Grupp 2 - 2025

#17647 SSL-generator #17644
  .gitignore
  newinstaller/installer_ui.php
  newinstaller/tools/ssl/ssl_generator.php
Labels: Grupp 2 - 2025

#17615 Updating the microservice UI design/structure #17304
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
  DuggaSys/microservices/endpointDirectory/style.css
Labels: Grupp 2 - 2025

#17657 Changed to curlService in retrieveResultedService_ms #17416
  DuggaSys/microservices/resultedService/getUserAnswer_ms.php
  DuggaSys/microservices/resultedService/retrieveResultedService_ms.php
Labels: Grupp 2 - 2025

#17591 Added two alerts
  DuggaSys/microservices/endpointDirectory/admin-endpointDirectory_db.php
Labels: Grupp 2 - 2025

#17593 Fixed and reduced whitespace in UML Class, IE and SD elements
  DuggaSys/diagram/draw/element.js
Labels: G1-2025, Acceptance test - issues

#17638 Fixed "Send to Back" elements placed behind the canvas
  DuggaSys/diagram/draw/options.js
Labels: Bug, G1-2025

#17683 Documented retrieveCodeviewerService_ms.php and updateCodeExampleTemplate_ms.php #17619
  DuggaSys/microservices/Microservices Documentation/codeviewerService.md
Labels: Grupp 2 - 2025

#17607 Acceptance Test Script for Connecting Course Element to Github
  DuggaSys/tests/testGithubLinkCodeExample.php
Labels: Grupp 2 - 2025

#17699 Added funtionality for read existing configuration for new installer
  newinstaller/installer_ui.php
  newinstaller/tools/components.php
  newinstaller/tools/configuration_manager.php
Labels: Grupp 2 - 2025

#17568 Change 'setupEndpointDirectory.php' to use delete script #17467
  DuggaSys/microservices/endpointDirectory/setupEndpointDirectory.php
Labels: Grupp 2 - 2025

#17693 Added inverse dependencies for getUid_ms.php in Microservices_inverse_dependencies.md #17664
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#17687 curlService for processDuggaFile
  DuggaSys/microservices/showDuggaService/processDuggaFile_ms.php
  DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
Labels: Grupp 2 - 2025

#17684 Re-engineered microservice retrieveCourseedService
  DuggaSys/microservices/courseedService/changeActiveCourseVersion_courseed_ms.php
  DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createMOTD_ms.php
  DuggaSys/microservices/courseedService/createNewCourse_ms.php
  DuggaSys/microservices/courseedService/getCourseed_ms.php
  DuggaSys/microservices/courseedService/retrieveAllCourseedServiceData_ms.php
  DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
  DuggaSys/microservices/courseedService/specialUpdate_ms.php
  DuggaSys/microservices/courseedService/updateActiveCourseVersion_courseed_ms.php
  DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
  DuggaSys/microservices/courseedService/updateCourse_ms.php
  Shared/dugga.js
Labels: Grupp 2 - 2025

#17732 Added missing inverse dependencies for retrieveSectionedService_ms.php in Microservices_inverse_dependencies.md #17694
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#17710 Documented removeListEntries_ms.php and reorderListEntries_ms.php in sectionedService.md
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
Labels: Grupp 2 - 2025

#17736 Fixed URL and removed header in sectionedService/createListEntry_ms.php #17708
  DuggaSys/microservices/sectionedService/createListEntry_ms.php
Labels: Grupp 2 - 2025

#17735 Add dependencies to microserviceUI #17721
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17730 Update microservice_connections #17427
  DuggaSys/microservices/microservice_connections.md
Labels: Grupp 2 - 2025

#17738 Added gitignore in LenaSYS/dockerenv/coursesyspw.php. Docker specific.
  dockerenv/.gitignore
  dockerenv/coursesyspw.php.template
  dockerenv/setup.bat
  dockerenv/setup.sh
Labels: Grupp 2 - 2025

#17717 Tried to fix GitHub functionality #17702
  DuggaSys/gitfetchService.php
  DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php
  DuggaSys/test_gitfetch.php
Labels: Grupp 2 - 2025

#17747 Remove unused file in microservices/endpointDirectory #17744
  .gitignore
  DuggaSys/microservices/endpointDirectory/dependenciesList.php
Labels: Grupp 2 - 2025

#17757 Add missing information to microservices/courseedService #17584
  DuggaSys/microservices/Microservices Documentation/courseedService.md
Labels: Grupp 2 - 2025

#17760 Implemented feature: Automatic options-panel toggle
  DuggaSys/diagram/draw/options.js
  DuggaSys/diagram/events/mouse.js
  DuggaSys/diagram/globals.js
Labels: Feature

#17761 Added receieveMicroservicePOST for setAsActiveCourse
  DuggaSys/microservices/sharedMicroservices/setAsActiveCourse_ms.php
Labels: Grupp 2 - 2025

#17745 Documented files in gitCommitService
  DuggaSys/microservices/Microservices Documentation/gitCommitService.md
Labels: Grupp 2 - 2025

#17799 Add parameter search to microserviceUI #17789
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17788 Updated the Docker Install Instructions
  README.md
  Shared/Documentation/docker_images/terminal4.png
Labels: Grupp 2 - 2025

#17839 COMPLEMENTS PR #17654: Convert JQuery in \DuggaSys\templates\dugga5.js - #17534
  DuggaSys/templates/dugga5.js
Labels: Grupp 3 - 2025

#17838 COMPLEMENTS PR #17723: G3 2025 v7 #17532 convert jquery to js in dugga4.js
  DuggaSys/templates/dugga4.js
Labels: Grupp 3 - 2025

#17822 Re-engineered microservice retrieveDuggaedService
  DuggaSys/microservices/duggaedService/createDuggaVariant_ms.php
  DuggaSys/microservices/duggaedService/createDugga_ms.php
  DuggaSys/microservices/duggaedService/deleteDuggaVariant_ms.php
  DuggaSys/microservices/duggaedService/deleteDugga_ms.php
  DuggaSys/microservices/duggaedService/retrieveDuggaedService_ms.php
  DuggaSys/microservices/duggaedService/updateDuggaVariant_ms.php
  DuggaSys/microservices/duggaedService/updateDugga_ms.php
Labels: Grupp 2 - 2025

#17837 Document retrieveAllCourseVersions_ms.php and retrieveSectionedService_ms.php #17433
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
Labels: Grupp 2 - 2025

#17833 Createed a test for codeviewerService/retrieveCodeviewerService_ms.php #17806
  DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php
  DuggaSys/tests/microservices/codeviewerService/retrieveCodeviewerService_ms_test.php
Labels: Grupp 2 - 2025

#17853 Created a test for fileedService/retrieveFileedService_ms.php
  DuggaSys/tests/microservices/fileedService/retrieveFileedService_ms.test.php
Labels: Grupp 2 - 2025

#17884 Created test for createGithubCodeExample_ms_test.php
  DuggaSys/tests/microservices/sectionedService/createGithubCodeExample_ms_test.php
Labels: Grupp 2 - 2025

#17868 Created a test for resultedService/retrieveResultedService_ms.php #17811
  DuggaSys/tests/microservices/resultedService/retrieveResultedService_ms_test.php
Labels: Grupp 2 - 2025

#17904 create a test for profileService/retrieveProfileService_ms.php #17810
  DuggaSys/microservices/profileService/retrieveProfileService_ms.php
  DuggaSys/tests/microservices/profileService/retrieveProfileService_ms_test.php
Labels: Grupp 2 - 2025

#17830 Created test for updateCodeExampleTemplate_ms.php
  DuggaSys/tests/microservices/codeviewerService/updateCodeExampleTemplate_ms_test.php
Labels: Grupp 2 - 2025

#17869 Fixed page not updating properly
  DuggaSys/microservices/sectionedService/readCourseVersions_ms.php
  DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Labels: Grupp 2 - 2025

#17876 Add button from microserviceUI to dependencyUI #17854
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
  DuggaSys/microservices/endpointDirectory/style.css
Labels: Grupp 2 - 2025

#17910 Fixed snapping of activation elements
  DuggaSys/diagram.js
Labels: G1-2025

#17951 Documented microservices to be renamed #17847
  DuggaSys/microservices/Microservices Documentation/renamingMicroservices.md
Labels: Grupp 2 - 2025

#17968 G2 2025 v8 #17814
  DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
  DuggaSys/tests/microservices/sectionedService/removeListEntries_ms_test.php
Labels: Grupp 2 - 2025

#17994 G3 Added dots and commas as legal names
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2025

#17974 Fixed $pdo error in createNewListEntry_ms.php #17954
  DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Labels: Grupp 2 - 2025

#18012 Removed "README.md" from the links
  README.md
Labels: Grupp 2 - 2025

#18015 Fixed course page shows empty. Linux and macos only.
  xampp/setup.sh
Labels: macOS, Grupp 2 - 2025, Linux

#18046 Doublechecked Microservices Documentation\accessedService.md and Microservices Documentation\codeviewerService.md
  DuggaSys/microservices/Microservices Documentation/accessedService.md
  DuggaSys/microservices/Microservices Documentation/codeviewerService.md
Labels: Grupp 2 - 2025

#18059 Fix initial page on newinstaller/installer.php #18052
  newinstaller/installer_ui.php
  newinstaller/style.css
Labels: Grupp 2 - 2025

#18061 Fixed the typo. Only macOS and Linux
  dockerenv/setup.sh
Labels: Grupp 2 - 2025

#18051 Edited documentation of all microservices to follow the same standard #17982
  DuggaSys/microservices/Microservices Documentation/accessedService.md
  DuggaSys/microservices/Microservices Documentation/codeviewerService.md
  DuggaSys/microservices/Microservices Documentation/courseedService.md
  DuggaSys/microservices/Microservices Documentation/duggaedService.md
  DuggaSys/microservices/Microservices Documentation/fileedService.md
  DuggaSys/microservices/Microservices Documentation/gitCommitService.md
  DuggaSys/microservices/Microservices Documentation/gitFetchService.md
  DuggaSys/microservices/Microservices Documentation/resultedService.md
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
  DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
  DuggaSys/microservices/Microservices Documentation/showDuggaService.md
Labels: Grupp 2 - 2025

#18065 G3 Fixed the horizontal scroll in sectioned.
  Shared/css/style.css
Labels: Grupp 3 - 2025

#18071 G3 2025 v8 fix auto open
  DuggaSys/diagram/draw/element.js
  DuggaSys/diagram/draw/line.js
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2025
