Repository HGustavs/LenaSYS, pull requests merged in 2025-04, with the labels that each got.

#16313 Issue-000000 a20artje hello world
  Hello World
Labels: Grupp 2 - 2025

#16112 g1 2024 v7 #15783
  DuggaSys/diagram/draw/line.js
  README.md
Labels: Grupp 3 - 2025

#16218 Fixed common typo in Microservices.md
  DuggaSys/microservices/Microservices.md
Labels: Grupp 2 - 2025

#16276 Added class to upper part of SD entity
  DuggaSys/diagram/draw/element.js
  Hello World
Labels: Grupp 3 - 2025

#16275 added the corner node code to the start/end if statement
  DuggaSys/diagram/draw/node.js
Labels: Grupp 3 - 2025

#16254 Fixed highlight in fileed.php
  DuggaSys/fileed.js
  Shared/css/style.css
Labels: Grupp 3 - 2025

#16204 Update Microservices.md
  DuggaSys/microservices/Microservices.md
Labels: Grupp 2 - 2025

#16205 Fixed courseed and sectioned motd button
  DuggaSys/sectioned.php
  Shared/css/style.css
Labels: Grupp 3 - 2025

#16189 Fixed Resizing with upper nodes on elements weird
  DuggaSys/diagram.js
Labels: Grupp 3 - 2025

#16173 Komplettering b22jonan 15788
  DuggaSys/diagram/draw/selection.js
Labels: Grupp 3 - 2025

#16180 New styling and separation of groups in Sectionlistc (#16179)
  DuggaSys/sectioned.js
  Shared/css/style.css
Labels: Grupp 3 - 2025

#16222 Updated Microservices.md
  DuggaSys/microservices/Microservices.md
Labels: Grupp 2 - 2025

#16215 16213 create documentation for specialupdate msphp and add it in microservicesmd
  DuggaSys/microservices/Microservices.md
Labels: Grupp 2 - 2025

#16273 Fixing the primary key problem
  DuggaSys/diagram/draw/element.js
Labels: Grupp 2 - 2025

#16341 G2 2025 v2 #16327 a23axehe
  DuggaSys/microservices/Microservices.md
Labels: Grupp 2 - 2025

#16390 Created list of all files in microservices #16372
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16400 Documented where setAsActiveCourse is used
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16406 Updated microservices_inverse_dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16402 Added inverse dependencies for createNewListEntry_ms.php #16381
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16404 Document inverse dependencies of retrieveUsername_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16407 Research inverse dependency for getAccessedService_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16405 Update Microservices_inverse_dependencies.md
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16410 Documented retrieveAccessedService
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16411 No dependencies found for 'addClass_ms.php'
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16403 Added a list of all inverse dependencies in updateUserPassword section
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16408 Added inverse dependencies for createNewCodeExample_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16432 Updated microservices_inverse_dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16434 Fix typo in Microservices.md
  DuggaSys/microservices/Microservices.md
Labels: Grupp 2 - 2025

#16422 Documented inverse dependencies for isSuperUser_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16425 Added updateUser inverse dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16416 Updated microservices_inverse_dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16465 Added a text about inverse dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16464 Documentation inverse dependencies for editBoxTitle_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16440 Update Microservices_inverse_dependencies.md
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16469 Added inverse dependencies: updateCodeExampleTemplate_ms.php #16447
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16476 Updated Microservices_inverse_dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16477 Documentation for inverse dependencies retrieveAllCourseedServiceData_ms.php.
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16482 Found inverse dependencies - 16470
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16481 Added directory text
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16483 Documented inverse dependencies for retrieveCodeviewerService_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16504 Add documentation regarding inverse dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16495 Added documentation for updateActiveCourseVersion_courseed_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16486 issue#16452
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16485 Documented inverse dependencies for updateCourseVersion_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16493 Updated microservices_inverse_dependencies for "createCourseVersion_ms"
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16506 Update Microservices_inverse_dependencies.md
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16502 Update Microservices_inverse_dependencies.md
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16174 komplettering b22jonan 15751
  DuggaSys/diagram/draw/options.js
Labels: G1-2025

#16546 Documented inverse dependencies for deleteDugga_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16496 Added inverse dependencies: specialUpdate_ms.php #16458
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16561 Updated dependencies.
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16500 Documented getCourseed in Microservices_inverse_dependencies
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16564 Renamed from keywords_java.sql to keywords_javascript.sql file
  newinstaller/SQL/keywords_javascript.sql
Labels: Grupp 2 - 2025

#16487 G2 2025 v2 #16453
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16509 Documented inverse dependencies for updateDuggaVariant_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16576 Create Documentation folder and template
  DuggaSys/microservices/Microservices Documentation/template.md
Labels: Grupp 2 - 2025

#16579 Update Microservices_inverse_dependencies.md
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16568 Add communication between EndpointDirectory and nameQuery - issue 16519
  DuggaSys/microservices/endpointDirectory/endpointDirectory.php
  DuggaSys/microservices/endpointDirectory/nameQuery.php
Labels: Grupp 2 - 2025

#16365 Added deletes after each test #16271
  DuggaSys/tests/microservices/courseedService/copyCourseVersion_ms_test.php
Labels: Grupp 2 - 2025

#16600 G2 2025 v2 #16538 a23oskme
  .gitignore
  DuggaSys/microservices/endpointDirectory/fillEndpointDb.php
  DuggaSys/microservices/endpointDirectory/installEndpointDb.php
  DuggaSys/microservices/endpointDirectory/microserviceList.php
  DuggaSys/microservices/endpointDirectory/testMarkDownFile.md
Labels: Grupp 2 - 2025

#16603 Documented inverse dependencies: changeActiveCourseVersion_sectioned_ms.php, createGithubCodeExample_ms.php #16593
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16569 Update .gitignore
  .gitignore
  newinstaller/courses/1/.gitkeep
  newinstaller/courses/2/.gitkeep
  newinstaller/courses/global/.gitkeep
Labels: Grupp 2 - 2025

#16607 Documented getCourseGroupsAndMembers_ms.php AND getCourseVersions_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16575 Update Microservices_inverse_dependencies.md
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16618 Fixed directoryRendering include by adding .php
  .gitignore
  DuggaSys/microservices/Microservices_inverse_dependencies.md
  DuggaSys/microservices/endpointDirectory/endpointDirectory.php
  newinstaller/courses/1/.gitkeep
  newinstaller/courses/2/.gitkeep
  newinstaller/courses/global/.gitkeep
Labels: Grupp 2 - 2025

#16604 Inverse dependencies for createListEntry and deleteListEntries
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16610 Documented getListEntries_ms.php AND getUserDuggaFeedback_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16615 Connect name query to database - Issue #16570
  DuggaSys/microservices/endpointDirectory/nameQuery.php
Labels: Grupp 2 - 2025

#16614 Updated microservices_inverse_dependencies for "getDeletedListEntries…
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16633 G2 2025 v2 #16566
  DuggaSys/microservices/microservice_connections.md
Labels: Grupp 2 - 2025

#16609 Documented lack of inverse dependencies in editCodeExample_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16623 Added a button for go to course page when installer is finish to inst…
  newinstaller/installer_ui.js
  newinstaller/installer_ui.php
  newinstaller/style.css
Labels: Grupp 2 - 2025

#16641 Added a button when installer failed to install lenasys
  newinstaller/installer_ui.js
Labels: Grupp 2 - 2025

#16524 Replacing/removing Jquery from topbar with React/Babel
  Shared/navheader.php
Labels: Grupp 3 - 2025

#16047 Added documentation for issue#15794
  DuggaSys/diagram/constants.js
Labels: Documentation, G1-2025

#16580 Added subfolders
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
  DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
Labels: Grupp 2 - 2025

#16677 Document inverse dependencies for updateVisibleListEntries
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16667 G2 2025 v3 #16520 a23oskme
  DuggaSys/microservices/endpointDirectory/endpointDirectory.php
  DuggaSys/microservices/endpointDirectory/endpointDirectory_db-sqlite
  DuggaSys/microservices/endpointDirectory/parameterQuery.php
Labels: Grupp 2 - 2025

#16673 List inverse dependencies for updateListEntriesTabs_ms.php AND updateListEntries_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16679 Fixed: Copy pasting is no longer working in the diagram site.
  DuggaSys/diagram/constants.js
  DuggaSys/diagram/helper.js
Labels: G1-2025

#16676 Update Microservices_inverse_dependencies.md for updateListEntryOrder_ms.php AND updateQuizDeadline_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16699 Updated microservices_inverse_dependencies for "setVisibleListentries…
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16708 Fixed microservice endpoint output format
  DuggaSys/microservices/endpointDirectory/directoryRendering.php
  DuggaSys/microservices/endpointDirectory/endpointDirectory.php
Labels: Grupp 2 - 2025

#16691 Pre-filled root username with 'root' in new installer
  newinstaller/installer_ui.php
  newinstaller/tools/components.php
Labels: Grupp 2 - 2025

#16730 Documented inverse dependencies: deleteFileLink_ms.php AND getFileedService_ms.php #16727
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16735 Documented inverse dependencies for retrieveFileedService and updateFileLink
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16739 Corrected the documentation of reorderListEntries/updateListEntryOrder
  backend-models/microservices/duggaSys services/Microservices.md
Labels: Grupp 2 - 2025

#16740 Delete old file endpointDirectory
  DuggaSys/microservices/endpointDirectory/endpointDirectory.php
Labels: Grupp 2 - 2025

#16741 Documented inverse dependencies for clearGitFiles and fetchOldToken.
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16761 Documented inverse dependencies for getGithubURL and getIndexFile.
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16762 Documentation inverse dependencies for insertToFileLink_ms.php and insertToMetadata_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16777 Issue#16731
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16779 Documented inverse dependencies: highscoreservice_ms.php AND retrieveHighscoreService_ms.php #16754
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16788 Fix for copypasting elements with labels #16542
  DuggaSys/diagram/helper.js
Labels: G1-2025

#16778 Updated microservices_inverse_dependencies for "newUpdateTime_ms.php"…
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16799 Document inverse dependencies: the two files in /resultedService #16792
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16781 Updated docker install instructions
  dockerenv/docker_install_instructions.md
  dockerenv/document/apacheLink.png
  dockerenv/document/choosePlan.png
  dockerenv/document/containersdeactive.png
  dockerenv/document/createAccount.png
  dockerenv/document/dockerContainers.png
  dockerenv/document/dockerContainers2.png
  dockerenv/document/dockerDesktop.png
  dockerenv/document/docker_home.png
  dockerenv/document/docker_install_instructions.md
  dockerenv/document/dockerimages.png
  dockerenv/document/github.png
  dockerenv/document/homepage.png
  dockerenv/document/lenasys.png
  dockerenv/document/newlenasysinstaller.png
  dockerenv/document/os.png
  dockerenv/document/stopdocker.png
  dockerenv/document/terminal.png
  dockerenv/document/terminal2.png
  dockerenv/document/terminal3.png
  dockerenv/document/terminal4.png
  dockerenv/document/terminal5.png
  dockerenv/document/terminal6.png
  dockerenv/document/terminal7.png
  dockerenv/document/terminal8.png
Labels: Grupp 2 - 2025

#16783 Microservice conversion coding standard
  DuggaSys/microservices/Microservices Documentation/microserviceCodingStandard.md
Labels: Grupp 2 - 2025

#16805 Added inverse dependencies - Issue #16794
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16809 Sanitized inputs #16782
  DuggaSys/diagram/draw/element.js
  DuggaSys/diagram/draw/options.js
Labels: G1-2025

#16674 Updated template for Microservices Documentation
  DuggaSys/microservices/Microservices Documentation/template.md
Labels: Grupp 2 - 2025

#16714 Added instructions on how to install XAMPP in README.md
  README.md
  Shared/Documentation/Install/installXAMPP.png
Labels: Grupp 2 - 2025

#16820 Added selection to check if buttons are not null
  newinstaller/tools/modal.js
Labels: Grupp 2 - 2025

#16808 Fix grammar and typos for docker_install_instructions.md
  dockerenv/document/docker_install_instructions.md
Labels: Grupp 2 - 2025

#16804 G2 2025 v3 #16635
  DuggaSys/microservices/microservice_connections.md
Labels: Grupp 2 - 2025

#16796 Inverse dependencies: getShowDugga_ms.php & loadDugga_ms.php
  DuggaSys/microservices/Microservices_inverse_dependencies.md
Labels: Grupp 2 - 2025

#16821 Updated microservices_inverse_dependencies for "retrieveProfileServic…
  DuggaSys/microservices/Microservices_inverse_dependencies.md
  backend-models/microservices/duggaSys services/Microservices.md
Labels: Grupp 2 - 2025

#16860 Added a title section about how to setup docker in README file.
  README.md
  Shared/Documentation/docker_images/apacheLink.png
  Shared/Documentation/docker_images/choosePlan.png
  Shared/Documentation/docker_images/containersdeactive.png
  Shared/Documentation/docker_images/createAccount.png
  Shared/Documentation/docker_images/dockerContainers.png
  Shared/Documentation/docker_images/dockerContainers2.png
  Shared/Documentation/docker_images/dockerDesktop.png
  Shared/Documentation/docker_images/docker_home.png
  Shared/Documentation/docker_images/dockerimages.png
  Shared/Documentation/docker_images/github.png
  Shared/Documentation/docker_images/homepage.png
  Shared/Documentation/docker_images/lenasys.png
  Shared/Documentation/docker_images/newlenasysinstaller.png
  Shared/Documentation/docker_images/os.png
  Shared/Documentation/docker_images/stopdocker.png
  Shared/Documentation/docker_images/terminal.png
  Shared/Documentation/docker_images/terminal2.png
  Shared/Documentation/docker_images/terminal3.png
  Shared/Documentation/docker_images/terminal4.png
  Shared/Documentation/docker_images/terminal5.png
  Shared/Documentation/docker_images/terminal6.png
  Shared/Documentation/docker_images/terminal7.png
  Shared/Documentation/docker_images/terminal8.png
Labels: Grupp 2 - 2025

#16879 G3-2025-v3-#16336-delete-without-selection-V2
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
Labels: Grupp 3 - 2025

#16864 Changed the JQuery used in codeviewer.js with normal JS - G3 2025 v4 a23alera #16768
  DuggaSys/codeviewer.js
Labels: Grupp 3 - 2025

#16872 Locate and change the jQuery used in sectioned.js with normal js commands line 902 - 1388 (Revamp)
  DuggaSys/sectioned.js
  README.md
Labels: Grupp 3 - 2025

#16851 Removed broken comment
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2025

#16877 Remove the jquery UI in code viewer #16718
  DuggaSys/codeviewer.js
Labels: Grupp 3 - 2025

#16876 Remove jQuery in section #16639
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2025

#16937 G2 2025 v4 #16854 a23oskme
  DuggaSys/microservices/endpointDirectory/dependenciesList.php
  DuggaSys/microservices/endpointDirectory/fillDependeciesDb.php
  DuggaSys/microservices/endpointDirectory/installEndpointDb.php
  DuggaSys/microservices/endpointDirectory/newMDStructureTest.md
Labels: Grupp 2 - 2025

#16942 Create microserviceRefactorPOSTWithAnswer.md
  DuggaSys/microservices/Microservices Documentation/microserviceRefactorPOSTWithAnswer.md
Labels: Grupp 2 - 2025

#16875 Create courseCreationAcceptanceTest.php #16512
  DuggaSys/microservices/courseCreationAcceptanceTest.php
Labels: Grupp 2 - 2025

#16941 Re-engineer microservice retrieveHighscoreService #16870
  DuggaSys/microservices/highscoreService/highscoreservice_ms.php
  DuggaSys/microservices/highscoreService/retrieveHighscoreService_ms.php
Labels: Grupp 2 - 2025

#16882 FAB button bug fixed: refactoring of the cogwheel button to use a React button component
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/components/Button.js
Labels: Grupp 3 - 2025

#16883 G3 2025 v3 #16643 jquery to js in show dugga
  DuggaSys/templates/svg-dugga.js
  Shared/dugga.js
  Shared/markdown.js
Labels: Grupp 3 - 2025

#16908 Create microserviceRefactorPOSTnoAnswer.md
  DuggaSys/microservices/Microservices Documentation/microserviceRefactorPOSTnoAnswer.md
Labels: Grupp 2 - 2025

#16958 Update updateCourseVersion_ms.php
  DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
Labels: Grupp 2 - 2025

#16962 G2 2025 v4 #16896
  DuggaSys/microservices/endpointDirectory/fillEndpointDb.php
  DuggaSys/microservices/endpointDirectory/installEndpointDb.php
  DuggaSys/microservices/endpointDirectory/microserviceList.php
  DuggaSys/microservices/endpointDirectory/newMDStructureTest.md
Labels: Grupp 2 - 2025

#16906 Re-engineered microservice retrieveCodeviewerService #16830
  DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php
  DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php
  DuggaSys/microservices/codeviewerService/editCodeExample_ms.php
  DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php
  DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php
Labels: Grupp 2 - 2025

#16900 Re-engineer microservice createNewCodeExample
  DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
  DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php
  DuggaSys/microservices/sectionedService/createListEntry_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
Labels: Grupp 2 - 2025

#16952 Updated microservice directory UI to match mock-up
  DuggaSys/microservices/endpointDirectory/microserviceList.php
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#16895 Changed the JQuery to JS #16671
  DuggaSys/codeviewer.js
Labels: Grupp 3 - 2025

#16903 G3-2025-v4-#16772-change-jquery-in-codeviewer-2981-to-3478
  DuggaSys/codeviewer.js
  codeviewer_add_update_templates.md
Labels: Grupp 3 - 2025

#16917 Issue 16829, Re-engineer microservice for retrieveUsername_ms.php
  DuggaSys/microservices/accessedService/retrieveAccessedService_ms.php
  DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createCourseVersion_ms.php
  DuggaSys/microservices/courseedService/createNewCourse_ms.php
  DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
  DuggaSys/microservices/courseedService/updateCourse_ms.php
  DuggaSys/microservices/fileedService/updateFileLink_ms.php
  DuggaSys/microservices/sectionedService/createListEntry_ms.php
  DuggaSys/microservices/sectionedService/updateCourseVersion_sectioned_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
  DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
  DuggaSys/microservices/sharedMicroservices/retrieveUsername_ms.php
Labels: Grupp 2 - 2025

#16991 G2 2025 v4 #16966 a23oskme
  DuggaSys/microservices/endpointDirectory/fillDependenciesDb.php
  DuggaSys/microservices/endpointDirectory/fillEndpointDb.php
  DuggaSys/microservices/endpointDirectory/installEndpointDb.php
  DuggaSys/microservices/endpointDirectory/setupEndpointDirectory.php
Labels: Grupp 2 - 2025

#17021 Create script to be able to download Microservice directory database #17011
  DuggaSys/microservices/endpointDirectory/downloadDb.php
Labels: Grupp 2 - 2025

#16986 Get tutorial for refactoring - Issue #16933
  DuggaSys/microservices/Microservices Documentation/microserviceRefactorGET.md
Labels: Grupp 2 - 2025

#16995 Documented updateUserPassword_ms.php
  DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
Labels: Grupp 2 - 2025

#17029 Added delete functionality to the UI
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17034 Documented addCladd and addUser
  DuggaSys/microservices/Microservices Documentation/accessedService.md
Labels: Grupp 2 - 2025

#17001 Re-engineer microservice retrieveResultedService #16951
  DuggaSys/microservices/resultedService/getUserAnswer_ms.php
  DuggaSys/microservices/resultedService/retrieveResultedService_ms.php
Labels: Grupp 2 - 2025

#16982 Added clarifications to tutorial 16976
  DuggaSys/microservices/Microservices Documentation/microserviceRefactorPOSTWithAnswer.md
Labels: Grupp 2 - 2025

#17032 Improve error handling for microserviceUI.php when database is missing. #17024
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#16997 Documentation for microservices createListEntry and deleteListEntries.
  DuggaSys/microservices/Microservices Documentation/sectionedService.md
Labels: Grupp 2 - 2025

#16909 Documentation for createNewCodeExample and createNewListEntry
  DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
  DuggaSys/microservices/Microservices Documentation/template.md
Labels: Grupp 2 - 2025

#16953 Documentation of getUid_ms.php and isSuperUser_ms.php
  DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
Labels: Grupp 2 - 2025

#16988 Documented setAsActiveCourse and updateSecurityQuestion
  DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
Labels: Grupp 2 - 2025

#17006 G3 2025 v3 #16722 view buttons position
  DuggaSys/sectioned.js
  DuggaSys/sectioned.php
  Shared/components/Dropdown.js
  Shared/css/style.css
  Shared/icons/hamburger_menu_google_fonts.svg
Labels: Grupp 3 - 2025

#16916 G3 2025 v4 locate and change the j query used in sectioned.js with normal js setup and event listeners line 3530 4082
  DuggaSys/sectioned.js
Labels: Grupp 3 - 2025

#17069 Make the template more clear for documentation of Microservices + fix accessedService.md #17059
  DuggaSys/microservices/Microservices Documentation/accessedService.md
  DuggaSys/microservices/Microservices Documentation/template.md
Labels: Grupp 2 - 2025

#17072 Changed the name of helper function to curlService - Issue #17067
  DuggaSys/microservices/curlService.php
Labels: Grupp 2 - 2025

#17062 Reverted to original working code WITH the try catch
  DuggaSys/microservices/endpointDirectory/microserviceUI.php
Labels: Grupp 2 - 2025

#17084 Update curlService.php
  DuggaSys/microservices/curlService.php
Labels: Grupp 2 - 2025
